### ISSUE TITLE
什么时候发布第一个版本？

### ISSUE THREAD

**Issue by zhy272** [CeuiLiSA/Pixiv-Shaft#1]
如题

**Comment by CeuiLiSA** [comment]
几个月之后吧？关键我一个人写写得慢啊，有人帮忙吗，另外一个问题，去哪发布啊。。酷安已经禁了类似的应用

**Comment by MicroMe4** [comment]
F-droid 可以试一试
毕竟open source

**Comment by OharaRinne** [comment]
发布在Play Store？

**Comment by CeuiLiSA** [comment]
对，到时候下载量   5+，希望有你们一份

**Comment by OharaRinne** [comment]
好的2333

**Comment by CeuiLiSA** [comment]
https://play.google.com/store/apps/details?id=ceui.lisa

**Comment by Lboy-C** [comment]
@CeuiLiSA 建议蓝奏云/滑稽
其实sourceforge.net也行

**Comment by CeuiLiSA** [comment]
已上线
