### ISSUE TITLE
评论区的建议

### ISSUE THREAD

**Issue by soloopooo** [CeuiLiSA/Pixiv-Shaft#101]
建议评论区支持小表情的显示，留着(heart)等文字版有时候非常让人迷惑。

**Comment by CeuiLiSA** [comment]
有大佬指导一下吗，我不知道怎么弄

**Comment by soloopooo** [comment]
感觉评论区的文字进行小表情的完全匹配然后替换成小表情就行了吧...具体代码我也不清楚，因为我又不开发Android（

**Comment by duzhaokun123** [comment]
@soloopooo 有小表情的实例吗, 我看一下小表情长什么样

**Comment by duzhaokun123** [comment]
@CeuiLiSA 可能可以用`SpannableString`

https://stackoverflow.com/a/28347404

**Comment by CeuiLiSA** [comment]
好！这东西困扰我好久了，不知道能不能搞定

**Comment by soloopooo** [comment]
> @soloopooo 有小表情的实例吗, 我看一下小表情长什么样
pixiv原版客户端里有小表情，还有网页版里的大表情

**Comment by CeuiLiSA** [comment]
更最新版上去看下吧，做了
