### ISSUE TITLE
一言闪退

### ISSUE THREAD

**Issue by mikusaa** [CeuiLiSA/Pixiv-Shaft#102]
一言在随机几次之后会闪退，具体到五次之后必闪退。
Redmi K20Pro，MIUI12

**Comment by soloopooo** [comment]
Miui11 小米9 Android Q快速点击切换，会返回到开始界面，不闪退，你试试慢点点击切换试试

**Comment by duzhaokun123** [comment]
@soloopooo 应用可能已经崩了, 但第一次不提示, 退出当前`Activity`假装无事发生, 只有日志默默记录了一切

(我自己的理解, 肯能有误)

**Comment by CeuiLiSA** [comment]
确实是闪退了。因为之前取了个巧
`        baseBind.hitoType.setText(TYPES[(int) response.getType().charAt(0) - (int) 'a']);
`
这个要改一下

**Comment by CeuiLiSA** [comment]
其实这个功能不该出现在这个app里，现在已经从里面剔除了。如果有时间的话，另开一个app专门做一言吧
