### ISSUE TITLE
建议 下载图片使用 Glide

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#103]
`Glide`获取图片文件, 直接复制就好, 如果之前加载过可使用缓存

```java
File file = Glide.with(context).asFile().load(url).submit().get();
```

**Comment by CeuiLiSA** [comment]
好

**Comment by CeuiLiSA** [comment]
Glide asfile有进度监听和改文件名的方法吗，这俩还是挺重要的

**Comment by duzhaokun123** [comment]
文件获取的是 Glide 缓存 里的文件, 要自己复制出来

进度监听实现很复杂, 要重写`AppGlideModule`实现,具体请自行查找

或者找一个实现了进度监听的第三方 glide 库

**Comment by CeuiLiSA** [comment]
下载功能已更新，修复了之前的几个bug
