### ISSUE TITLE
预览图片会卡住直到图片加载完成才能反应

### ISSUE THREAD

**Issue by soloopooo** [CeuiLiSA/Pixiv-Shaft#104]
预览图片有大概率会图片显示区域一片白（若源文件过大必会这样），但背景高斯模糊正常，如果这时候点击了白界面的话就会卡住，试图返回无响应，直到图片加载完成并预览了才有响应
第二张图是返回了的情况
![Screenshot_2020-05-08-22-04-38-910_ceui lisa pixi](https://user-images.githubusercontent.com/36123081/81413456-0ab5a180-9178-11ea-9782-8206b5a8757f.jpg)
![Screenshot_2020-05-08-22-04-45-436_ceui lisa pixi](https://user-images.githubusercontent.com/36123081/81413468-0ee1bf00-9178-11ea-91fa-4b0f00093a6a.jpg)

**Comment by CeuiLiSA** [comment]
好，发现这问题了。已修复
