### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by mikusaa** [CeuiLiSA/Pixiv-Shaft#106]
这个下载功能不够完善，下载链接一旦退出就清空，而且到一定数量就没有下载速度了，下载收藏的图片很蛋疼，需要不断下滑加载才能全部下载。
来自 https://www.himiku.com/archives/pixiv-shaft.html/comment-page-1#comment-3149 的issue

**Comment by CeuiLiSA** [comment]
正在修复

**Comment by CeuiLiSA** [comment]
速度的问题修复了。上个版本为了稳定，设置了最多一个线程参与下载。现在取消了限制
关于下载收藏的图片，暂时还没有好的解法，因为就算是官方也没有一次性获取所有收藏图片的接口。。
