### ISSUE TITLE
在Google play中的版本1.8.8的一些问题

### ISSUE THREAD

**Issue by soloopooo** [CeuiLiSA/Pixiv-Shaft#107]
## 下载：
出现TASK ERROR，在应用内试图设置下载文件夹的时候，显示空白。
* 在github上的版本1.5.5无此问题
### 相关图：
![Screenshot_2020-05-11-10-05-44-883_ceui lisa pixi](https://user-images.githubusercontent.com/36123081/81517956-161eed80-936f-11ea-87c5-60897ce41bb9.jpg)
![Screenshot_2020-05-11-10-05-23-047_ceui lisa pixi](https://user-images.githubusercontent.com/36123081/81517963-19b27480-936f-11ea-8b8a-1bb9ff322791.jpg)
### 1.5.5版本对比图：
![Screenshot_2020-05-11-10-15-15-199_ceui lisa pixi](https://user-images.githubusercontent.com/36123081/81518345-5763cd00-9370-11ea-8634-269dd794f5bb.jpg)

## 设置语言时：
设置完成自动回到主界面后必然崩溃一次，重新进入应用后才正常。
* 在github上的版本1.5.5无此问题
### 相关图：
![Screenshot_2020-05-11-10-06-53-935_ceui lisa pixi](https://user-images.githubusercontent.com/36123081/81518037-5bdbb600-936f-11ea-8624-3387b5edb90d.jpg)
(卡在这里不动 几秒后崩溃)
## 系统相关信息：
![Screenshot_2020-05-11-10-11-24-101_com android se](https://user-images.githubusercontent.com/36123081/81518184-ca207880-936f-11ea-9618-3c77aed48f60.jpg)

**Comment by CeuiLiSA** [comment]
不知道咋回事，，突然就下载不了了。还在找问题

**Comment by 2ciyv** [comment]
同样的问题
![Screenshot_20200511-124949](https://user-images.githubusercontent.com/50177664/81525324-e5e34900-9386-11ea-83c3-e9dd5f1af74f.jpg)

**Comment by CeuiLiSA** [comment]
已修复，发布到play了，审核通过之后请更新
