### ISSUE TITLE
安全问题 导出登录用户的密码泄露风险

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#109]
明文存储密码, 导出至剪贴板, 而应用不需要授权就可以读取剪贴板, 部分应用可能会收集剪贴板数据

建议修改为导出到文件, 并且加上不要与他人分享的警告

如果可能, 对导出文件进行加密

如果一定要记录密码, 建议修改为只保存密码和token的校验, 用户导入时输入密码确认

**Comment by CeuiLiSA** [comment]
好的，这确实是个问题

**Comment by CeuiLiSA** [comment]
已处理，下版本更新上去
