### ISSUE TITLE
建议 提高设置选项用户体验

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#110]
把`onClickListener`设置`relativeLayout`而不是`textView`上

**Comment by soloopooo** [comment]
同意。对手机字体小的人来说这简直反人类操作

**Comment by CeuiLiSA** [comment]
遵命，已修改

**Comment by duzhaokun123** [comment]
遵命不太好吧, 我又不是你上级

duzhaokun123
________________________________
