### ISSUE TITLE
无法设置个人资料

### ISSUE THREAD

**Issue by Shirakami-Sora** [CeuiLiSA/Pixiv-Shaft#112]
设置-个人资料设置点击修改头像会闪退回到- 设置，已经设置允许访问手机存储![bugs](https://raw.githubusercontent.com/Shirakami-Sora/bugs_report/master/Video_20200520_090526_61.gif)

**Comment by CeuiLiSA** [comment]
这是知乎图片选择库的问题，近期在考虑换成其他的

**Comment by CeuiLiSA** [comment]
已修复，正在play提交更新
