### ISSUE TITLE
自己提供会员账号，自用热度排序的问题

### ISSUE THREAD

**Issue by NibaZShab** [CeuiLiSA/Pixiv-Shaft#113]
如果我有2个账号，其中一个是pixiv的会员，另一个不是，怎么才能把是会员的那个账号的热度排序给调用出来，让shaft变成以前那样，使普通账号也能热度排序呢？

**Comment by CeuiLiSA** [comment]
有点难，但是估计可以实现。你能提供下会员账号不

**Comment by NibaZShab** [comment]
账号是同学的，所以我不能提供

**Comment by NibaZShab** [comment]
> 有点难，但是估计可以实现。你能提供下会员账号不

账号是同学的，不是我本人的，所以我不能提供

**Comment by CyanTrigger** [comment]
有个油猴脚本也可以搞出这种效果，但是他的原理是从页面上抓取作品的Fav数，然后再排序，所以要较费时间去排序，并不像会员那样可以立马出结果
https://greasyfork.org/en/scripts/30766-pixiv-previewer
