### ISSUE TITLE
“关于”界面和评论输入栏

### ISSUE THREAD

**Issue by History-exe** [CeuiLiSA/Pixiv-Shaft#114]
1. 关于页面没有显示版本的位置。
2. 评论输入栏疑似与输入法重叠。如图。
![IMG_20200605_124200_100](https://user-images.githubusercontent.com/33642965/83838268-474ecb80-a72b-11ea-86a7-9f15b3190d26.jpg)

**Comment by CeuiLiSA** [comment]
已处理，更新版本试下吧

**Comment by History-exe** [comment]
@CeuiLiSA 确认已修复。
