### ISSUE TITLE
保存格式自定义没有了？

### ISSUE THREAD

**Issue by xushet** [CeuiLiSA/Pixiv-Shaft#120]
以及新版详情页会挡住图片底部一部分区域

**Comment by CeuiLiSA** [comment]
自定义在做了在做了，底部被弯起的弧形遮挡了16dp，应该不要紧吧

**Comment by xushet** [comment]
> 自定义在做了在做了，底部被弯起的弧形遮挡了16dp，应该不要紧吧

不是很要紧，幸苦了
