### ISSUE TITLE
R18图片希望可以存进单独文件夹

### ISSUE THREAD

**Issue by LZTSGS** [CeuiLiSA/Pixiv-Shaft#122]
毕竟R18图片和全年龄图片都存一个文件夹后期分类图片起来难度比较大，或者可以自定义图片命名写入R18标签的话倒简单些…………………………

**Comment by CeuiLiSA** [comment]
这个难点主要是如何判定图片到底属不属于R18，有的图标签就一个少女，或者一个原创，图色的不要不要的

**Comment by CeuiLiSA** [comment]
抱歉。经过考察，确实做不了哈，做了可能也是分类不准确，
