### ISSUE TITLE
同时下载最大数

### ISSUE THREAD

**Issue by LZTSGS** [CeuiLiSA/Pixiv-Shaft#123]
图片下载希望可以按顺序依次下载，更新过后的同时下载多图虽然快，但是因为每张图的下载速率不一样，会让多P图片下载完成后的顺序改变，失去连贯性。至少给个同时下载最大数的设置选项比较好。

**Comment by CeuiLiSA** [comment]
已添加这个功能，需要自己去设置页面打开。等下版本更新吧
