### ISSUE TITLE
列表页面加入下载按钮

### ISSUE THREAD

**Issue by LZTSGS** [CeuiLiSA/Pixiv-Shaft#125]
主界面推荐列表页面和画师作品页面的图片略缩图上加入下载按钮，看到想下载的图片就不用打开大图，直接在列表页面就可以直接下载，使用起来更加方便。

**Comment by CeuiLiSA** [comment]
其实大部分人是来看图的，加个收藏按钮他们都觉得碍眼，再加个下载估计要哭了，设置页面做一个开关吧，可开可关
