### ISSUE TITLE
自定义图片命名小建议

### ISSUE THREAD

**Issue by LZTSGS** [CeuiLiSA/Pixiv-Shaft#126]
自定义图片命名中的字符串之间的连接方式能否进行自定义呢？用“_”作为连接方式总感觉不大醒目
![1594394337680](https://user-images.githubusercontent.com/67962258/87170597-22d6a800-c304-11ea-83bd-ace1cf6f44aa.jpg)

比如如果可以自定义改成⚪就感觉醒目多了。
![1594394306071](https://user-images.githubusercontent.com/67962258/87170644-2ff39700-c304-11ea-98b8-8c2599795439.jpg)

更新出自定义图片命名功能（不过貌似和以前老板里的自定义命名除了UI没多大区别）不过能出也真是让我热泪盈眶。

**Comment by CeuiLiSA** [comment]
哥，之前出过这个功能，让我吃到苦头了，有的人用特殊字符当做分隔符，直接导致文件名怪异部分手机无法生成文件下载不了，所以咱们还是求稳用下划线吧，呐？
