### ISSUE TITLE
标签翻译

### ISSUE THREAD

**Issue by LZTSGS** [CeuiLiSA/Pixiv-Shaft#127]
图片标签可以提供翻译吗？原版P站标签有翻译，但是Pixiv-Shaft没有，日语有的看不懂。
![S00711-10570830](https://user-images.githubusercontent.com/67962258/87215140-f2bff100-c365-11ea-9571-1f25f818ccdf.jpg)
![S00711-10590089](https://user-images.githubusercontent.com/67962258/87215141-f5bae180-c365-11ea-9938-143e4594a284.jpg)

**Comment by CeuiLiSA** [comment]
好的，晚点搞，最近公司事情挺忙的

**Comment by CeuiLiSA** [comment]
加了，下版本更新
