### ISSUE TITLE
希望能增加部分功能

### ISSUE THREAD

**Issue by Khvar** [CeuiLiSA/Pixiv-Shaft#131]
有两个小小的建议，希望您能考虑一下
1.是关于url的识别，目前好像是无法识别pixiv.net/user/userid的链接
2.是希望在收藏的新图片的同时进行下载（可以做个开关？

**Comment by CeuiLiSA** [comment]
1.已处理，升级新版即可
2.收藏和下载按钮离得这么近。。。动动你的小手指头多点一下吧hh
