### ISSUE TITLE
#130 修复后的bug

### ISSUE THREAD

**Issue by hsr-GitHub** [CeuiLiSA/Pixiv-Shaft#132]
还是那个问题，现在对于特别长的评论能展示到最后一行，但是收藏按钮、标签、作者信息什么原本在简介上面的东西被顶到了图片上面。。。。。。
并且除了收藏按钮置于顶层还能看到，其他的全被挡住了233

**Comment by CeuiLiSA** [comment]
我先还原回去了，不过多给简介加了一点空间，这个问题有空了再弄吧，毕竟不是每个人都要在简介写小说哈哈
