### ISSUE TITLE
简介bug#3

### ISSUE THREAD

**Issue by hsr-GitHub** [CeuiLiSA/Pixiv-Shaft#135]
作者在插画漫画简介中跳转到小说的链接（novel/######）点击后会回到主页。

简介中的n个坑。。。。。。

**Comment by CeuiLiSA** [comment]
能否提供一个作品id，这样方便测试

**Comment by hsr-GitHub** [comment]
可以
[https://www.pixiv.net/artworks/83631198](83631198)

**Comment by CeuiLiSA** [comment]
感谢你提供的测试信息，现在已经支持简介跳转具体小说了。而且同时搞定了搜索页面ID搜小说的问题
