### ISSUE TITLE
搜索

### ISSUE THREAD

**Issue by hsr-GitHub** [CeuiLiSA/Pixiv-Shaft#136]
选择ID搜作品后只能搜索插画漫画，希望新增ID搜小说

**Comment by CeuiLiSA** [comment]
加了，下版本更新

**Comment by CeuiLiSA** [comment]
看了下，好像不行。
id搜插画是因为v1/illust/detail  接口可以getIllustByID，获取插画的所有信息。
但是目前pixiv没有通过小说id获取小说详细信息的接口，只能根据id获取小说文字。
我做好了之后， 根据id只能搜到一串小说的文字，关于小说标题，是否收藏过，等等信息都是没有的。所以这个功能应该是不支持了，去掉了

**Comment by duzhaokun123** [comment]
@CeuiLiSA 那获取完整小说信息需要什么

**Comment by CeuiLiSA** [comment]
获取完整小说信息需要根据id获取NovelBean对象的接口，现在官方都是没这接口的

现有的小说列表展示的是NovelBean的列表,  点进小说详情页面之后，根据NovelBean对象的详细内容展示小说详情页面，再用NovelBean的novelID去调另外一个接口获取小说正文。
现在的问题是，只通过小说id，可以强行进去看小说详情，获取小说正文，但是没办法通过小说id获取到NovelBean，所以小说详情只有正文，没有标题等等信息。不能收藏，不能保存，不能关注用户，看不到tag

**Comment by duzhaokun123** [comment]
抓了个web端接口, 有标题,用户id,tag等信息

> https://www.pixiv.net/ajax/user/11/novels

*方式: GET*
*无需Cookie*

**url参数:**
|参数名|类型|内容|必要性|备注|
|-|-|-|-|-|
|id[]|num|小说id|必要||
|lang|str|用户语言|非必要|可能与返回的tag语言有关|

**json返回才不多这样**

```json
{
    "error": false,
    "message": "",
    "body": {
        "13448914": {
            "id": "13448914",
            "title": "\u300c\u30a2\u30ca\u30ed\u30b0\u30cf\u30c3\u30af\u30fb\u30aa\u30fc\u30d7\u30f3\u30ea\u30bd\u30fc\u30b9\u5c0f\u8aac\u30b3\u30f3\u30c6\u30b9\u30c8\u300d\u958b\u50ac ",
            "xRestrict": 0,
            "restrict": 0,
            "url": "https:\/\/i.pximg.net\/c\/600x600\/novel-cover-master\/img\/2020\/08\/03\/11\/38\/20\/13448914_cc55b2d0bc8dfabc76427773472d9924_master1200.jpg",
            "tags": [
                "\u516c\u5f0f\u4f01\u753b",
                "\u4f01\u753b\u76ee\u9332",
                "\u30a2\u30ca\u30ed\u30b0\u30cf\u30c3\u30af\u30fb\u30b3\u30f3"
            ],
            "userId": "11",
            "userName": "pixiv\u4e8b\u52d9\u5c40",
            "textCount": 225,
            "description": "", //预览 太长了删了
            "isBookmarkable": null,
            "bookmarkData": null,
            "bookmarkCount": 109,
            "isOriginal": true,
            "marker": null,
            "titleCaptionTranslation": {
                "workTitle": null,
                "workCaption": null
            },
            "createDate": "2020-08-03T11:38:20+09:00",
            "updateDate": "2020-08-03T11:38:20+09:00"
        }
    }
}
```

**Comment by CeuiLiSA** [comment]
json一般是   "属性"："值，对象，或者数组"，
body对象里面有个 13448914对象，这个是不规范的地方，能修改一下吗，可以去掉这一层对象嵌套，直接让body: {id, title}

**Comment by duzhaokun123** [comment]
又不是我写的接口我有什么办法

只能把`body`写成`List<JsonObject>`, 用`body.getAsJsonObject(id)`获取内容

**Comment by CeuiLiSA** [comment]
这也太草了，web端都这么玩的吗？

**Comment by duzhaokun123** [comment]
> 又不是我写的接口我有什么办法
> 
> 只能把`body`写成`List<JsonObject>`, 用`body.getAsJsonObject(id)`获取内容

看错了`body`应该是是`JsonObject`

**Comment by CeuiLiSA** [comment]
现在支持ID搜小说了，找到一个接口 v2/novel/detail， 根据ID获取小说详情
