### ISSUE TITLE
小说

### ISSUE THREAD

**Issue by hsr-GitHub** [CeuiLiSA/Pixiv-Shaft#137]
我看背景颜色的修改在哪里挂了好久了。。。。。。

1 支持修改背景颜色，文字颜色，字体，背景纹理，字体大小，字间距，行间距。并可以导出为XML再导入，以支持用户间主题共享。

2 支持隐藏状态栏并显示时间电量（虽然没有也没关系，但是加上对刘海屏的支持最好了！）。

3 右下角界面遮挡文字，可以在小说结尾处加几个空行。

4 保存为文本文件到本地

**Comment by CeuiLiSA** [comment]
都是该加的，但是得排期。毕竟自己也有工作和业余生活。请耐心等待

**Comment by hsr-GitHub** [comment]
嗯，可以等的，希望越做越好。

**Comment by CeuiLiSA** [comment]
1的背景色和 2  4都弄好了哈
