### ISSUE TITLE
建议用 kotlin data class 代替 java bean

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#142]
优点
- 写起来轻松一些
- 没有大量生成的`get` `set`方法占行
- `toString()`返回json

缺点
- 没有无参构造器

**Comment by CeuiLiSA** [comment]
听你一句劝，后面试下

**Comment by CeuiLiSA** [comment]
擦。尝试了一下，没有无参构造的话，有时候有点致命，new一个对象要把所有参数都new出来。或者在类里面写默认值，可能只有比较简单的类可以转成dataclass了
