### ISSUE TITLE
无法打开 www.pixiv.net/users/{画师id} 画师主页

### ISSUE THREAD

**Issue by Homulilly** [CeuiLiSA/Pixiv-Shaft#148]
现在碰到画师大多数提供 www.pixiv.net/users/{画师id} 或 pixiv.me/xxx (会跳转到前一种) 格式的个人主页链接。

使用 PixShaft 打开后显示是 不正确的请求 。

**Comment by CeuiLiSA** [comment]
已修复，等待下版本更新
