### ISSUE TITLE
File extension is flawed

### ISSUE THREAD

**Issue by takase1121** [CeuiLiSA/Pixiv-Shaft#149]
PixShaft allows user to determine the filename format and the extension. I have the extension set as PNG. However, this literally renames all image files to PNG, even if they are JPEG. I have a script to extract PNG files from my downloads that simply checked for the file extension and it broke. 

I think a way to fix this is to:
1. remove the option
2. Make it the preferred format for the user. If PNG is not available, than PixShaft will download JPEG.

The file extension is obtainable from the URL to get the file or the `Content-Type` header.

**Comment by CeuiLiSA** [comment]
Thank you for your advice. I'll fix the problem later based on your tips

**Comment by CeuiLiSA** [comment]
done
