### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by paralolik** [CeuiLiSA/Pixiv-Shaft#150]
Good afternoon, can I help with translation into Russian?

**Comment by CeuiLiSA** [comment]
Thanks for your support but, this is a time-consuming and laborious thing. Please consider it carefully. 

I will put all Chinese characters in the value / strings folder, all you need to do is write the corresponding string in Russian in value / strings-ru

When I've sorted out the Chinese string, I'll reopen the issue, and that will be your show time

**Comment by duzhaokun123** [comment]
@CeuiLiSA Did you forget this

**Comment by CeuiLiSA** [comment]
> Good afternoon, can I help with translation into Russian?

Now I have prepared Chinese text resources.
path of project :  Pixiv-Shaft/app/src/main/res/values/strings.xml

All you need to do is translate every line in the file into Russian and put it in another file：
path of project :  Pixiv-Shaft/app/src/main/res/values-ru/strings.xml

For example:
 this is the chinese content in values/strings.xml
<string name="string_239">推荐</string>

you need to write Russian words and put it into values-ru/strings.xml
<string name="string_239">рекомендовать</string>
