### ISSUE TITLE
收藏显示bug

### ISSUE THREAD

**Issue by demolg** [CeuiLiSA/Pixiv-Shaft#153]
复现步骤：
从链接跳转到Shaft插画页面（比如telegram群里的P站插画链接），收藏插画并返回退出；
进入Shaft主界面，从侧边栏进入浏览记录页面；
打开刚才收藏的插画页面，显示为“未收藏”；
进入个人主页查看个人收藏，显示“已收藏”。

**Comment by CeuiLiSA** [comment]
感谢反馈，已修复，下版本更新，
