### ISSUE TITLE
深色模式显示异常

### ISSUE THREAD

**Issue by Hobostar** [CeuiLiSA/Pixiv-Shaft#155]
从V2.2.7开始，深色模式下的关于页面就开始显示异常
<details>
<summary>V2.2.7</summary>

![Screenshot_20200909_101306_ceui lisa pixiv](https://user-images.githubusercontent.com/69063924/92590281-86625f00-f2ce-11ea-9e3c-185b7a103145.jpg)
</details>
到了最新的V2.2.9，关于页面问题依旧，设置页面也变成这样
<details>
<summary>V2.2.9</summary>

![Screenshot_20200909_185223_ceui lisa pixiv](https://user-images.githubusercontent.com/69063924/92591241-1bb22300-f2d0-11ea-9d8e-d179172b9062.jpg)
![Screenshot_20200909_185216_ceui lisa pixiv](https://user-images.githubusercontent.com/69063924/92590899-90389200-f2cf-11ea-80fb-7c5154b9f908.jpg)
</details>
V2.2.6前均正常
<details>
<summary>V2.2.6</summary>

![Screenshot_20200909_101442_ceui lisa pixiv](https://user-images.githubusercontent.com/69063924/92590423-ca556400-f2ce-11ea-89c2-f6601d13f339.jpg)
![Screenshot_20200909_101447_ceui lisa pixiv](https://user-images.githubusercontent.com/69063924/92590429-cd505480-f2ce-11ea-9ffb-e9b945eb5830.jpg)
</details>

**Comment by CeuiLiSA** [comment]
已修复，等下一波app更新。
或者直接拉pull github代码
