### ISSUE TITLE
UI修改建议

### ISSUE THREAD

**Issue by MNEVEC14** [CeuiLiSA/Pixiv-Shaft#157]
![get_thumbnail](https://user-images.githubusercontent.com/30370720/93111561-632e1a00-f6e9-11ea-9bd6-6b6bb5d94766.jpg)
建议这个切换按钮选项改成在左边时显示“公开关注”，右边时显示“私人关注”。或者”公开关注“时切换按钮呈暗色，私人呈主题色。

**Comment by MNEVEC14** [comment]
顺便我发现设置里很多切换按钮也是是左边右边一个颜色，希望改改成这样
![F_5W~OQ6 M}KI})Y3JGYZ@2](https://user-images.githubusercontent.com/30370720/93127075-d93d7b80-f6ff-11ea-9a53-fefa43cd6885.png)
![BQYJ2{T3%~_PK$}`KZO3L@1](https://user-images.githubusercontent.com/30370720/93127080-da6ea880-f6ff-11ea-9e44-931975a0519a.png)

**Comment by CeuiLiSA** [comment]
对夜间模式支持有限，想等界面沉淀下来了花时间统一改夜间模式

**Comment by MNEVEC14** [comment]
> 对夜间模式支持有限，想等界面沉淀下来了花时间统一改夜间模式

额，不是夜间模式，是切换按钮

**Comment by efsg** [comment]
我觉得现在的配色不协调，以前的就很好了

**Comment by CeuiLiSA** [comment]
已修复，等下一波app更新。
或者直接拉pull github代码
