### ISSUE TITLE
登陆报错104

### ISSUE THREAD

**Issue by Eclocksss** [CeuiLiSA/Pixiv-Shaft#158]
电脑网页端测试正常.另外密码错误报错是103, 104报错日文看不懂

**Comment by duzhaokun123** [comment]
什么日文

**Comment by Eclocksss** [comment]
> 什么日文

104:無効なユーザーアカウントです。


我日本语本当下手，文字是OCR识别出来的

**Comment by duzhaokun123** [comment]
无效的用户帐户

**Comment by Eclocksss** [comment]
> 无效的用户帐户

我怀疑是我pixiv账户出问题了, 网页端虽然能登陆但是无法点赞无法再关注其他用户, 不知道怎么回事

**Comment by CeuiLiSA** [comment]
应该是账号本身的问题哈，使用用户名或者邮箱换着登陆试试
