### ISSUE TITLE
收藏过的图，在作者的详情页里就会隐藏

### ISSUE THREAD

**Issue by cero-ss** [CeuiLiSA/Pixiv-Shaft#159]
![S01016-20162221](https://user-images.githubusercontent.com/32891402/96257511-1641aa00-0fed-11eb-92c0-87c963ed22da.png)
收藏过最新的作品后，就会变成这样

**Comment by CeuiLiSA** [comment]
已修复。等下次更新即可。之前不小心默认隐藏掉了
