### ISSUE TITLE
搜索功能建议

### ISSUE THREAD

**Issue by 0o-0** [CeuiLiSA/Pixiv-Shaft#161]
希望能够增加搜索用户，以及通过id来搜索作品或作者的功能。orz😘

**Comment by duzhaokun123** [comment]
搜索 -> 切换(右上角)

功能都有

**Comment by 0o-0** [comment]
> 搜索 -> 切换(右上角)
> 
> 功能都有

没找到啊，只有关键字匹配，收藏数搜索，没有通过id查询，以及搜索用户的功能

**Comment by 0o-0** [comment]
@duzhaokun123 没找到啊，只有关键字匹配，收藏数搜索，没有通过id查询，以及搜索用户的功能

**Comment by duzhaokun123** [comment]
`2.3.2`有
![Screenshot_20201018-035014_Shaft](https://user-images.githubusercontent.com/39830683/96352373-2c3a9200-10f5-11eb-8a6c-56552d3e2815.png)

**Comment by 0o-0** [comment]
最新版没了😶？我最近才用 @duzhaokun123

**Comment by CeuiLiSA** [comment]
哈哈哈委屈你了 @duzhaokun123 这夜间模式确实拉胯。我在想等所有页面都完善结束了一股脑来弄夜间模式
