### ISSUE TITLE
新的个人中心无法通过长按关注，设置成私人关注

### ISSUE THREAD

**Issue by cero-ss** [CeuiLiSA/Pixiv-Shaft#162]
![S01019-19013811](https://user-images.githubusercontent.com/32891402/96442514-d58c9f80-123d-11eb-9d09-a331a34d3c87.png)
长按关注无法变成私人关注

**Comment by cero-ss** [comment]
还有想看作者的漫画，个人收藏还得多点2下，希望能参考下面这个软件的界面
![S01019-19150128](https://user-images.githubusercontent.com/32891402/96443678-91020380-123f-11eb-8051-05f4c3312146.png)

**Comment by CeuiLiSA** [comment]
你好，
1可以加上，做漏了。
但是2可能需要再斟酌一下。
之所以换了个人中心界面，就是因为老版本的页面一次性要请求很多东西，往往是四五个请求同时发出去，显得很重，所以决定优化。现在是展示最重要的东西，这个页面非常轻量级，只发起两个请求，而且都是轻量级的。只能说见仁见智吧，请理解下
