### ISSUE TITLE
夜间模式下 设置-账号管理 界面文字因颜色无法阅读

### ISSUE THREAD

**Issue by ttaox34** [CeuiLiSA/Pixiv-Shaft#165]
![Screenshot_20201029-215524_PixShaft](https://user-images.githubusercontent.com/44202394/97583945-70e9f580-1a32-11eb-8dc2-d10c321865ad.png)
如题，该界面下文字和底色都是白色，导致无法看清文字
同样在夜间模式下有阅读困难的还有 关于 界面
![Screenshot_20201029-215649_PixShaft](https://user-images.githubusercontent.com/44202394/97584092-9d057680-1a32-11eb-943d-6740bd07d81b.png)
大佬辛苦了

**Comment by CeuiLiSA** [comment]
谢谢反馈，之前只优化了几个页面这些还没做到这来。今天弄了吧

**Comment by ttaox34** [comment]
辛苦了！
