### ISSUE TITLE
夜间模式仍然有些界面不正常

### ISSUE THREAD

**Issue by MAT-OUT** [CeuiLiSA/Pixiv-Shaft#166]
如图，夜间模式下，没有显示深色。。。
![Screenshot_2020-11-08-15-33-16-649_ceui lisa pixiv](https://user-images.githubusercontent.com/62179039/98459750-a16f2380-21d8-11eb-8fb6-7256821fbc69.jpg)

![Screenshot_2020-11-08-15-33-25-875_ceui lisa pixiv](https://user-images.githubusercontent.com/62179039/98459754-a6cc6e00-21d8-11eb-92d5-9e82d338530f.jpg)

**Comment by CeuiLiSA** [comment]
done
