### ISSUE TITLE
这个密码显示的设计是不是不太合理。。。

### ISSUE THREAD

**Issue by cheetah747** [CeuiLiSA/Pixiv-Shaft#167]
设置 -》 账号管理 -》显示（密码）

从来没有见过哪一款APP产品的密码是可以直接点一下就能查看的。如果有人借用手机，那这个密码不是很容易泄漏吗？如果很多网站都用的同一个密码，那不是很危险吗？

不是很懂这个设计逻辑。。。有点荒谬。

**Comment by cheetah747** [comment]
点击复制竟然也会在Toast里明文显示密码。。。那这个密码用圆点显示的意义何在？

**Comment by CeuiLiSA** [comment]
想一个场景， 你第一次下载app，没有账号，点的 是游客账号登录，收了一大堆图，现在要去网页端登录绑定账号，但是自己不知道游客账号的密码，这时候怎么办。

当然这是历史版本的遗留问题了，以前不支持app内发送邮箱认证，，只能显示密码让别人去网页端登录。如果你需要的话，我可以把显示密码的功能给干掉，但是会有更多的人跑来问我注册的账号不知道密码怎么办。

**Comment by duzhaokun123** [comment]
@CeuiLiSA 显示密码前认证，例如 Chrome

**Comment by CeuiLiSA** [comment]
mac上的chrome显示密码是输入当前登录mac系统的用户密码来认证的，手机端该用什么认证呢

**Comment by duzhaokun123** [comment]
@CeuiLiSA 解锁用的指纹(如果有)或密码，但调哪个api我没找见

可以参考 https://developer.android.com/about/versions/marshmallow/android-6.0#fingerprint-authentication

**Comment by CeuiLiSA** [comment]
好，最近在搞SAF框架的下载。target api换成30

**Comment by duzhaokun123** [comment]
@CeuiLiSA 找见了 https://developer.android.com/training/sign-in/biometric-auth

**Comment by jungledeem** [comment]
请问方便微信交流一下考公的事儿吗？ 我的微信号是 zhangyi-56
