### ISSUE TITLE
建议增加强调色

### ISSUE THREAD

**Issue by efsg** [CeuiLiSA/Pixiv-Shaft#168]
感觉现在的配色不协调，如果可以自定义或者跟随系统强调色就好了

**Comment by duzhaokun123** [comment]
@efsg  其实不存在跟随系统的主题的

只能自定义

**Comment by efsg** [comment]
> @efsg 其实不存在跟随系统的主题的
> 
> 只能自定义

SR和AppOps不知道怎么实现的，Pixel AOSP应该是有强调色这种东西，LOS之类的也有

**Comment by duzhaokun123** [comment]
查了一下, [这个](https://stackoverflow.com/questions/58352718/get-android-system-accent-color-android-10-system-color-accent)可能有用

**Comment by CeuiLiSA** [comment]
在上海，作为密接被隔离了，没法写代码，晚点

**Comment by CeuiLiSA** [comment]
试下新的release
