### ISSUE TITLE
[Feature Request]希望能够保留画册中第一张图的p数即_p0后缀

### ISSUE THREAD

**Issue by YanceyChiew** [CeuiLiSA/Pixiv-Shaft#169]
从pixiv网站直接保存的文件会保留这个_p0后缀，其官方客户端或者早期的第三方客户端pxview也遵照这个原则。
pixivshaft则有一套自己的可定制重命名方案，其中画册ID与图片序号是必选项，但并不会保留第一张图的图片序号即_p0，这样下载到的图片和官方渠道下载到的合并到同个目录后就可能产生重复。

**Comment by CeuiLiSA** [comment]
在上海，作为密接被隔离了，没法写代码，晚点

**Comment by CeuiLiSA** [comment]
done
