### ISSUE TITLE
建议能自主选择主题颜色

### ISSUE THREAD

**Issue by AlanDinkle** [CeuiLiSA/Pixiv-Shaft#170]
关键是以前浅蓝色太好看了，跟图标颜色也搭配

**Comment by CeuiLiSA** [comment]
我要是会做早就加上去了...

**Comment by CeuiLiSA** [comment]
主要还是不知道怎么实现

**Comment by AlanDinkle** [comment]
> 我要是会做早就加上去了...

额。。以前就是浅蓝呀感觉蛮好看(｡･ω･｡)ﾉ♡如果大家都喜欢深蓝就算了-_-||

**Comment by duzhaokun123** [comment]
> 主要还是不知道怎么实现

在`setContentView`之前改主题

**Comment by CeuiLiSA** [comment]
试下新的release

**Comment by AlanDinkle** [comment]
> 试下新的release

太…太棒了吧٩(♡㉨♡ )۶ 
不过这个是bug吗，图标都是感叹号[Screenshot_20201201_145833.jpg](https://user-images.githubusercontent.com/68946359/100707510-c294ef80-33e5-11eb-84eb-496566e3fc18.jpg)

**Comment by CeuiLiSA** [comment]
测试版还没找到合适的图片，无伤大雅就先这样了

**Comment by AlanDinkle** [comment]
> 测试版还没找到合适的图片，无伤大雅就先这样了

好的谢谢| ू•ૅ㉨•́)ᵎᵎᵎ
