### ISSUE TITLE
部分夜间模式字体颜色需要调整

### ISSUE THREAD

**Issue by MAT-OUT** [CeuiLiSA/Pixiv-Shaft#171]
![IMG_20201202_142536](https://user-images.githubusercontent.com/62179039/100836763-d7878680-34aa-11eb-8479-61cd00c16694.jpg)
![IMG_20201202_142545](https://user-images.githubusercontent.com/62179039/100836773-d9e9e080-34aa-11eb-83d5-9b20104c83fa.jpg)
黑底与黑字搭配，在某些屏幕下难以识别

**Comment by efsg** [comment]
![Screenshot_2020-12-04-22-44-39-169_ceui lisa pixiv](https://user-images.githubusercontent.com/39408740/101177114-64386d00-3682-11eb-89ac-b5a0964b5d46.jpg)
![Uploading Screenshot_2020-12-04-22-44-58-040_ceui.lisa.pixiv.jpg…]()
更新后旧版个人主页的夜间和刷新动画也有问题

**Comment by Retia-Adolf** [comment]
哪儿夜间模式？咋夜间模式？

**Comment by SodaWithoutSparkles** [comment]
Android好像从android 10 之後內置夜间模式，就是背景变黑字体变白。这个bug不是这个app独有的，其他app也有。关掉重开就行了。

**Comment by CeuiLiSA** [comment]
转 #203
