### ISSUE TITLE
GIF无法播放

### ISSUE THREAD

**Issue by dhslcy** [CeuiLiSA/Pixiv-Shaft#173]
提示重构中，暂不支持
所以自然也是无法下载的: )

**Comment by SodaWithoutSparkles** [comment]
最新版本可以了，虽然大的会有点卡，下载完成进度条跑完之后还要等30-60秒左右才能播放，估计是等ffmpeg合成吧。（作者是用ffmpeg合成吗？）

**Comment by CeuiLiSA** [comment]
我这边合成还蛮快的，你合成时长比较长的作品ID发一下吧

**Comment by CeuiLiSA** [comment]
gif短期内先打算用com.waynejo:androidndkgif 了。现在是可以正常播放和下载的。
ffmpeg确实是个好方法，后面有空了会深入研究一下
