### ISSUE TITLE
无法设置下载路径，点击前往设置会导致软件重启。

### ISSUE THREAD

**Issue by V1046-R** [CeuiLiSA/Pixiv-Shaft#174]
更新到2.4.6后，每次点击下载都会提示
　提示
　下载文件不需要请求权限，但
　是需要设定保存文件的目录文
　件夹
　　　　　　取消　　前往设定

点击前往设定也只是导致软件重启。
在设置内惦记图片下载路径也没有任何反应。

更新到2.4.6后出现的问题。
卸载2.4.6，现在回滚安装2.4.4和2.4.2测试，问题依旧。

**Comment by CeuiLiSA** [comment]
手机型号说下呢

**Comment by V1046-R** [comment]
> 手机型号说下呢

Mi6 6+64G MIUI 11.0.5 | 稳定版

**Comment by CeuiLiSA** [comment]
回退2.3.7即可

**Comment by V1046-R** [comment]
> 回退2.3.7即可

问题得到解决了！非常感谢！
