### ISSUE TITLE
下载路径设置为不存在的路径时会导致点击下载闪退

### ISSUE THREAD

**Issue by shirok1** [CeuiLiSA/Pixiv-Shaft#177]
我的索尼手机有把图片视频等等迁移到sd卡上的功能。在迁移的时候，我原本专门为shaft开的文件夹被整个移到了sd卡上（也就是原路径指向的文件夹不存在了）。不知道能不能做成自动创建文件夹？

**Comment by CeuiLiSA** [comment]
这个在授权之前应该是不可以的。也就是说授权的时候必须保证文件夹存在，你这种情况可以在设置页面重新选择SD卡的目录保存然后再去下载试试

**Comment by CeuiLiSA** [comment]
代码上做了一些校验，已授权文件夹被删除的会做提醒
