### ISSUE TITLE
作品详情点击图片全屏预览无法显示

### ISSUE THREAD

**Issue by efsg** [CeuiLiSA/Pixiv-Shaft#179]
应用版本：2.5.3
进度条加载完依旧是黑底不显示图片，可以滑动切换图片但也不会显示

**Comment by History-exe** [comment]
~~应用版本：2.5.1
Android版本：Android 10
手机ROM：LineageOS17.1
同样有这个问题，但是有很少一部分图片可以正常加载~~

应用版本：2.5.3
Android版本：Android 10
手机ROM：LineageOS17.1
上述问题已经解决，但是安装github安装包过程中提示签名不一致。

**Comment by SodaWithoutSparkles** [comment]
2.5.1

同样黑底问题无解，有些可以有些不行。在墙外无需代理

**Comment by SodaWithoutSparkles** [comment]
无法安装2.5.3 github版本，已经新开一个issue处理。应该是签名不见了

**Comment by CeuiLiSA** [comment]
黑底是加载失败了，试试V2.5.4

**Comment by efsg** [comment]
> 黑底是加载失败了，试试V2.5.4

可以了，感谢！

刚刚叕发现一个bug新版本还没修复，详情页某些多p作品折叠预览有问题，截图：
![Screenshot_2020-12-21-17-09-09-877_ceui lisa pixiv](https://user-images.githubusercontent.com/39408740/102760105-ff824f80-43af-11eb-9f51-918dc8bef9ae.jpg)

**Comment by CeuiLiSA** [comment]
这个是之前考虑过的问题。
如果图片为1P，那么界面以图片的尺寸宽高展示图片，图片高则界面高，图片矮则界面矮
如果图片为多P，那么界面以固定高度展示多P图片
现在的问题是只知道第一张图片的高度，第二张图片的高度只有加载完了才知道，所以暂时无解
