### ISSUE TITLE
图片瀑布流和自定义图片预览列数

### ISSUE THREAD

**Issue by History-exe** [CeuiLiSA/Pixiv-Shaft#184]
希望添加**瀑布流**预览图片功能；
希望添加**自定义图片预览列数**功能。

以上两个功能是因为有在平板等大屏幕设备上使用的需求
现在的界面在平板上显示貌似是固定宽度和高度的，增添以上设置后会使界面更美观

**Comment by CeuiLiSA** [comment]
瀑布流预览图片是指什么呢，第二个已经做了，你下载最新版的release试试

**Comment by History-exe** [comment]
谢谢作者，我下载了最新版**2.6.2(153)**，已经达到了效果。

关于瀑布流的描述，我可能没有描述准确。
想要的效果就是在主页浏览图片时，要展示全图，且图片间无空白，每个框紧密贴合。现在**设置为3、4列**就已经达到了这样的效果。

**Comment by History-exe** [comment]
> 瀑布流预览图片是指什么呢，第二个已经做了，你下载最新版的release试试

试用了最新版一段时间，有时会卡死，比如按标签搜索作品时和，加载排行榜图片时。长时间卡住并随后app提示关闭或重启。

Andtoid版本 7.1.2

**Comment by CeuiLiSA** [comment]
可能是其他原因导致的吧，跟瀑布流列数应该关系不大。因为近期核心代码换的挺多的。如果可以的话，希望你能稳定复现一下卡死的问题，我这边也好调试改bug------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;History_exe&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月30日(星期三) 晚上7:06
收件人:&nbsp;&quot;CeuiLiSA/Pixiv-Shaft&quot;<Pixiv-Shaft@noreply.github.com&gt;;
抄送:&nbsp;&quot;CeuiLiSA&quot;<fatemercis@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [CeuiLiSA/Pixiv-Shaft] 图片瀑布流和自定义图片预览列数 (#184)

**Comment by History-exe** [comment]
好。具体出现卡死的操作如下，基本每次都会卡死。
软件基本设置如下：

- 未开启任何直连功能
- 未开启浏览历史纪录
- 图片列数为3列

基本操作如下：
1.点开任意一张主页推荐图片，随之点击其标签，快捷搜索同标签图片。
2.搜索结果正常显示，在未向下滑动搜索结果的情况下，点击图片查看详情无异常。
3.向下滑动一段之后（出现加载新结果动作后）再次点击新加载出的图片查看详情会卡死。

作者上电报吗？之前电报里也私聊你了。

**Comment by CeuiLiSA** [comment]
好的谢谢，我明天看下这段代码吧。现在下班了不太方便。 电报群上的少，所以消息可能没法及时回复...------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;History_exe&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月30日(星期三) 晚上7:23
收件人:&nbsp;&quot;CeuiLiSA/Pixiv-Shaft&quot;<Pixiv-Shaft@noreply.github.com&gt;;
抄送:&nbsp;&quot;CeuiLiSA&quot;<fatemercis@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [CeuiLiSA/Pixiv-Shaft] 图片瀑布流和自定义图片预览列数 (#184)
