### ISSUE TITLE
无法安装github版

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#185]
直接点apk会安装失败，SAI安装会有这个错误信息

`INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1972119458.tmp/0.apk: File  in manifest does not exist`

**Comment by CeuiLiSA** [comment]
卸载play版本，再装github版

**Comment by SodaWithoutSparkles** [comment]
已经卸载，无效
