### ISSUE TITLE
如何不显示原图？

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#186]
![Screenshot_2020-12-21-00-31-20-740_ceui.lisa.pixiv.jpg](https://user-images.githubusercontent.com/64138578/102718591-ee8bfc80-4323-11eb-8748-e8f050817eaa.jpg)

之前选项还在的说(,,•́ . •̀,,)

**Comment by CeuiLiSA** [comment]
新版本把开关加回来了
