### ISSUE TITLE
[2.5.3 ~ 2.5.5] 「批量下载」操作时卡死等问题

### ISSUE THREAD

**Issue by Retia-Adolf** [CeuiLiSA/Pixiv-Shaft#187]
- 点击【批量下载】之后，可能会在加载动画、图片多选界面滑动时卡死。也有可能在查看图片界面左右滑动、点击【收藏】时卡死。强制关闭时不会关闭整个 APP, 而是退回上一级的 Activity, 下载队列也全部丢失。

- https://github.com/CeuiLiSA/Pixiv-Shaft/issues/178#issuecomment-748883004 首次使用时，除非在默认下载路径手动新建文件夹，否则下载任务完成，没有报错，也没有得到下载的图片。

- 网速缓慢的时候，下载的图片很多是损坏的。

- 如果重复下载，一定会在已有的文件上追加，而不是覆盖整个文件，这样一来：

	- 本来完好的图片体积会加倍……

	- 损坏的图片在增加体积之后依然是损坏的……

```
Shaft 2.5.3 ~ 2.5.5
EMUI 4.1.3, Android 6.0
```

**Comment by CeuiLiSA** [comment]
`getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values)`
每次返回的都是全新的文件，比如第一次下载时abc.png，下载同一张图就是abc.png(1)，这个谁帮我解决下

**Comment by CeuiLiSA** [comment]
请安装release 里面的 v2.6.0 版本试下，如果下载不动，去设置里面打开cat代理重新开始下载试试

**Comment by Retia-Adolf** [comment]
哇，更新好快

重复下载时文件越来越大的问题解决了

十分感谢

**Comment by CeuiLiSA** [comment]
用2.6.0的话，批量下载还会卡死吗？

**Comment by Retia-Adolf** [comment]
> 用2.6.0的话，批量下载还会卡死吗？

卡死的问题仍然存在。我发现卡死似乎与批量下载没有直接关系，那只是其中一个可能卡死的地方。其它地方卡死之前有时候也会有征兆，比如：

  - 连续点击查看图片、连续左右翻页查看图片容易卡在 0 %, 或者 100 % 之后却不显示图片；

  - 点击收藏时很久才弹出收藏成功的消息。

**Comment by Retia-Adolf** [comment]
P.S. 虽然重复下载时文件越来越大的问题解决了，但有时又出现一个新的问题：

在应用没有卡死、剩余空间足够、网络也没问题的情况下，下载队列会在完成某个图片 A 的下载后自己停住，必须手动暂停、再点击开始，才会恢复下载。

如果不把下载完成的图片 A 移走，恢复下载后队列里仍然有 A 的任务，原本完好的图片 A 会被一个残缺的小文件给覆盖掉。

似乎队列里小图片很多的时候比较容易出现这个问题。

**Comment by CeuiLiSA** [comment]
谢谢你的反馈，自动暂停的问题已修复，等待google play的2.6.2更新即可
