### ISSUE TITLE
收藏标签自动分类

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#189]
就是收藏页面可以在每次收藏的时候自动对图片包含同一标签的自动归类。如收藏分类标签（自己设定的那个）有"猫"这一分类的话，以后收藏作者标签为"猫"的图片的话会自动分类为"猫"，这样就不用手动分类了。但当作者没标签的话那就没办法，毕竟不可能用AI分类，所以需要保留标签手动分类的功能。

**Comment by SodaWithoutSparkles** [comment]
或者可以在收藏里面搜索

**Comment by CeuiLiSA** [comment]
你好，希望我们首先可以明确一点。我们是第三方客户端，所做的功能也是在原版的基础上修改而来的，功能点mainly depends on官方客户端。
官方数据接口返回的数据，不足以支撑你所提出的需求，所以可能无法实现。

详细的可行/不可行的原因，如果需要的话我可以整理成文档发出来。总之确实是接口不支持，并不是我们一句话否决掉的。开发人员也花费了心思，甚至已经开始着手做了， 做到一半发现不可抗力导致无法完成。请理解

**Comment by SodaWithoutSparkles** [comment]
明白，谢谢开发者。我有空自己研究一下吧，成功了就再看看
