### ISSUE TITLE
开源部分没有登陆api接口么？

### ISSUE THREAD

**Issue by fengchuisaman** [CeuiLiSA/Pixiv-Shaft#190]

**Comment by duzhaokun123** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/app/src/main/java/ceui/lisa/http/AccountApi.java

`AndroidMainfirst`->`MainActivity`->`TemplateActivity`->`FragmentLogin`->`login()`->`AccountApi`

顺藤摸瓜也能找见

**Comment by fengchuisaman** [comment]
您说的这个类，我找到了，但是我在项目里面没有找到 这个类的实现方法。



> https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/app/src/main/java/ceui/lisa/http/AccountApi.java
> 
> `AndroidMainfirst`->`MainActivity`->`TemplateActivity`->`FragmentLogin`->`login()`->`AccountApi`
> 
> 顺藤摸瓜也能找见

**Comment by duzhaokun123** [comment]
@fengchuisaman 只需要描述接口就可以, 不需要自己实现
