### ISSUE TITLE
浏览记录中的小说会导致插画错位

### ISSUE THREAD

**Issue by RainChen128** [CeuiLiSA/Pixiv-Shaft#191]
软件版本是2.6.2(153)，渠道是谷歌商店
先浏览一些插画，然后浏览小说，来到浏览记录里查看插画时，会显示更早的记录
比如浏览记录显示的是ABCD①②③EFGHI
插画ABCD和小说①②③能正常查看，
但是点击插画E会显示插画H，
如果点击G/H/I，后方图片不足以顺位就会显示A了

**Comment by CeuiLiSA** [comment]
谢谢你很细致的讲解。我居然没发现这个问题，立马修复

**Comment by CeuiLiSA** [comment]
已修复，等待下个版本更新
