### ISSUE TITLE
预览图图片剪裁问题

### ISSUE THREAD

**Issue by wwjCMP** [CeuiLiSA/Pixiv-Shaft#192]
新增加的多列显示都没有进行剪裁，能把2列显示的剪裁取消或者增加一个选项吗

**Comment by CeuiLiSA** [comment]
当两列显示的时候，长宽比特别奇葩的比如特别扁平，特别高瘦的图片会被剪裁成正常宽高。
现在你是想要剪裁还是不想要剪裁，仅以原图比例展示呢
