### ISSUE TITLE
gif图片预览速度问题

### ISSUE THREAD

**Issue by RoFatNya** [CeuiLiSA/Pixiv-Shaft#193]
遇到大型ugoira图片的播放会相当缓慢
artworks/86431010
比如这个。

**Comment by CeuiLiSA** [comment]
造成缓慢的原因已经找到了。
1.这个文件合成之后太大，播放的时候方式不对，实际上已经合成完了，但是没有开始播放，所以看起来一直在合成，已修复
2.可能是设备性能限制导致合成较慢，我自己S10测试机 855基本上十五秒以内就可以合成完这个作品，修复了第一点之后就可以立即播放了，效果还行
3.现在给合成进度也加了个进度条（之前只有下载GIF 文件有进度条），也可以有效缓解等待合成时的焦虑。
请等待下版本更新。最近临近过年，公司任务比较多，所以做这个APP的时间就变少了。。见谅
