### ISSUE TITLE
希望添加功能：通过原图链接访问 POST 

### ISSUE THREAD

**Issue by Homulilly** [CeuiLiSA/Pixiv-Shaft#194]
使用情景：在使用其他第三方图站 APP 时，有很多图片来源是直接填写了原图链接，这时想去 P 站看时也是通过链接中 ID 拼出 POST 的链接来访问。

可以关联 https://i.pximg.net/ 然后截取最后链接中的 ID 直接访问对应的  POST ？

很好用的客户端，祝大佬新年快乐。

**Comment by CeuiLiSA** [comment]
“拼出 POST 的链接” ， “直接访问对应的 POST”
你好这个我不太理解，能详细讲一下需求吗

**Comment by Homulilly** [comment]
> “拼出 POST 的链接” ， “直接访问对应的 POST”
> 你好这个我不太理解，能详细讲一下需求吗

就是别人分享图片时只提供了原图的直接链接
https://i.pximg.net/img-original/img/2021/01/06/00/04/52/86849274_p0.png 
通过这个链接获取到 pixiv id: 86849274

然后访问 https://www.pixiv.net/artworks/86849274

手机上浏览器直接访问原图链接的话是 403 不会自动跳转

**Comment by CeuiLiSA** [comment]
我懂了。立马做！

**Comment by Homulilly** [comment]
> 我懂了。立马做！

辛苦了，感谢 d(･∀･○)

**Comment by CeuiLiSA** [comment]
好了，下最新的release试试

**Comment by Homulilly** [comment]
> 好了，下最新的release试试

好用，感谢
