### ISSUE TITLE
2.6.2版本登录报103错误

### ISSUE THREAD

**Issue by ZhReimu** [CeuiLiSA/Pixiv-Shaft#195]
![IMG_20210104_135602](https://user-images.githubusercontent.com/58155247/103505224-b7295e00-4e94-11eb-8ddd-2d228aa84cce.jpg)
如图所示，大概是说账号或密码错误？但是用网页版就能正常登录，应该不是账号的问题吧。

**Comment by CeuiLiSA** [comment]
你现在用网页版pixiv.net登录一下呢，看看系统有没有提示你弱密码叫你修改一个强密码、、

**Comment by ZhReimu** [comment]
> 你现在用网页版pixiv.net登录一下呢，看看系统有没有提示你弱密码叫你修改一个强密码、、

确实有的，难道要改密码才能用？

**Comment by CeuiLiSA** [comment]
是的，因为这是官方前段时间新增的限制，改成合规的新密码就能正常在app上登陆了

**Comment by ZhReimu** [comment]
> 是的，因为这是官方前段时间新增的限制，改成合规的新密码就能正常在app上登陆了

终于能用了，可以加个提示的。

**Comment by CeuiLiSA** [comment]
弹出的这段提示，和密码错误的提示一样。所以区分不了到底是真的密码错了还是密码不合规

**Comment by ZhReimu** [comment]
> 弹出的这段提示，和密码错误的提示一样。所以区分不了到底是真的密码错了还是密码不合规

好⑧
