### ISSUE TITLE
最新版本(2.6.3)在MIUI12(安卓10)上频繁出现下载失败问题

### ISSUE THREAD

**Issue by crmmc** [CeuiLiSA/Pixiv-Shaft#198]
更新了最新(2021.1.15)版本2.6.3后，下载图片时频繁提示下载失败，原因总是显示：
Shaft: 下载失败 原因:android.app.RecoverableSecurityExpection:ceui.lisa.pixiv has no access to content://media/external/images/media/568942

而我在设置想要尝试以更换储存位置解决问题，却提示：位置不可更改。

**Comment by CeuiLiSA** [comment]
你是老版本覆盖安装的吗，如果可以的话卸载安装一下。
还是不行的话说一下你的机型

**Comment by CeuiLiSA** [comment]
升级到2.6.5试试呢，大概修了一下，

**Comment by crmmc** [comment]
今天是2020.1.25
更新了最新的2.6.7版本后，shaft下载不会报错了，感谢作者的辛勤付出！
