### ISSUE TITLE
夜间模式配色样式优化集中记录

### ISSUE THREAD

**Issue by sunbeams001** [CeuiLiSA/Pixiv-Shaft#203]
长期更新，夜间模式配色，样式问题集中收录

- [x] 搜索 fragment_search，搜索提示列表底色导致文字无法看清
- [x] 搜索结果过滤 fragment_filter，下拉选项颜色，右下角的“查找结果”颜色
- [x] 作品详情，作品名颜色
- [x] 发现页和动态页的文字颜色
- [x] 刷新动画背景，刷新动画云的颜色
- [x] 旧版个人页面配色
- [x] 长按插画网格后弹出的菜单
- [x] 插画页面长按收藏，按标签收藏页面
- [x] gif 详情页面 作品描述颜色
- [x] 弹出式 dialogue 配色
- [x] 工具栏弹出菜单颜色
- [x] pixivision 图标颜色
- [x] 动态页面切换开关颜色
- [x] 评论页面表情列表底色
- [x] 评论页面按钮图标
- [x] 设置-账号管理
- [x] 设置-编辑账号信息与邮箱
- [x] 设置-个人资料设置
- [x] 排行榜-选择日期-日期选择器
- [x] 以图搜图结果页面，长按菜单中的链接颜色
- [x] 小说阅读界面右上角弹出菜单
- [x] 小说阅读界面卡片主题色
- [x] 小说系列背景
- [x] 下载中描述文字
- [x] 图片加载占位符背景
- [x] ActionBar 图标在纯白底色上不明显
- [x] 批量下载页面底色
- [x] 作品-屏蔽设置，弹窗中的tag，文字颜色和边框样式，适配有屏蔽但未启用状态
- [x] WebView(Pixivision) 通过注入样式支持夜间模式
- [x] 小说阅读页，选择文字后底色
- [x] 精华列占位符背景

**Comment by sunbeams001** [comment]
2. 搜索结果过滤 fragment_filter，下拉选项颜色，右下角的“查找结果”颜色
![image](https://user-images.githubusercontent.com/3478170/105331067-fe8e4900-5c0d-11eb-9268-557623a92e1b.png)

**Comment by sunbeams001** [comment]
3. 作品详情，作品名颜色
![image](https://user-images.githubusercontent.com/3478170/105331256-34333200-5c0e-11eb-88e5-48e8edf2dade.png)

**Comment by sunbeams001** [comment]
4. 发现页和动态页的文字颜色
https://github.com/CeuiLiSA/Pixiv-Shaft/issues/171#issue-754986879

**Comment by CeuiLiSA** [comment]
没有刻意弄成这样，仅仅是因为忘记了，，这些颜色一直是没空弄的，因为自己对色彩也没有研究。如果你有空的话，请在不改动colors.xml的情况下，把colors-night.xml对应的颜色改成你需要的颜色就好了，刻意仿照B站，云音乐，知乎，甚至系统自带APP的配色来填充颜色，谢谢

**Comment by sunbeams001** [comment]
5. 刷新动画，暂时改了一半，过度下拉后的底色还未修改
https://github.com/CeuiLiSA/Pixiv-Shaft/issues/171#issuecomment-738823469

**Comment by sunbeams001** [comment]
6. 旧版个人页面配色
https://github.com/CeuiLiSA/Pixiv-Shaft/issues/171#issuecomment-738823469

**Comment by sunbeams001** [comment]
7. 长按插画网格后弹出的菜单

**Comment by sunbeams001** [comment]
8. 插画页面长按收藏，按标签收藏页面

**Comment by sunbeams001** [comment]
1-8 目前已修改

**Comment by sunbeams001** [comment]
9. gif详情页面 作品描述颜色

**Comment by duzhaokun123** [comment]
建议 关于issues
修改一楼格式成

- [x] a
- [ ] b

```markdown
- [x] a
- [ ] b
```

的形式
这样在外面看会有一个进度条, 且不需要向下翻就可以明确知道完成情况

**Comment by CeuiLiSA** [comment]
感谢 @sunbeams001 的贡献
