### ISSUE TITLE
收藏量筛选有bug

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#205]
比如我选择筛选500人收藏以上的，有时候收藏1000的也会显示不出来。可能是代码里面填错数字了？

或许可以自定义，例如我想筛选50收藏以上的。
还有某些冷门的标签搜寻500+会什么也显示不出来，如果可以在搜寻的时候选择筛选数字，或者显示出来的图片少于某一个数字的时候自动降低收藏门槛。例如我筛选20000+没出任何结果，就降低门槛到15000+。如果15000+只出现了10个结果，那么就降低门槛到10000+，直到结果数大于某个数字（例如50，可调教就最好）

顺带一句，2021新年快乐

**Comment by SodaWithoutSparkles** [comment]
突然发现了可以在搜寻页面更改收藏数限制，在屏幕右边边缘大概几十像素的位置拉出来就行，可是非常容易误触到全面屏手势。

**Comment by sunbeams001** [comment]
XXXXusers入り 之类的是按tag搜索，所以没人加tag的搜不到，也不能直接按多个tag搜索，你说的按收藏数直接搜索是会员功能

**Comment by CeuiLiSA** [comment]
楼上正解

**Comment by SodaWithoutSparkles** [comment]
理论上能不能模仿会员功能，就是让程式请求收藏量之后再增加一个判断决定要不要显示

**Comment by sunbeams001** [comment]
多接口请求合并数据，虽然理论上是可以做到，但是如何合并结果，排序，翻页选择哪些子接口获取新数据，对前页数据的维护，会涉及到很多细节问题

**Comment by SodaWithoutSparkles** [comment]
不能直接在现有搜寻的基础上加一个
```
if (num_fav >= num_fav_required){
    display = true;
}else{
    display = false;
}
```
之类的吗？

P.S. 没空看代码只是有一个思路，平常写C

**Comment by sunbeams001** [comment]
已支持过滤收藏数和tag不符的作品
#228
