### ISSUE TITLE
屏蔽某一个作品

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#206]
根据那个ID屏蔽，不根据标签屏蔽例如你找作品的时候已经确定某些绝对不适合的时候就可以先屏蔽，或是不适当的标签（你觉得这标签不适合这作品，所以在搜寻这个标签的时候把那个作品屏蔽）。

**Comment by CeuiLiSA** [comment]
现在可以针对单个作品屏蔽了，下载2.7.0 release看下
