### ISSUE TITLE
两点小小的建议

### ISSUE THREAD

**Issue by metaphilium** [CeuiLiSA/Pixiv-Shaft#21]
1.建议抽屉中加入「主页」

目前没有「主页」产生的一个问题是，当从非主页页面返回主页时，抽屉仍指示当前页为上一页面。

2.建议图片详情页中下载、相关作品、评论、收藏，尤其是收藏，建议做成悬浮式。

悄悄问一句评论的点赞数为什么都是 1087？

**Comment by CeuiLiSA** [comment]
1.加了
2.现在不是悬浮式嘛。。。
3.因为pixiv没有评论点赞机制，就随便写了个数字1087，本来想写1024的，感觉有点黄
