### ISSUE TITLE
伺服器bug了？

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#211]
首页ok，搜寻搜不到任何东西，个人收藏显示为空。有时候搜寻能搜到，可是热门排序（没会员的那个）是空的。关掉直连有改善，但仍然有很大机会不行
Edit: 关掉直连要等一会才行，一开直连就搜寻不到了

**Comment by CeuiLiSA** [comment]
看pixiv官方推特，他们服务器宕机了。
