### ISSUE TITLE
保存 GIF 时会同步在 Pictures 目录下生成一张静态图片

### ISSUE THREAD

**Issue by sunbeams001** [CeuiLiSA/Pixiv-Shaft#212]
新版好像还是有这个问题
调试了下，ImageSaver 里 这个方法执行后会有静态图 MediaStore.Images.Media.insertImage
我不太熟悉保存流程，可能对其他有影响，你看着改吧
@CeuiLiSA

**Comment by CeuiLiSA** [comment]
hao!
