### ISSUE TITLE
第一次用该软件为什么登录不了

### ISSUE THREAD

**Issue by Content10** [CeuiLiSA/Pixiv-Shaft#213]
![Screenshot_2021-01-25-21-21-51-897_ceui lisa pixiv](https://user-images.githubusercontent.com/19535044/105711424-813b3f00-5f53-11eb-93f5-157bcc073a07.jpg)
这是我一直用的账号可以直接在p站官网登录，刚下载软件想用自己账号登录，就一直提示id密码不正确，只能用内置的没有账号的方法登录

**Comment by Content10** [comment]
我改了下密码就可以登录了。。。我原密码是纯大写字母的 @CeuiLiSA 是不是软件对密码输入有格式检查啊，导致我原密码登录不了

**Comment by CeuiLiSA** [comment]
是因为Pixiv对弱密码用户做了登录限制，必须去P站官网登陆，然后按照要求修改成指定复杂度的密码就可以正常登陆了。
