### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by 751691193** [CeuiLiSA/Pixiv-Shaft#235]
如图，无论是用用户名还是邮箱都是这样，新账号也是，密码已经是强密码了
此外，注册功能也用不了，点注册账号就一直转不出东西
![Uploading IMG_20210209_141607.jpg…]()

**Comment by 751691193** [comment]
我图好像裂了……
总之弹出一串The grant type is unauthorized for this client id

**Comment by Summpot** [comment]
client id被吊销了
全部都挂了

**Comment by RainChen128** [comment]
最近我也有登陆时一直转圈的情况，去网页版看了一眼，发现吃到reCaptcha验证了，不知道这个验证普遍不普遍。
我在网页完成验证以后客户端就能登陆了。

**Comment by 751691193** [comment]
> client id被吊销了
> 全部都挂了

啊这……网页版和原版app都能登录来着，这个怎么解决啊

**Comment by Summpot** [comment]
就等吧

**Comment by NESeeker** [comment]
我也登不上了＼（〇_ｏ）／
![Uploading Screenshot_20210209-232624.jpg…]()

**Comment by sunbeams001** [comment]
是官方禁止低版本登录API调用了，开发者已经在搞了
先用官方版吧

**Comment by ygsk10** [comment]
https://github.com/upbit/pixivpy/issues/158

**Comment by sunbeams001** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/releases/tag/3.0.0
已初步修复

**Comment by demonlingzhu** [comment]
如果最新版还要开代理登录的話，那免代理（翻墙）Pixiv第三方意義何在呢，在此提醒之前未更新v3.0.0未出現登录問題的，谨慎更新，親測更新版本后需代理登录，估计型号是某些直連登录問題未解決

**Comment by duzhaokun123** [comment]
> 如果最新版还要开代理登录的話，那免代理（翻墙）Pixiv第三方意義何在呢，在此提醒之前未更新v3.0.0未出現登录問題的，谨慎更新，親測更新版本后需代理登录，估计型号是某些直連登录問題未解決

意义在于不用开代理看图，如果你开了代理速度更慢或你的代理按流量收费这就有意义了

**Comment by NESeeker** [comment]
意义不是在于它可以用会员功能吗？→_→

**Comment by ygsk10** [comment]
> 意义不是在于它可以用会员功能吗？→_→

那个也不是直连了，相当于作者的公共代理
