### ISSUE TITLE
超长图片略缩图显示问题

### ISSUE THREAD

**Issue by sunbeams001** [CeuiLiSA/Pixiv-Shaft#237]
图片就很长，例如进这个画师主页
id
15459431

瀑布流中，应该限制下最大高度

进一步发现，进入作品详情后canvas因为绘制图像过大会炸掉，应用崩溃

**Comment by duzhaokun123** [comment]
能具体说一下会崩的插画id吗

**Comment by sunbeams001** [comment]
pid
87566853

**Comment by duzhaokun123** [comment]
我没有崩诶，看来我手机内存太大了

**Comment by sunbeams001** [comment]
我还3.3G可用啊，跟这没关系吧

**Comment by duzhaokun123** [comment]
既然只在预览时崩溃，因为`ImageView`其实比屏幕长需要也必须全部画出来，但在查看是不会，因为`PhotoView`其实只要屏幕的大小，且不需要全部画出
那就继承一下`ImageView`，在异常方法处 try 一下，出异常就用别的替代，提示用户点一下，用`PhotoView`查看

**Comment by sunbeams001** [comment]
@duzhaokun123 哥们你写的插画详情布局部分吗，我Glide加了个缩放转换层处理崩溃，但是有点瑕疵

**Comment by duzhaokun123** [comment]
@sunbeams001 绝对不是我写的，不信你查提交记录

**Comment by sunbeams001** [comment]
好吧，各种计算我不敢动了，那等作者回来自己改吧

**Comment by sunbeams001** [comment]
@CeuiLiSA 这里有一个图片大小问题，如果转换层缩放重设了大小，会导致按原图计算的长宽不对应，下方有白边
