### ISSUE TITLE
Hello,关于登录直连实现

### ISSUE THREAD

**Issue by Notsfsssf** [CeuiLiSA/Pixiv-Shaft#243]
[PixEz](https://github.com/Notsfsssf/pixez-flutter)已经实现了登录直连
可以参考一下:

我使用`gomobile`编写了一个go的lib，监听本地端口    
webview设置proxy转发到go层,设置信任所有证书    
go层滤掉sni，作为中间人转发，已经跑通，只是包会大10兆   
可以将项目里的`weiss` [module](https://github.com/Notsfsssf/pixez-flutter/tree/master/android/weiss) 引入gradle,然后`weiss.Weiss.start(port)`,此时登录就不需要代理了    
应该也可以通过java层实现，只是我需要适配ios端所以没有这么干

我测试过使用`okttpclient` interrupt webview的request，get请求还好办，post请求很难拿到ajax的body，用比较麻烦的办法比如注入js代码应该也可以

总之，新年快乐:)

**Comment by CeuiLiSA** [comment]
新年快乐！感谢你的宝贵建议和辛苦开源的代码，果然大佬还是大佬啊

**Comment by niuhuan** [comment]
@Notsfsssf  我想写一个PC版的PXIV浏览器, 可是遇到了一些问题希望您能提供一些帮助

使用Golang通过代理直接访问pixiv没有任何问题。
但是通过修改dns实现免代理会出现connect close by peer。
通过 https://ip/ 再修改http请求header中的hosts, 相信任何证书 , 实现免代理, 会出现 http status  421 , nginx 421 Misdirected Request


![QQ20210808-080743](https://user-images.githubusercontent.com/20847533/128616720-97812e5b-c7b2-4234-892d-ee23a7c4ec59.png)

同样的http请求, 通过java的okhttp3或flutter的dio请求, 则不会出现这种问题
这令我很头痛, 调试了很久也没有好
