### ISSUE TITLE
链接转跳bug

### ISSUE THREAD

**Issue by efsg** [CeuiLiSA/Pixiv-Shaft#250]
支持转跳pixiv.me之后点击链接就会反复转跳，但不确定是不是系统问题
![Video_20210216_083256_526](https://user-images.githubusercontent.com/39408740/108063589-65304680-7096-11eb-8e80-d88a722b0613.gif)

**Comment by sunbeams001** [comment]
换个浏览器试试呢

**Comment by efsg** [comment]
> 换个浏览器试试呢

感觉不是浏览器的问题，从其它应用转跳也有问题

**Comment by CeuiLiSA** [comment]
ROM问题，建议换个主流ROM应该表现正常
