### ISSUE TITLE
在动态页面点进作品详情后，一直向后划，划到已加载的内容全部看完之后后面的内容不会自动加载

### ISSUE THREAD

**Issue by Demolishor** [CeuiLiSA/Pixiv-Shaft#251]
点进动态的作品详情之后向后刷图，刷到最后一张图之后就会卡住，后面的图片不会像官方的客户端一样自动加载出来，而是必须要退出详情页面，向下滑动，待后面的图加载出来才能继续点到详情里，继续向后刷图。

**Comment by CeuiLiSA** [comment]
这功能做好了，更新到新版本试下
