### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by hsr-GitHub** [CeuiLiSA/Pixiv-Shaft#255]
关闭直连以后内置浏览器不走代理（v2rayNG），使用 pixiv 官方 app 打开网页后用 shaft 打开“资源解析中”，“不正确的请求”。

**Comment by CeuiLiSA** [comment]
1.为什么提示“不正确的请求”？
-shaft跳转到登录页面后，登录结果只能用shaft打开，用pixiv打开会报错“不正确的请求”
-pixiv跳转到登录页面后，登录结果只能用pixiv打开，用shaft打开会报错“不正确的请求”

2.“不走代理” 可以开全局模式再登录
