### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by 1david389** [CeuiLiSA/Pixiv-Shaft#256]
Great app overall and is useful for finding and following new artists. I've encountered a few issues though.

First one being, there isn't any option to copy a post's link directly via the app. Whenever pressing the share button it only allows you to send it to other apps and not just copy it to your clipboard. Right now I have to use third party apps if I want to do it. 

Second, there is no option to view R-18 content via the recommended on the home page, and the R-18 only category only appears in the website and is not existed on the app. It's really a shame having to use the browser version of the app for that purpose alone. 

I asked for help on Telegram and they told me it would be best to post over here directly, so that's what I'm doing. If the stated above could be addressed it would be much appreciated. Thanks!

**Comment by sunbeams001** [comment]
Just click the artwork id and it will be copied to your clipboard.

**Comment by duzhaokun123** [comment]
@sunbeams001 it is only id, but we neet link

**Comment by CeuiLiSA** [comment]
All done. Please wait for the new version
