### ISSUE TITLE
3.0.6版本收藏问题

### ISSUE THREAD

**Issue by cero-ss** [CeuiLiSA/Pixiv-Shaft#257]
![S10219-17292215](https://user-images.githubusercontent.com/32891402/108486187-c34c6c00-72d8-11eb-9694-c757fa7d9c93.png)
点击收藏会自动把所有标签勾选中

**Comment by CeuiLiSA** [comment]
之前故意弄成默认全选自动分类的，那我改回去吧

**Comment by SodaWithoutSparkles** [comment]
默认全选自动分类挺好的啊，那样就能在收藏里面按标签搜寻了。不如加一个选项？
