### ISSUE TITLE
3.0.5版“按标签收藏”功能建议

### ISSUE THREAD

**Issue by Nigel-NI** [CeuiLiSA/Pixiv-Shaft#258]
最新的3.0.5版，长按收藏按钮进入“按标签收藏”功能时，默认所有标签为选中状态。我只希望添加一个或两个标签，但是其他不想添加的标签我仍需一个一个手动取消选中，所以希望能增加一个“全选”或“反选”功能或选项。期待作者大大的回复，谢谢！

**Comment by CeuiLiSA** [comment]
现在改成原来那样，默认不选中了
