### ISSUE TITLE
Regarding the latest update (3.0.6)

### ISSUE THREAD

**Issue by 1david389** [CeuiLiSA/Pixiv-Shaft#259]
I  [made a post](https://github.com/CeuiLiSA/Pixiv-Shaft/issues/256) just a day ago regading the R18 content on the app. Whilst the latest update sure was a step forward in having this sort of content on the app, it wasn's exactly what I meant when I suggested it. I meant that the R18 content would be displayed alogside other posts on "Recommended for you" section, [like on this page](https://www.pixiv.net/discovery) (it depends on the user settings if the adult content involving nudity would be presented there). I'm not sure if it's possible, but it would be great if it is. 

On a-not-so-unrelated note, on the main app and on the website there is also the feature of having being recommended more posts after liking one of them on the homepage. Meaning it would roll out a few more posts on the homepage that are similar to the one you liked. 

Thanks for the quick response

**Comment by sunbeams001** [comment]
@1david389 For the "Recommended for you" section, does it supported by the official app? I mean, it will be hard to add such feature if the API is not allow us to do so.

**Comment by CeuiLiSA** [comment]
1.R18 content in recmd page， not supported.
2.show related illust after post-like illust, done.  see v3.0.8 in TG group
