### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by HinataKato** [CeuiLiSA/Pixiv-Shaft#260]
在默认直连登录的时候Google的验证会打不开，无法登录
关闭直连之后需要杀掉应用重新打开才能登录，不然就会一直出现错误，请刷新

**Comment by andan0** [comment]
网络正常的情况下登录显示被限制访问之后无法连接到reCAPTCHA服务，重新加载仍是这样。

**Comment by CeuiLiSA** [comment]
考虑了下，先把直连登录给砍了。暂时开代理登录下吧，这样是可以正常登录的
