### ISSUE TITLE
底栏图标大小不一致。

### ISSUE THREAD

**Issue by Ra1sin** [CeuiLiSA/Pixiv-Shaft#264]
![Screenshot_20210223_003735](https://user-images.githubusercontent.com/58866317/108739421-9960a700-756f-11eb-8ef9-0090fb4c34cf.jpg)

动态图标明显过大了。

**Comment by duzhaokun123** [comment]
甚至风格都不一致

**Comment by CeuiLiSA** [comment]
瞎扒拉的几个，各位有什么好的推荐吗

**Comment by sunbeams001** [comment]
哈哈经典问题，程序员该不该搞美工

https://www.iconfont.cn/

**Comment by sunbeams001** [comment]
@Ra1sin @duzhaokun123 试试效果

**Comment by duzhaokun123** [comment]
@sunbeams001 大半夜的，没有ci构建，很难办的

**Comment by CeuiLiSA** [comment]
感谢 @sunbeams001
