### ISSUE TITLE
使用 SAF 指定保存路径

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#266]
实在不行先下到缓存再移过去

**Comment by CeuiLiSA** [comment]
其实之前做过了一版，100个手机里面就有那么两三个选不了，要么选完就卡死，要么SAF被砍完全不支持。为了让所有人都正常，就做成现在这个比较保守的方案保存到Pictures目录下了

另外以前还遇到一个问题，在已知文件名的情况下，如何判断自选文件夹下的某个文件，是否已下载过？

**Comment by CeuiLiSA** [comment]
https://stackoverflow.com/questions/46180851/get-a-documentfile-that-is-a-child-of-a-document-tree-without-using-findfiles


https://community.commonsware.com/t/using-saf-how-to-check-if-a-file-already-exists/476

**Comment by duzhaokun123** [comment]
为什么要判断自选文件夹下的文件是否下载过？

**Comment by CeuiLiSA** [comment]
不判断的话，每次点下载都会创建新的文件，假如文件名是ABC.png，再调用一次documentFile.createFile就会新生成一个
ABC（1）.png

**Comment by duzhaokun123** [comment]
> 不判断的话，每次点下载都会创建新的文件，假如文件名是ABC.png，再调用一次documentFile.createFile就会新生成一个
> ABC（1）.png

难道不应该吗，是否下载过应该应用在别的地方记录

**Comment by CeuiLiSA** [comment]
如果下载按钮的功能是文件已存在，不下载，
你在相册删了图片，app还记录着已下载，下载点不动怎么办？

如果下载按钮的功能是文件已存在，仍然下载，
那重复同样的文件就会越来越多，只是名字不一样而已

现在的需求很简单，我在下载图片之前，先判断文件存不存在，存在就直接写入到这个文件上，不新建
如果不存在，就新建一个文件，然后写入，File可以，且很简单，用DocumentFile就很恶心了

**Comment by duzhaokun123** [comment]
下载按钮的功能是文件已存在，不下载，但下载过的显示重新下载，删掉已有的下载记录再下载

**Comment by CeuiLiSA** [comment]
那你觉得APP需不需要记录已经下载过某个图片

**Comment by duzhaokun123** [comment]
> 那你觉得APP需不需要记录已经下载过某个图片

是只记录名字作者日期和路径还是内容都记录上

**Comment by CeuiLiSA** [comment]
都记录吧

**Comment by duzhaokun123** [comment]
> 都记录吧

啊这，那不如改成下载在私有目录，用户可选导出到自选

**Comment by CeuiLiSA** [comment]
我先再做一版试试。

**Comment by CeuiLiSA** [comment]
...这。所以DocumentFile怎么判断自己指定目录下的一个文件是否已存在？不管怎样这个判断肯定是需要用到的吧

**Comment by CeuiLiSA** [comment]
试下这个
[https://github.com/CeuiLiSA/Pixiv-Shaft/releases/tag/3.0.9](url)
给个反馈

**Comment by duzhaokun123** [comment]
bugs:
- SAF 模式下
  - 移除下载文件或撤销访问权限后尝试打开黑屏而不是提示"文件已被删除或移动"
  - 修改下载路径后没有立即更新显示
- 不同路径下可重复下载，但后下载完的项目会覆盖之前的项目 (这可能是 feature)
- 下载按钮点两次后才变为重新下载
- 二级详情始终为下载图片

其他还好吧

**Comment by CeuiLiSA** [comment]
好的。后面修吧，今天摸鱼一天了，做点正事

**Comment by duzhaokun123** [comment]
所以为什么要直接下载到目标文件而不是完成后再移过去

**Comment by CeuiLiSA** [comment]
移过去还是得考虑存不存在的问题，cache文件夹判断一次，目标外部目录再判断一次，不是给自己找事吗。。

**Comment by duzhaokun123** [comment]
cache 为什么要判断

**Comment by CeuiLiSA** [comment]
先讨论清除方案吧，如果下载到cache里怎么导出，什么时候导出

**Comment by duzhaokun123** [comment]
> 先讨论清除方案吧，如果下载到cache里怎么导出，什么时候导出

看了一代码，好像确实没有必要先下载到 cache 里

**Comment by sunbeams001** [comment]
SAF 模式下不能正确区分R18目录？会全部下到选定的目录
