### ISSUE TITLE
还是闪退……

### ISSUE THREAD

**Issue by Auralcraft** [CeuiLiSA/Pixiv-Shaft#27]
1.0.28版本，登录就闪退，华为荣耀10 Lite（Android 9.0，EMUI9.1.0）。

**Comment by CeuiLiSA** [comment]
卸载重装试试？有空了我们俩单独调试一下

**Comment by realnabarl** [comment]
我也闪退，红米Note4X，MIUI 8.5 稳定版（8.5.7.0）。登录账号后出现一个首页的界面，但是内容看不到，全白的，然后会提示授予本机存储权限，给后就会崩溃。之后每次开都是直接闪退。

**Comment by CeuiLiSA** [comment]
麻烦给个联系方式？解决这问题就靠和你联调了

**Comment by realnabarl** [comment]
用QQ吧：404699388
