### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Marius-Streicher** [CeuiLiSA/Pixiv-Shaft#28]
关闭直连，打开小飞机/开直连，关闭小飞机是这样的
![qq_pic_merged_1567550751840](https://user-images.githubusercontent.com/54869560/64213486-b4ed7300-cedf-11e9-8382-015128674b3c.jpg)
关直连和小飞机是这样的
![qq_pic_merged_1567550768607](https://user-images.githubusercontent.com/54869560/64213518-d2bad800-cedf-11e9-84d2-413533c07cfd.jpg)
一个是HTTP400，一个是超时...

**Comment by CeuiLiSA** [comment]
已修复
