### ISSUE TITLE
只能改背景色不能改字体颜色有点问题

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#280]
用这个app看pixiv小说的话，改颜色会有问题。
选深色背景字体是白色没问题，选浅色背景字体仍然是白色这就很有问题了，选近似白色的背景右上角更多的按钮还会有保护色。
所以建议可以在看小说的时候更改字体颜色和背景色，然后让右上角更多的按钮在看小说的时候跟随字体颜色。
例如选择#FFFFFF 的时候 整个页面基本看不见东西了。所以在更改背景色下面加一个选项是更改文字颜色就行了(吧？)

**Comment by sunbeams001** [comment]
異議あり!
深色背景省电还保护视力
