### ISSUE TITLE
按收藏就自动按标签收藏

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#283]
像[#258](https://github.com/CeuiLiSA/Pixiv-Shaft/issues/258)一样，不过不用长按就能做到。

（其实这个就是[#189](https://github.com/CeuiLiSA/Pixiv-Shaft/issues/189)我想说的东西...）

**Comment by sunbeams001** [comment]
老哥，确信当时已经完全了解你的需求了，但是你看没看过接口数据格式呢，之前要帮你做这功能来着，但是官方不支持啊，返回数据里看不出哪些是收藏过的tag

**Comment by SodaWithoutSparkles** [comment]
那就算了吧
