### ISSUE TITLE
manually set dark mode ignored

### ISSUE THREAD

**Issue by benjaminBrownlee** [CeuiLiSA/Pixiv-Shaft#285]
app version: 3.1.4
android version: 7.1.1

Sorry, I realize the primary language of this project is Chinese, but English is the only language I speak. Hopefully my comments can still be useful.

Since my version of android doesn't have a system wide dark mode, I use the manual option for dark mode. However, suddenly the app began opening in light mode again. Changing between system, light, and dark modes seems to have no effect now. I tried clearing app data, reinstalling, and even installing older APKs, but the theme setting still will not go into dark mode. I even tried switching the language (English used to not work with dark mode before) but all of them still open in light mode. I could not find any messages in the logcat regarding theming when the app launches. I am sort of lost as to how to start debugging this since it spans versions that I have not previously experienced issues before.

**Comment by sunbeams001** [comment]
This is a bug, got fix it several days.
For your problem, follow these instructions:
1. Remember the position of Settings-Themes
2. Change Language to Chinese(简体中文)
3. Change Settings-Themes to what you want
4. Change back Language to English
