### ISSUE TITLE
Help with GFW bypass in my app

### ISSUE THREAD

**Issue by yellowbluesky** [CeuiLiSA/Pixiv-Shaft#289]
Hello, I am the author of another [third party Pixiv Android application](https://github.com/yellowbluesky/PixivforMuzei3). My app has quite a number of users from China, and I would really like to implement a GFW bypass for them.

I have tried to copy things as closely as you have it, but so far it is not working. I hope it is ok if I use Kotlin compared to your Java 😊

[Here](https://github.com/yellowbluesky/PixivforMuzei3/blob/CeuiLiSA-experimental-GFW-bypass/app/src/main/java/com/antony/muzei/pixiv/provider/network/OkHttpSingleton.kt#L33) is where the OkHttpClient is setup..

[This](https://github.com/yellowbluesky/PixivforMuzei3/blob/CeuiLiSA-experimental-GFW-bypass/app/src/main/java/com/antony/muzei/pixiv/provider/network/RubySSLSocketFactory.java) is my SSLSocketFactory. It is copied exactly the same as it is in Pixiv-Shaft

[This](https://github.com/yellowbluesky/PixivforMuzei3/blob/CeuiLiSA-experimental-GFW-bypass/app/src/main/java/com/antony/muzei/pixiv/provider/network/RubyHttpDns.java) is my HttpDns, and again it is copied exactly the same as it is in Pixiv-Shaft.

Your GFW bypass works for getting the JSON describing the images, but when I try to download the actual images I get this error:

![image](https://user-images.githubusercontent.com/11283778/111063997-c61c3480-8505-11eb-81c9-eb8b0a3c7e34.png)

I have tried using a HostnameVerifier to forcibly accept the unverified hostname, but that results in HTTP 421 errors.

I would really appreciate it if you could spare some time to look at my code, or if you can provide some advice on what I'm missing. I will make sure I credit you for any work that you perform.
Please let me know if you need any more information

To replicate the issues:

1. Install Muzei, and set it up as your wallpaper
2. Clone my app and install it
3. Login to Pixiv through my app
4. Select Bookmark or Feed ("收藏（需登录）" or "关注订阅（需登录）") artwork mode
5. "Immediately clear image cache" / "清除图像缓存" while reading logcat

**Comment by CeuiLiSA** [comment]
I don't know if I can help you solve this problem, but please leave your most frequently used contact information and I will contact you. The communication efficiency of leaving messages on github is very low

**Comment by yellowbluesky** [comment]
Hi, Please contact me at ***@***.***

Thank you

**Comment by CeuiLiSA** [comment]
hey guy your email cannot be seen
