### ISSUE TITLE
拦截规则在关闭应用重开之后仍然没有更新

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#290]
刚刚看了一下好像portal的regex规则没有应用，麦片哥的规则也没。

强制关闭，清除缓存，关掉功能重开都试过了。

怀疑是jsdelivr那边没有更新，但是github这边更新了。

是不是需要加个东西自动同步github和jsdelivr？

应用版本3.1.4

**Comment by sunbeams001** [comment]
必须有tag后才生效（详见 jsdelivr 网站说明）

**Comment by sunbeams001** [comment]
小改了一下，现在是读取master分支最新内容了，等下次 release 就能使用这个特性了
