### ISSUE TITLE
登录的时候无法reCAPTCHA认证

### ISSUE THREAD

**Issue by jacknifeXcrossbow** [CeuiLiSA/Pixiv-Shaft#294]
登录时，输入账号密码之后点击登陆之后，会出现“请进行reCAPTCHA认证”的按钮，但是这个按钮是灰色的，点不了，导致我认证不了，也登陆不进去。
（已开梯子）
![Screenshot_2021-03-21-18-58-02-917_ceui lisa pixi](https://user-images.githubusercontent.com/81081211/111902268-9de98400-8a77-11eb-8872-7a3365cf5d08.jpg)

**Comment by soloopooo** [comment]
这个“请进行reCaptcha验证”不是按钮，只是单纯的一个提示。之前我用SNI绕过方式登录网页的时候，也出现过这个问题，不过也没有解决

**Comment by jacknifeXcrossbow** [comment]
> 这个“请进行reCaptcha验证”不是按钮，只是单纯的一个提示。之前我用SNI绕过方式登录网页的时候，也出现过这个问题，不过也没有解决

解决了，出现这个问题可能是因为我之前用的是在Google play上下载的版本，刚刚下载了一个github提供的版本，登录时没有要求我进行认证

**Comment by CeuiLiSA** [comment]
是的，某个直连登录的版本有可能会出现加载不出来recap验证，后面版本改成开代理登录就可以了
