### ISSUE TITLE
关于收藏的反馈

### ISSUE THREAD

**Issue by ScrapW** [CeuiLiSA/Pixiv-Shaft#296]
- 希望可以新增“收藏时自动添加收藏夹中已存在的标签”选项
比方说一个作品的标签有a，b，c三个，我当前收藏夹中已存在的标签有c，d，e三种，点击收藏该作品时自动打上c标签

- 现存选项“按标签收藏默认全选标签”会把不属于该作品但属于收藏夹内的标签也选上

- 当选中的标签较多时会显示“too many items”并收藏失败

**Comment by CeuiLiSA** [comment]
官方有个按标签收藏的数量限制，现在还不知道收藏到多少个标签里就会报这个错，“too many items”。

**Comment by SodaWithoutSparkles** [comment]
逐个逐个试试

**Comment by ScrapW** [comment]
> 官方有个按标签收藏的数量限制，现在还不知道收藏到多少个标签里就会报这个错，“too many items”。



> 逐个逐个试试，再根据结果慢慢增加减小

我这试出来上限10个
