### ISSUE TITLE
首页点击收藏有几率导致其他图片刷新

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#302]
首页会显示很多图片，有几率按了收藏之后在其之后的图片，包括还在显示中的图片刷新。如有时候首页有几个喜欢的然后第一个点了收藏，第二个会不见了。

建议改为刷新显示区域外的，你看不见自然也不会担心。看见你想要收藏的然后不见了好像不太好。

**Comment by sunbeams001** [comment]
虽然这功能不是我做的，但是
1 现在就加了5个啊，也不多
2 首页推荐的质量很少值得连续收藏
3 也不难找，新加的有 new 标志

建议和提这需求的老哥线上 Battle

**Comment by vincentkilua** [comment]
不是刷新了，而是加插，设置成3列/4列显示的话可以看到本来在后面的图片被顺延至更后的位置。

**Comment by CeuiLiSA** [comment]
现在的情况是A B C D E F作品按顺序排，收藏C，会自动推荐X Y Z，新的列表变成了A B C X Y Z D E F，这样可以吗？
