### ISSUE TITLE
【搜索结果过滤已收藏】功能打开后会应用至作者详情页

### ISSUE THREAD

**Issue by vincentkilua** [CeuiLiSA/Pixiv-Shaft#304]
版本：3.1.5(186)

首先感谢作者大大制作这app，这个【搜索结果过滤已收藏】功能很好用，有效减少了搜索时的重复加载，不过我发现将这功能打开后，连作者主页、作品页都会过滤掉已收藏的图片，我尝试收藏到精华，不过在精华列表里也是看不到已收藏的图片，所以感觉好像不太对劲，如果可以的话希望这个过滤功能只应用到搜索结果里，或者分离出【作者页面过滤已收藏】之类这样子。

❈如果两者不能分离的话，或者在显示图片列表的页面可以做到快速开关感觉也是可以的，现在要在最上层点进设置里开关，操作起来不是太方便

**Comment by CCRcmcpe** [comment]
@CeuiLiSA 在版本3.1.7(190)的动态页面也出现了类似的问题，复现步骤：1. 打开这个选项；2. 打开动态页面，收藏一个作品；3. 刷新，可以看到之前收藏的作品从列表消失了
