### ISSUE TITLE
希望搜索结果可以筛选全年龄向或R向

### ISSUE THREAD

**Issue by Nigel-NI** [CeuiLiSA/Pixiv-Shaft#311]
如图，官方网页版（手机、PC版）都可以实现图片中红框内框选的“年龄筛选”功能，官方客户端暂无，貌似其他第三方客户端也没有此功能，希望未来开发者能将此功能加入APP，非常感谢。
![Screenshot_20210405-232832](https://user-images.githubusercontent.com/23294384/113591807-f23f5700-9666-11eb-91b5-79a7fb00e0a7.jpg)

**Comment by sunbeams001** [comment]
App接口上并没有这个参数，可以手动加上 R-18 tag 搜索

**Comment by CeuiLiSA** [comment]
等有一天官方APP支持这样玩了，我们也可以！
