### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by demolg** [CeuiLiSA/Pixiv-Shaft#314]
清空应用数据后，我挂代理重新登录，正常打开登录网页界面，在最后图里的界面卡住了，后来在应用设置里关掉直连功能再重新登录才成功。这是什么问题？是不是应该在登录期间禁止“直连”行为？

**Comment by demolg** [comment]
![Screenshot_20210409-213305_Shaft](https://user-images.githubusercontent.com/26198098/114188599-e19b2380-997b-11eb-9f51-3b0d8cdce2d7.png)

**Comment by CeuiLiSA** [comment]
用的什么版本呢，有个老版本会有你这个问题

**Comment by demolg** [comment]
3.1.5 google play

**Comment by HinataKato** [comment]
我的 3.1.5 Google play版也有这个问题，需要手动去设置关闭直连
