### ISSUE TITLE
Ios

### ISSUE THREAD

**Issue by 1endlesspro** [CeuiLiSA/Pixiv-Shaft#316]
有iOS可以下载的版本吗，实在好用，突然换手机了但是还是想用这个软件

**Comment by duzhaokun123** [comment]
很明显该软件没有也不肯能直接有 iOS 版
一个可能的办法是在 iOS 设备上运行 Android 虚拟机之类的东西

**Comment by duzhaokun123** [comment]
可以使用 https://github.com/Notsfsssf/pixez-flutter
该软件使用 flutter 支持 iOS

**Comment by 1endlesspro** [comment]
谢谢



发自我的iPhone


------------------ Original ------------------
From: 杜兆琨 ***@***.***&gt;
Date: Wed,Apr 14,2021 7:34 PM
To: CeuiLiSA/Pixiv-Shaft ***@***.***&gt;
Cc: 1endlesspro ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [CeuiLiSA/Pixiv-Shaft] Ios (#316)





 
可以使用 https://github.com/Notsfsssf/pixez-flutter
 该软件使用 flutter 支持 iOS

**Comment by SodaWithoutSparkles** [comment]
开发者可能可以考虑像youtube++一样的处理方法，不知道难度不过可能可以一试

**Comment by CeuiLiSA** [comment]
哈哈哈开发者最近太忙了，忙着挣钱啊
