### ISSUE TITLE
图片有机会加载不出来

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#320]
1. 在预览的时候有机会会黑掉
2. 有部分图片会卡在0.0%，在多P插画出现概率更高
3. 有机会在插画详情出现"重新载入"字样，点击有时候能够载入成功，有机会不行

以上情况均在最近几天才开始出现。

traceroute 到 i.pixiv.cat, app-api.pixiv.net, www.pixiv.net 均没发现问题。

在墙外没需要开代理直连之类。

**Comment by sunbeams001** [comment]
看看
https://i.pximg.net/

**Comment by SodaWithoutSparkles** [comment]
`ping` 可以
`traceroute` 会卡在`158.205.95.54`

**Comment by sunbeams001** [comment]
因为图片就 host 在 i.pximg.net 这个域下，看起来是局部网络问题啊，你用官方App也是这个效果
可以过段时间再看看是否缓解，或挂上其他区域的代理

**Comment by SodaWithoutSparkles** [comment]
发现为什么`traceroute i.pximg.net` 不行了，因为需要TCP才行。`traceroute -T -4 i.pximg.net`就行了。

**Comment by SodaWithoutSparkles** [comment]
这几天暂时没事了，有问题再开吧

**Comment by SodaWithoutSparkles** [comment]
又来了，情况挺严重，很多是黑掉看不到了。 

`traceroute -T -4 i.pximg.net` 没问题

**Comment by SodaWithoutSparkles** [comment]
重启了路由器，暂时好像好点了，看看之后几天的表现吧。
