### ISSUE TITLE
希望能优化多P图的单图保存

### ISSUE THREAD

**Issue by 1235789gzy1** [CeuiLiSA/Pixiv-Shaft#321]
对于多P图有一些不想存的图，只能手动点进去一个一个下载，二级界面希望可以长按保存，而不需要点击图片详情才能保存，（至于右下角的下载点一下就全下载了，之后还需要去图库里一张一张删）

**Comment by sunbeams001** [comment]
你说的二级界面是竖直展示的那个吗，长按某一图片就下载？

**Comment by 1235789gzy1** [comment]
> 你说的二级界面是竖直展示的那个吗，长按某一图片就下载？

一张图，点进去是二级，再次点击全屏查看是三级
（我按照设置里那个二级加载原图来划分的）

**Comment by sunbeams001** [comment]
好像有点误会，设置里详情指的是你说的二级，二级详情指的是你说的三级
这功能感觉还行，可以做，不过可能做成不会默认开启，长按就下载还是有点激进

**Comment by 1235789gzy1** [comment]
> 好像有点误会，设置里详情指的是你说的二级，二级详情指的是你说的三级
> 这功能感觉还行，可以做，不过可能做成不会默认开启，长按就下载还是有点激进

顺带提一下，批量下载对于GIF来说有bug，并且在下载列表内下载的zip（GIF），下载完成之后回到原GIF页面去加载，会有两个进度条不断闪烁，并且等第二个进度条加载完毕（这个进度条并不会显示，我根据加载速度推的）会有很大概率闪退

**Comment by 1235789gzy1** [comment]
等会我录个屏

**Comment by 1235789gzy1** [comment]
这个是批量下载GIF的视频，视频中GIF下载后点击播放也不加载

**Comment by 1235789gzy1** [comment]
这是下载GIF退出，等待下载完毕之后的双重进度条，闪退视频里没有复现，但是GIF在第二个进度条加载完毕后的确从头开始了

https://user-images.githubusercontent.com/52618207/116250069-fe1ec480-a79f-11eb-8484-ae72e2a0905e.mp4

**Comment by sunbeams001** [comment]
嗯，这个问题我知道，已经做出了一定的修改，但是完全改好可能要等原作者自己来
推荐暂时逐张下载GIF，不容易崩
