### ISSUE TITLE
动态加载bug

### ISSUE THREAD

**Issue by 1235789gzy1** [CeuiLiSA/Pixiv-Shaft#322]
今天我刷图发现动态中，“全部”这一栏有问题，首先公开和私人依旧是分开的（虽然偶尔会蹦出来一个处于私人关注的图，但“全部”中几乎全是公开关注的作品）并且我在刷画师的作品时，切换回动态页时发现动态下一页新加载的一页也变成了画师的作品，并且刷到底后无法接着更新（因为画师作品刷到底之后再怎么拉也不会出现内容）

**Comment by 1235789gzy1** [comment]
手动浏览“私人”之后“全部”中才出现相关作品

**Comment by 1235789gzy1** [comment]
这是应用刚启动时，“全部”的截图
![Screenshot_20210502-214034](https://user-images.githubusercontent.com/52618207/116815333-9990aa80-ab8f-11eb-9f5c-3cc76717484c.jpg)
“公开”截图
![Screenshot_20210502-214102](https://user-images.githubusercontent.com/52618207/116815348-a8775d00-ab8f-11eb-9fcd-ae7ac1d75cbb.jpg)
“私人”截图
![Screenshot_20210502-214111](https://user-images.githubusercontent.com/52618207/116815314-7ebe3600-ab8f-11eb-927c-d51229fb0a8f.jpg)
这是最后全部点击手动加载之后的“全部”截图
![Screenshot_20210502-213923](https://user-images.githubusercontent.com/52618207/116815372-c6dd5880-ab8f-11eb-881c-f7eec0161a3b.jpg)
可以发现私人中第一张的白发猫猫漏了（一加长截图太短，没法提供足够的材料，但是问题是的确存在的0

**Comment by sunbeams001** [comment]
了解了，像是全部的搜索值初始化成公开了，然后切换选择后就正常了
