### ISSUE TITLE
考虑下下载功能优化？

### ISSUE THREAD

**Issue by 1235789gzy1** [CeuiLiSA/Pixiv-Shaft#323]
希望添加
下载管理（不想下的选择删除，暂停后点击恢复单图的下载）
断点续传（我20多M的图说重下就重下？太难了）

**Comment by UpKiry** [comment]
:+1

**Comment by sunbeams001** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/releases/tag/v3.2.6-beta

**Comment by sunbeams001** [comment]
试一下没问题我就关掉issue了

**Comment by 1235789gzy1** [comment]
再来一个：移动数据保存图片不下载
即 只添加到下载列表，不开始下载，等到连接至WLAN时再开始下载
