### ISSUE TITLE
[BUG] Search target contains invalid values

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#324]
```
{"search_target":["Search Target contains invalid value"]}
```

如何复制：

1. 复制两个标签
2. 在搜寻栏贴上第一个标签，加一个空格，贴上第二个标签 (猫 狗)
3. 选择右上角剪刀，搜寻条件设为500+收藏，匹配是"标题/简介 匹配"
4. 弹出上述错误讯息，但大多时候仍然能够检索结果

Ver 3.1.5 Google play
Android 10
MIUI Global 12.0.3 Stable

**Comment by sunbeams001** [comment]
修过了，还没发新版而已
