### ISSUE TITLE
URL无法转跳 pixiv.net/i

### ISSUE THREAD

**Issue by efsg** [CeuiLiSA/Pixiv-Shaft#326]

**Comment by sunbeams001** [comment]
来个完整地址看看

**Comment by efsg** [comment]
> 来个完整地址看看

https://www.pixiv.net/i/76667871

**Comment by sunbeams001** [comment]
暂时修了，这种带 i 的是怎么分享出来的？我假定的是最后都是插画ID可以吗

**Comment by efsg** [comment]
> 暂时修了，这种带 i 的是怎么分享出来的？我假定的是最后都是插画ID可以吗

好像是以前插画的链接，现在都是artworks了
