### ISSUE TITLE
[FRQ] 浏览记录显示收藏状态

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#327]
Feature ReQuest
如题

建议在浏览记录预览图右下新增，或者在删除上面加一个❤？

**Comment by sunbeams001** [comment]
我觉得不妥，这个收藏状态如果需要维护成实时，就很浪费性能；如果不做成实时，就不符合单一事件源原则
为什么要加这个功能呢？点进去收藏也不是很费事吧，如果想收藏一般看完就收藏了，按钮过于密集也容易误触
