### ISSUE TITLE
[BUG] 自适应高度的 ImageView 在设置 ScaleType 时无法达到效果（偶发）

### ISSUE THREAD

**Issue by sunbeams001** [CeuiLiSA/Pixiv-Shaft#329]
复现：
1 收藏这个插画 作品ID 89761291（高宽比超过 3.0，按照代码缩放类型应该为 center_crop）
2 打开我的插画收藏，可以看到正常展示（第一次一定正常的）
3 多次下拉刷新，发现该图显示不正常，不一定总是 center_crop，有时看起来是 center 的效果不会缩放
4 然而此时断点查看该ImageView，发现 scaleType 值确实是 center_crop

默默调试中……
这种难道是绘制流程出问题了吗？重复强制 requestLayout 也无效，或者是 Glide 流程导致的问题？
不是很懂，希望哪位比较懂的能指点下

**Comment by sunbeams001** [comment]
分析一下已知问题
设置 ratio 会导致 requestLayout
设置 scaleType 内部也可能会 requestLayout
而 requestLayout 不是同步完成的，在重复触发时可能导致问题？

目前的修改方式：
设置 scaleType 后暂时存储在 ImageView 变量中，在 onLayout 中重复设置 scaleType 触发可能的重新 layout
```
@Override
    protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        if(tmpScaleType != null){
            setScaleType(tmpScaleType);
        }
        super.onLayout(changed, left, top, right, bottom);
    }
```
效果：修复了center_crop失效的问题，但是图像有几率会糊掉，感觉改的方式不太对

**Comment by duzhaokun123** [comment]
`Glide`似乎会根据`ImageView`的缩放方式和大小缩放图像以节约内存
避免使用`Gilde.with(context).load(url).into(imageView)`而是`Glide.with(context).asBitmap().load(url).submit().get()`获取`Bitmap`手动设置可能能解决这个问题

**Comment by sunbeams001** [comment]
@duzhaokun123 这个思路可以，把大小 override 成图片自身宽高之后就不糊了
