### ISSUE TITLE
遮罩标签使用regex或wildcard

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#330]
对于包含某个关键词的作品进行屏蔽，例如："腐" 那样的话就要屏蔽很多标签，有时候会藏在收藏数标签里面(500 users 入__)，逐个逐个加的话会很多，使用regex/wildcard可能更加有效，效率更高。

如果不能做到的话就算了吧，感谢开发者

**Comment by sunbeams001** [comment]
个人认为这事不很靠谱
1. 大多数用户是不懂什么正则的，复杂规则写对写错也肯定不会调试，基本就写上个词就完了
2. 随之带来的tag误杀就多了，你加了一个腐，显然腐川冬子就没了
3. 如果给屏蔽方式加上不同种类区分？全tag匹配屏蔽，正则匹配屏蔽什么的。可以做，但是现在设计上没有这个维度，要改起来比较麻烦，你如果有时间可以PR
4. 建议使用多个tag屏蔽 腐向 BL ホモ 什么的多来几个就差不多了

**Comment by SodaWithoutSparkles** [comment]
现在想起来或许能加一个功能，如果用`/`开头和用`/g`结尾就以regex处理，没有的话就普通模式。例如

```
/([A-Z])\w+/g
```

而且，可不可以考虑屏蔽带有收藏数标签的tag时，把其他相应的也屏蔽掉，例如屏蔽这个
```
アズールレーン1000users入り
```
的时候，把这些类似的也屏蔽掉
```
アズールレーン500users入り
アズールレーン5000users入り
アズールレーン10000users入り
```
等等

**Comment by sunbeams001** [comment]
现在是全匹配，添加屏蔽tag时候增加选项，包含匹配，只要任何tag里包含匹配文字（不需要完全一致）就过滤？感觉这个是你需要的

**Comment by SodaWithoutSparkles** [comment]
感觉就是了，这个不就是wildcard match吗？
