### ISSUE TITLE
对于长宽比3.2左右的作品缩图模糊

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#334]
其他缩图没问题，暂时只是那一张看见

对于长宽比超大，如为1785x5715的图片，缩图极其模糊，举例插画ID84766863（以下称作A）

首页看见插画A的话会比其他的插画模糊，上下裁剪。

首页点进去A预览没事，收藏A，返回首页，收藏另外的作品(B)，刷新推荐。之后A看起来放大了，然后更加模糊。

在收藏页面看起来也模糊，和首页看见的差不多，不过上下没有裁剪。

在画家的主页找到A，和收藏页面看起来几乎一样，不肯定有无区别。

在作品详情那里，无论从那里进去，清晰度一样。

作品详情点击图片放大，双击之后左右贴屏幕边界，但是放大动画有肉眼可见的卡顿。

下载原图之后最清晰，但是缩图没变。

P.S. 感觉所有图片也是有一个上限，最多放大百分之多少，但是对超长图会非常不友善，要放大细节很难看清。建议可以提高那个上限。

感觉和#329有关

**Comment by sunbeams001** [comment]
329 改过了，等下次发布看效果
