### ISSUE TITLE
对于超大图的以图搜图

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#335]
从某个途径获得了一张1.5GB的图片。作死想去以图搜源看看会发生什么。毫无意外地崩掉了。看报错日志写的是类似out of memory。可能需要加一个判定，不要看见什么就把它写进内存？不过搜图网站有限制，可能可以用那个来定

**Comment by sunbeams001** [comment]
加上了
