### ISSUE TITLE
精华清单预览图一片黑

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#336]
首页 > 左上更多 > 精华列 > 精华清单

预览图一片黑，点进去一片黑的预览图，可以预览不同系列(?)的插画，但是例如显示这个的页面，预览图是一片黑的。不知道是否正常。

[一片黑的预览图]

2020年6月1日 22:33 添加 [tab] 漫画系列作品 🗑️

**Comment by sunbeams001** [comment]
不太清楚这东西的存在意义，把相关作品单独保存起来？
反正你每次添加精华时候等到完全加载出来再加就不会显示不出预览了

**Comment by sunbeams001** [comment]
漫画系列是有点问题，和其他内部数据格式不同所以无法显示预览，已修改
