### ISSUE TITLE
打开外部链接跳转毫无视觉反馈

### ISSUE THREAD

**Issue by demolg** [CeuiLiSA/Pixiv-Shaft#338]
目前打开外部pixiv链接需要几秒钟等shaft加载完图片才会进入shaft应用界面，这几秒钟内没有任何提示，只能干等，希望添加“加载中”的Toast提示，或者点击链接直接打开应用显示加载进度（如图）。![](https://i.loli.net/2021/06/12/9DHQjJRYndvUeoh.png)

**Comment by sunbeams001** [comment]
修了
