### ISSUE TITLE
当搜寻结果太少的时候，禁止滑动

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#339]
例如搜寻结果不会排出荧幕外导致需要滑动的时候，禁止滑动。

这个应该能够解决一个bug，就是在某些特殊条件下，搜寻结果为空，而搜寻栏隐藏的时候，下拉不能把搜寻栏和快速筛选(剪刀图标)拉下来。

**Comment by sunbeams001** [comment]
我这完全没这个问题，来个截图或者录屏看看？

**Comment by SodaWithoutSparkles** [comment]
![Screenshot_2021-06-20-00-49-10-397_ceui.lisa.pixiv.jpg](https://user-images.githubusercontent.com/64138578/122956711-d3be4180-d3b3-11eb-8883-cde2b522878f.jpg)

**Comment by sunbeams001** [comment]
可以暂时滑动顶部的 tab 部分完成下拉
这问题比较复杂，虽然能按你这么改但是还要研究下

**Comment by sunbeams001** [comment]
果然不能乱改，之前的修改方式会造成搜索数据过多时滑动卡顿，还要再研究下
