### ISSUE TITLE
刘海屏没有完全适配

### ISSUE THREAD

**Issue by Shirakami-Sora** [CeuiLiSA/Pixiv-Shaft#34]
![ScreenShot_1](https://user-images.githubusercontent.com/56698742/67042699-ff0e7900-f15a-11e9-811a-ac57266517b1.png)
刘海屏在图片详情界面时图片标题会跟状态栏重叠导致部分标题被遮挡，刘海区域已经用红色标记出来

**Comment by CeuiLiSA** [comment]
手机型号说下呗，给个面子
