### ISSUE TITLE
[Feature Request] 增加以上皆非的template

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#343]
## What feature should be added? / 需要加上什么功能
Explain why this should be added

因為不是所有issue都是bug report 和feature request

## Is this feature supported by the official pixiv app? / 官方App是否支持
Yes/No/NA

NA

## Is this feature supported by any other third-party pixiv app? / 第三方App是否支持
Yes/No and which one(if yes)

NA

## Any other information can be help? / 其它信息

NA

**Comment by sunbeams001** [comment]
比如？
我觉得大部分可以归类为广义的 bug 和 feature
而且你可以全删掉不想填的部分，这个没有做限制，只是建议格式

**Comment by SodaWithoutSparkles** [comment]
例如我刚发上去的对于无法下载github版的解决方法。因为找不到地方发才发issue。而且，例如请求增加FAQ，对readme做改进，更新版权等杂项，是否应该分类作为feature request 呢？

**Comment by duzhaokun123** [comment]
@SodaWithoutSparkles 其实你完全可以不用模板

**Comment by SodaWithoutSparkles** [comment]
> @SodaWithoutSparkles 其实你完全可以不用模板

我知道可以不用，我另外一个issue就是这样开的

> 好像没有不要模板的选项，那可能真的需要"以上皆非"了
> 
> 不然随便选一个模板再删完感觉怪怪的

同意，就是因为这样才有这个issue的
