### ISSUE TITLE
[Feature Request] 导出汇入本地资料

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#346]
## 需要加上什么功能
导出本地资料，如本地浏览记录，本地遮罩，设定等。重新安装之后会丢失所有本地数据（试过了）。

## 官方App是否支持
官方app有云端储存，而且也没有本地浏览记录

## 第三方App是否支持
没有数据，但是有其他非pixiv第三方可以做到

## 其它信息
可能可以用database的方式是导出？也可以用tar.gz压缩

**Comment by sunbeams001** [comment]
先记录一下有哪些项目，可能做但不会很快
下载记录？
浏览记录？
搜索记录？
屏蔽记录 +
设置 +

**Comment by SodaWithoutSparkles** [comment]
我认为最好可以选择导入什么，还有现有的资料怎么处理（最简单的方法是覆盖之前的）。

我认为有以下的部分需要备份：

1. 浏览记录（保存作品ID，时间/UNIX时间）
2. 屏蔽标签，屏蔽作品，等本地屏蔽（ID和标签）
3. 搜寻记录（明文）
4. 设置（例如界面颜色，筛选设置等）（或许可以用二进位保存设定，之后用换成16进位？）

之后使用.tar.gz压缩。

**Comment by sunbeams001** [comment]
讲真浏览记录有必要加吗，因为这堆真的挺大的，会有人经常看这个？

**Comment by sunbeams001** [comment]
浏览记录备份已增加为可选流程
