### ISSUE TITLE
可以直连登录吗？

### ISSUE THREAD

**Issue by Dr-WeiAL** [CeuiLiSA/Pixiv-Shaft#347]
以前有梯子的时候登录了，里面在直连的时候也能正常加载。前两天看到更新了就更新到了3.1.7_2，进去后无法加载任何图片，打算降到本来的版本，但是卸载重装后账户信息丢失，软件也无法使用直连登录，现在没梯子用了(悲)，是由于什么原因禁用了直连登录呢？

**Comment by sunbeams001** [comment]
3.1.7_3 可以用

**Comment by Dr-WeiAL** [comment]
> 3.1.7_3 可以用

电脑可以登上pixiv，有什么办法把用户信息导进去吗，手机上和模拟器上都连不上

**Comment by sunbeams001** [comment]
> 电脑可以登上pixiv，有什么办法把用户信息导进去吗，手机上和模拟器上都连不上
有办法但是过于复杂，手机登录过程挂梯就可以了

**Comment by Dr-WeiAL** [comment]
> > 电脑可以登上pixiv，有什么办法把用户信息导进去吗，手机上和模拟器上都连不上
> 
> 有办法但是过于复杂，手机登录过程挂梯就可以了

什么方法可以说一下吗，没梯子用了，不然就不会来发了(

**Comment by sunbeams001** [comment]
肯定比你找梯子麻烦
免费VPN好多的，自己随便搞一个
我记得QQ群里也有分享

**Comment by SodaWithoutSparkles** [comment]
再不行租一个，或者找一个墙外的朋友买一个两百多的树莓派自己搭建pivpn，理论上很稳定，而且网速绝对比随便一个免费提子都快，甚至比付费的还快。而且被封的机会很少，因为只有你一个人用
