### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by 932749734** [CeuiLiSA/Pixiv-Shaft#352]
安卓11我用的手势导航，看详情图是左右翻动的立方形式，这样的话我的手势的左边的返回键就被占用了看图就退不出来了

**Comment by sunbeams001** [comment]
系统级手势/第三方应用？虚拟返回键被隐藏？手势冲突？
完全不懂具体啥问题，希望来个截图或录屏

最新版Shaft是有自带了滑动返回了
一般侧面的滑动条不是能自定义宽度/触发位置的吗，我好几年前用的导航辅助软件都有这种功能

**Comment by SodaWithoutSparkles** [comment]
他说的应该是详情图点开之后，在边缘滑动(系统级返回)的手势和滑动图片的手势冲突了，想返回的时候只能滑动图片返回不了

解决方法：检测范围加一个mask，左右大概10到20px的位置不要滑动图片

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 这是不是有点本末倒置了？系统级手势导航原理是全局检测触摸区域，不在自身响应区的转发给应用
现在你让应用来适配系统，那是不是一些没用全局手势导航的用户会来问为啥我从边缘无法触发翻页？

**Comment by sunbeams001** [comment]
Android 11 官方系统的模拟器我试了下，全局手势导航可以正常使用，完全没问题，有冲突八成是厂商定制系统的问题

**Comment by SodaWithoutSparkles** [comment]
@932749734 那么你就试试找一个地方避免手势导航冲突吧，应该在荧幕偏下部分可以。

顺带一提你是什么手机？用的什么UI？

**Comment by 932749734** [comment]
@SodaWithoutSparkles 我用的摩托罗拉edges，myui，是一个类安卓原生的系统。试了另一种屏幕下方三建导航，还是要先呼出手势导航，然后才可以反回。三级的详情页面下方的三建也是一样隐藏的，上滑呼出导航的时候容易点到下载图片

**Comment by SodaWithoutSparkles** [comment]
@932749734 有时候手势导航会出bug的，应该是那边的程序员忘了处理edge case吧。

可能要找work around了，你看看有没有一个位置能触发手势导航的。

对了，更新到最新版看看还有没有这个问题？有时候可以解决

**Comment by sunbeams001** [comment]
设置-界面-插画二级详情显示导航栏

**Comment by 932749734** [comment]
旧版没有这个设置，我更新到新版试试

**Comment by SodaWithoutSparkles** [comment]
问题处理了没？
