### ISSUE TITLE
[Bug] 部分原图MD5与官网不一致

### ISSUE THREAD

**Issue by nuthx** [CeuiLiSA/Pixiv-Shaft#355]
注意到几张图与Pixiv官网下载的尺寸有差异，对比了其MD5，确实有所差异，目前且仅部分图片会出现此情况

举例ID：90894219, 90880816

有差异：
> 文件: E:\Pictures\90894219_p0.jpg
大小: 7124964 字节
修改时间: 2021年6月30日, 0:05:43
MD5: C0262CE1002D2960C1F3539BADE70CFB
SHA1: 9D67642E8AD10F472D69EC25C79D0F5419C16BE2
CRC32: 72B77A5B
> 
> 文件: E:\Desktop\90894219_p0.jpg
大小: 7126609 字节
修改时间: 2021年6月30日, 1:02:28
MD5: FBA503C018719BF08611EC6AE16D64EF
SHA1: 7A670038D454BEBFD05AA2B9B869573861780FE3
CRC32: 4DB367D6

> 文件: E:\Pictures\90880816_p0.jpg
大小: 1755797 字节
修改时间: 2021年6月29日, 23:29:37
MD5: 5D27F03A49055C5D9F5D7D393F818874
SHA1: 1C7551857C767E83B360ED3ED8F0D1AACE528D2E
CRC32: A7112C1F
> 
> 文件: E:\Desktop\90880816_p0.jpg
大小: 1735681 字节
修改时间: 2021年6月30日, 1:26:44
MD5: 413131984975767A3FC9C677483A1697
SHA1: 8A1F100E2EAFAAEC535909AFB630DE954A15DF54
CRC32: 47B5D7FD

无差异：
> 文件: E:\Pictures\90880789_p0.png
大小: 1909327 字节
修改时间: 2021年6月29日, 23:32:01
MD5: 1F9D1A829766458F889324E47A2FD037
SHA1: 847824A0870DF3F7257097054077A7CCE80FC3BE
CRC32: 68A67D92
> 
> 文件: E:\Desktop\90880789_p0.png
大小: 1909327 字节
修改时间: 2021年6月30日, 1:26:44
MD5: 1F9D1A829766458F889324E47A2FD037
SHA1: 847824A0870DF3F7257097054077A7CCE80FC3BE
CRC32: 68A67D92

**Comment by sunbeams001** [comment]
确实有这个问题，搞一下

**Comment by sunbeams001** [comment]
有结论了，因为替换了地址，实际下载地址从
https://i.pximg.net/img-original/xxx
修改为
http://210.140.92.145/img-original/xxx
类似这样，ip是从一组ip随机挑的
从http+ip这种地址下来的图就是这样的，哈希会不同，这些ip应该也是pixiv图片服务器的ip？不是很懂从哪里找的
底层为啥是这个流程我也不知道，应该是和直连有关
代理模式下下载图片改成不替换地址是否可行？这个要研究一下

**Comment by SodaWithoutSparkles** [comment]
试试导入到软件里面看看有啥不同的，理论上应该是同一张图来着？
