### ISSUE TITLE
滑动返回鬼畜

### ISSUE THREAD

**Issue by efsg** [CeuiLiSA/Pixiv-Shaft#356]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.1.7

### Android system version

11

### Device model

Apollo

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

边缘缓慢滑动返回
![Video_20210705_104004_827](https://user-images.githubusercontent.com/39408740/124410849-dd658300-dd7d-11eb-8b2f-eb1d34d264ed.gif)

### Expected behavior / 期望行为

RT

### Actual behavior / 实际行为

RT

**Comment by sunbeams001** [comment]
这个不好办了，看起来是这个三方库和你手机系统有些不兼容，修复时间很难保证
建议先关掉这个功能

**Comment by efsg** [comment]
> 这个不好办了，看起来是这个三方库和你手机系统有些不兼容，修复时间很难保证
> 建议先关掉这个功能

应该不是系统问题，小米安卓10和11固件还有类原生都能复现这个bug

**Comment by sunbeams001** [comment]
盲猜一个，硬件加速相关？

**Comment by sunbeams001** [comment]
[app-debug.zip](https://github.com/CeuiLiSA/Pixiv-Shaft/files/6766827/app-debug.zip)
搞了一个开启硬件加速版本的，如果你愿意可以试试，手里没实机不太好确定是不是这个问题

**Comment by efsg** [comment]
> [app-debug.zip](https://github.com/CeuiLiSA/Pixiv-Shaft/files/6766827/app-debug.zip)
> 搞了一个开启硬件加速版本的，如果你愿意可以试试，手里没实机不太好确定是不是这个问题

安卓10没问题了，但搜索页面来回切换后台之后滑动就会卡顿

**Comment by sunbeams001** [comment]
> 安卓10没问题了，但搜索页面来回切换后台之后滑动就会卡顿

那就行了，滑动卡顿是另外一个bug，和这里无关
