### ISSUE TITLE
申请适配以下两个链接形式

### ISSUE THREAD

**Issue by Khvar** [CeuiLiSA/Pixiv-Shaft#359]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

申请关联以下两个链接的形式
https://pixiv.net/i/图片id
https://pixiv.net/u/作者id

这应该是历史遗留问题？

### 

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

### Any other information can be help? / 其它信息

目前的话，这个链接是可以识别到的
但是并不会跳转到对应的图片/作者，而是停留在主页
官方app也不能识别该链接

**Comment by sunbeams001** [comment]
i 有了，u下次加上

**Comment by Khvar** [comment]
> i 有了，u下次加上
i是3.1.5之后的版本加上的吗？
我还在用playstore的3.1.5（

**Comment by sunbeams001** [comment]
3.1.7
小说还有个n

**Comment by SodaWithoutSparkles** [comment]
@Khvar 建议更新3.1.7，github版本会更新，什么bug和漏洞应该都在这里会修的更快。而且看起来google play版本最近应该不会更新了，作者在忙，github这边好搞定，但是google play手续多。

无法安装github版的话FAQ有
