### ISSUE TITLE
ceui.lisa.http.WorkThread 是啥子咧？

### ISSUE THREAD

**Issue by mashirozx** [CeuiLiSA/Pixiv-Shaft#36]
编译时报错 cannot find symbol class WorkThread，看了一下 http 目录下没有 WorkThread 文件，注释掉编译出来好像也没什么问题。。

<https://github.com/CeuiLiSA/Pixiv-Shaft/search?q=ceui.lisa.http.WorkThread&unscoped_q=ceui.lisa.http.WorkThread>

**Comment by CeuiLiSA** [comment]
我的我的，这东西没啥卵用，现在我把它去掉了，可以编译了
