### ISSUE TITLE
Template去哪了？

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#360]
如题![Screenshot_2021-07-12-23-09-21-556_com.github.android.jpg](https://user-images.githubusercontent.com/64138578/125311753-3c229200-e366-11eb-8f91-300890be75b3.jpg)

**Comment by sunbeams001** [comment]
这次模板太新，手机版没适配

**Comment by SodaWithoutSparkles** [comment]
好，那么我去github app那边反馈
