### ISSUE TITLE
[bug]  在加载时立刻划下会导致无法加载

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#361]
在加载页面，例如作者主页的时候，立刻划下会导致无法加载，一篇空白。弹窗显示"没有更多数据"

1. 点击任意插画
2. 进入该作者主页
3. 进入后立刻下滑（可能要多次下滑，直到页面底部出现"loading"字样）（像浏览更多插画一样）
4. 无法加载，弹窗显示"没有更多数据"

**Comment by sunbeams001** [comment]
你这用法太极限了，就不能正常用吗
这种bug是没有修的必要的，找这个刷新的框架作者去吧

**Comment by SodaWithoutSparkles** [comment]
好的👌，还以为是app的问题，原来是框架问题。
