### ISSUE TITLE
[bug] 部分语言翻译不全

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#362]
语言选择：繁体中文

- [ ] "个人中心" → "個人中心"
- [ ] "没有更多数据啦" → "沒有更多數據啦"

**Comment by sunbeams001** [comment]
不顺便来个准确翻译？

**Comment by LittleYe233** [comment]
补充：下载界面右上角菜单，“suspend”首字母没有大写。
