### ISSUE TITLE
对于曾下载过的图片的下载机制

### ISSUE THREAD

**Issue by LittleYe233** [CeuiLiSA/Pixiv-Shaft#363]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

操作：
1. 下载系列作品其中一部分；
2. 让图片下载失败（切断网络连接）；
3. 重新进入详情页，并点击需要下载的图片查看大图。

第3步中，详情页的下载按钮会一次下载全部图片，而不考虑是否下载过，但至少可以下载；而点击查看大图时不论是否下载成功，下方的下载按钮都不能显示，无法逐张下载。

因此，希望改进：
1. 对于下载过且__文件完整__的图片，可以选择跳过不覆写；
2. 对于曾下载过但未成功的图片，添加下载按钮。

### 

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

不知道，没有用过其他的。

**Comment by sunbeams001** [comment]
你说的情况，2和3中间恢复网络吗？
第一个问题，下载完的文件不重下，这个会有问题，万一有人就是想重下呢？失去了一次点击重下全部的体验。你这个需求的原始场景是什么？补齐组图中未下载的图片？那为啥开始时候不直接全部下载？一般人下图是要一张张看过去的吧，在大图页决定要不要下单张
第二个问题，没下完的单张图片不显示单独按钮，我这没遇到，无论网络开关，你确认是317吗

**Comment by LittleYe233** [comment]
> 你说的情况，2和3中间恢复网络吗？
> 第一个问题，下载完的文件不重下，这个会有问题，万一有人就是想重下呢？失去了一次点击重下全部的体验。你这个需求的原始场景是什么？补齐组图中未下载的图片？那为啥开始时候不直接全部下载？一般人下图是要一张张看过去的吧，在大图页决定要不要下单张
> 第二个问题，没下完的单张图片不显示单独按钮，我这没遇到，无论网络开关，你确认是317吗

1. 第2步之后需要恢复网络连接，不然的话进不去详情页；另外这一步的目的是中断下载，断网只是其中一种手段，重启软件再进入效果相同；此外只有在文件下载到一半的时候中断才有这种效果；
2. 我确实没有考虑到有人想要重下的需求，我认为可以设置一个开关允许跳过重复文件；我的需求的原始场景是：一个系列我只想要下载一部分图片，而在下载过程中由于网络原因（例如没有梯子）某张图片屡次未能下载完整，这张图片我就没办法单独下载，只能在详情页全部重下；
3. 我确定是有这样的情况，复现条件在第1条做了一些补充；我的版本也的确是3.1.7_3（按照GitHub releases里的版本号），软件内显示的是3.1.7(190)。

**Comment by sunbeams001** [comment]
1. 知道问题了，那我始终显示下载按钮不就好了？当初是认为下完了不显示按钮看起来清爽点才这么改的，而且问题是仅从作品信息看，能看出指定位置有没有文件，但是看出这文件完整不完整就不是很简单了，需要结合其他数据，就比较影响效率了
2. 下载记录始终存在，你可以去下载管理里重试未完成任务

**Comment by LittleYe233** [comment]
1. 理解了，关于检测文件完整性我一开始的想法是用p站api获取hash进行比对，的确网络延迟是一个负担；
2. 这个有一个问题是没法选定部分项目，只能下载全部（标题栏有个“start”按钮）；
3. 这个已经弄好了，没有问题。

**Comment by sunbeams001** [comment]
1. 倒是不用额外进行网络请求，官方也没这个接口获取hash信息，能想到的最简单方法是读取文件最后部分字节看是否是正常的文件结束符，或者对照下载记录看是否已完成，评估了下都不是太完美
2. 现在下载框架也不是我写的，单任务线程逐个下载，不过你都加到下载队列了肯定是要都下的啊，之后重构改不改再说吧

**Comment by LittleYe233** [comment]
好的，谢谢！
