### ISSUE TITLE
作者页面显示关注状态（私人or公开）

### ISSUE THREAD

**Issue by 1235789gzy1** [CeuiLiSA/Pixiv-Shaft#367]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

希望作者信息页面可以显示当前作者是公开还是私人关注
目前作者页面最上面的返回和关注按钮之间我觉得可以塞进去这条信息文本
因为万恶的资本，我都是用私人关注当分类，可惜并不知道这个作者我有没有设为私人关注，所以只能每次取关再长按

由此提个题外话，希望取消关注长按也能实现公开转私人关注的功能

### 

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by sunbeams001** [comment]
好哦，可以搞

**Comment by sunbeams001** [comment]
有点想多了，数据里没有具体的状态公开还是私人？需要再看看
长按切换同理，不能区分出之前是公开关注还是私人关注，只能统一私人关注

**Comment by 1235789gzy1** [comment]
长按私人就够了，切换不是必要的

**Comment by 1235789gzy1** [comment]
![Screenshot_20210718-204117](https://user-images.githubusercontent.com/52618207/126067495-3b108801-010a-4ddd-8683-d57199926c39.jpg)
网页在关注编辑里可以看到是不是私人

**Comment by sunbeams001** [comment]
知道了，是这里点击之后发起了新请求，普通用户数据里反正没这东西了

**Comment by sunbeams001** [comment]
仅限用户主页加了额外请求，如果是私人关注状态会修改按钮边框为虚线
插画页也这么做就太浪费了，这个不考虑
