### ISSUE TITLE
[Feature Request] - Release增加hash

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#370]
对release增加sha256的hash，确保下载的是真正的软件

**Comment by sunbeams001** [comment]
下载地址是https啊，这个会经常出错吗？

**Comment by SodaWithoutSparkles** [comment]
不一定，但是我们也完全没有办法肯定没错，只能相信下载的是真版本。

这个应该挺简单了，一个github action或许能处理了。

**Comment by SodaWithoutSparkles** [comment]
Version 3.2.1

```
MD5: 590047e0e3ff3416c22151dd849d594c
SHA-1: 30132635b9dda4b3dd7df3404940c6ba06908e22
SHA-256: 9804ba81259d52201ce163a37be0cdb506ed7abd4e77a58e655b2ba3b9a8158d
Vhash: d1efc3f6ad471e8ca68b29b348736f34
```
[No security vendors flagged this file as malicious](https://www.virustotal.com/gui/file/9804ba81259d52201ce163a37be0cdb506ed7abd4e77a58e655b2ba3b9a8158d/summary)

**Comment by sunbeams001** [comment]
我目前就加了一个 SHA1，感觉这个足够了且更常用，太多没必要。你要是有新的要求可以自己修改workflow配置文件

**Comment by SodaWithoutSparkles** [comment]
@sunbeams001 可是我找不到你说的SHA-1 hash？

**Comment by sunbeams001** [comment]
加上之后还没发布过呢

**Comment by SodaWithoutSparkles** [comment]
好像也是，那么我等下一个release吧

**Comment by SodaWithoutSparkles** [comment]
https://github.com/SodaWithoutSparkles/Pixiv-Shaft/blob/master/.github/workflows/gradle.yml

@sunbeams001 帮我看看有没有问题，我顺便把更新template写好了。

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 差不多，body你看action的文档写就行了，另外改下这个吧
SHA-1
SHA-256
这个说法比较官方

**Comment by SodaWithoutSparkles** [comment]
> 另外改下这个吧
> SHA-1
> SHA-256
> 这个说法比较官方

好，那么我把这个改了，等那边 #383 那边没办法build的问题处理了就一起PR

**Comment by SodaWithoutSparkles** [comment]
Version 3.2.2

```
MD5: 7fdf3f8855a662c4b95e9f0cea88ca7d
SHA-1: 3379e8ca4834f4453466c30bb56c0b796223e2cd
SHA-256: e5f23382ef58713b4ac76ac8be12a90f74a4e14f4b1f405c45e81c9a31f8b015
Vhash: e784cf6056ed6384ed17c143b99113b7
```

[No security vendors flagged this file as malicious](https://www.virustotal.com/gui/file/e5f23382ef58713b4ac76ac8be12a90f74a4e14f4b1f405c45e81c9a31f8b015)

**Comment by sunbeams001** [comment]
有个action可以研究一下，自动增加验证信息
https://github.com/marketplace/actions/virustotal-github-action

**Comment by SodaWithoutSparkles** [comment]
本来就是想做这个的，但是不知道内地的网络情况会不会允许virustotal

**Comment by SodaWithoutSparkles** [comment]
同时能不能试试把version tag加进release的档案名称里面？例如把`app-release.apk`改成
```
PixShaft_v3.2.2.apk
```
之类的

**Comment by SodaWithoutSparkles** [comment]
@sunbeams001 要不要把这个issue 重开？

**Comment by SodaWithoutSparkles** [comment]
> 有个action可以研究一下，自动增加验证信息
> https://github.com/marketplace/actions/virustotal-github-action


好像需要secrets，协作者有权限加吗？

**Comment by sunbeams001** [comment]
加不了，不过你愿意的话可以写死

**Comment by SodaWithoutSparkles** [comment]
这样看的话写死好像也行，反正apk签名也公开了，也不差一个api key了，不过别用自己电邮注册，随便找个十分钟电邮注册就行

**Comment by SodaWithoutSparkles** [comment]
@sunbeams001 十分钟电邮好像不行，这个项目有没有电邮地址之类的？没有的话加一个？

**Comment by sunbeams001** [comment]
没
而且你写错了，这东西的release相关配置是要求release事件触发workflow的，要是整合进流程里要用output获取检查结果

**Comment by sunbeams001** [comment]
那还是算了吧，我是觉得没必要加这个远程验证，反正是开源的
