### ISSUE TITLE
F-droid?

### ISSUE THREAD

**Issue by OliverLew** [CeuiLiSA/Pixiv-Shaft#371]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

如果符合要求的话，能否发布在f-droid官方仓库或者izzyondroid仓库？

### 

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by SodaWithoutSparkles** [comment]
据说要超过40GB的本地空间
┐(´-｀)┌

**Comment by OliverLew** [comment]
啊，是clone仓库的大小吗，我没了解过确实不清楚。
好象很复杂的样子，不好办就算了。
不过，所有fdroid的软件开发者都这样做的吗，不会劝退大部分人？不知道有没有更轻松的办法。。。

**Comment by SodaWithoutSparkles** [comment]
@sunbeams001 有啥想法？

**Comment by sunbeams001** [comment]
没做过这个，要是能一键导入/配置不麻烦的可以做
估计不行啊，这个如果做肯定是要项目拥有者来操作的，合作者没这权限

**Comment by OliverLew** [comment]
谢谢回复。
其实，fdroid对许可证并不限制在这两个之中，我看来他们只是举了两个例子。
izzyondroid这种第三方库可能在条件上更宽容一些，许多有anti feature的软件他们也接受。
不过这事看起来确实很复杂，我就先关掉这个issue了，如果有人觉得可行，再重新打开。

**Comment by linsui** [comment]
在 F-Droid 发布需要代码是开源的，但是本项目有一个非商业用途限制，所以**不是开源**的。如果想要限制商业用途可以切换到更严格的许可证，比如 GPL。构建并不需要你运行自己的构建服务器，apk 由 F-Droid 构建并发布。

**Comment by proletarius101** [comment]
> 协议不允许，这个市场要求是 GPL 或 Apache，现在是 MIT 的

Not true. You may use ANY licenses listed https://www.gnu.org/licenses/license-list.html, including the MIT license (called X11 License there).


> 据说要超过100GB的本地空间

It's only a requirement if you want to setup the same VM environment. Usually, you'll prefer the lightweight container environment for locally testing building your apps: https://gitlab.com/fdroid/wiki/-/wikis/Setting-up-app-submission-development-environment-locally.

> 很多方面不符合政策

I only see the license issue.

---

You may use GNU **Affero** General Public License v3.0. According to https://choosealicense.com/appendix/, it

- requires any derivative software be licensed under it
- treats network use as redistribution
- requires source code availability when the licensed software is distributed

So it effectively forbids commercial uses, unless they also open source their versions, which might not be against the will of the original user.

**Comment by SodaWithoutSparkles** [comment]
> > 协议不允许，这个市场要求是 GPL 或 Apache，现在是 MIT 的。
>
> 不是这样的。你可以使用 https://www.gnu.org/licenses/license-list.html 中列出的任何许可证，包括 MIT 许可证（在那里称为 X11 许可证）。
>
>
> > 据说要超过100GB的本地空间
>
> 这只是在你想设置相同的虚拟机环境时的一个要求。通常，你会喜欢轻量级的容器环境（~3GB），用于本地测试构建你的应用程序：https://gitlab.com/fdroid/wiki/-/wikis/Setting-up-app-submission-development-environment-locally。
>
> > 很多方面不符合政策
>
> 我只看到许可证问题。
>
> ---
>
> 你可以使用GNU **Affero** General Public License v3.0。根据https://choosealicense.com/appendix/，它
>
> - 要求任何衍生软件都要在其下获得许可
> - 将网络使用视为再分发
> - 要求在分发许可软件时提供源代码
>
> 所以它有效地禁止了商业使用，除非他们也开放其版本的源代码，这可能并不违背原始用户的意愿。
>
>

翻译了一下。
