### ISSUE TITLE
[Feature Request] - 更佳化搜寻筛选标准

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#373]
对于搜寻的时候，能不能选择搜寻筛选条件？例如 "收藏数达到500或以上" 而不是 "收藏数达到500"。据说这个筛选是使用标签的，那么能不能筛选标签的时候包含多个？

可能需要提交多个request之后合并？或者先下载之后才筛选？

**Comment by sunbeams001** [comment]
不能啊之前你问过了老哥
#205
