### ISSUE TITLE
[Feature request] 搜寻界面 & 翻译

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#380]
搜寻画师能不能合并到"ID搜画师"那里？这样占位太多了。某些情况，例如英语翻译下，会因为栏宽太小而自动跳行，有些情况更加显示不全，剩下 `...` 符号。

同时想问下，"搜索" 和 "关键词搜索" 有什么区别？

![IMG_20210805_040126.jpg](https://user-images.githubusercontent.com/64138578/128247616-354dd623-5de0-46e5-bfa7-d44e95a2a6a8.jpg)

**Comment by sunbeams001** [comment]
你先看看pr里的说明啊 #374 
详情请咨询这部分的作者
@takuron

**Comment by takuron** [comment]
“搜索”可以直接输入插画id，链接等进行自动跳转，在设计这个功能时还没有根据剪切板内容自动判断内容类型的功能。同理搜索页面顶部的搜索也被换成了有类似功能的搜索栏。
搜索画师翻译后过长的问题可以讨论一下，我倾向是优化翻译文本（因为四个真不算特别多），或者考虑直接把热度合并进搜索选项里面，这确实是一个问题。

**Comment by sunbeams001** [comment]
单纯放不开不如改下 tabMode 放开成滚动模式？

**Comment by SodaWithoutSparkles** [comment]
@sunbeams001 我怎么没想到呢，开滚动可能是最好的解决方法。

我说的占位太多是指现在的感觉非常不自然，有点太挤了。可能维持以往的spacing之后加滚动允许更多tab吧

**Comment by takuron** [comment]
个人认为最优的解决方案还是踢掉热度合并进搜索选项，因为（插画的）热度排序这个界面无法与 插画\漫画、小说、画师 这三个界面并列，热度应该属于搜索设置而不是单独开启界面。这个界面逻辑有一点问题，可以精简掉。滚动也有滚动的问题，滑动也是操作成本。
另外这里的翻译应该优化下，例如Illustrations/Manga Collection可以简化成picture之类，此处应该根据语言实际情况使用能够给予足够推断出类型的简单词语就可以，不需要逐字翻译。

**Comment by takuron** [comment]
搜索的问题是这样的，我是希望直接让八成用户直接输入任何内容都能得到满意的结果做出的“搜索”。

**Comment by SodaWithoutSparkles** [comment]
如果是合并成pictures好像不太好，改成Artworks可能更好

热度排序好像是这个pixiv客户端的买点之一，感觉还是不要砍掉/合并比较好

**Comment by takuron** [comment]
pixiv官方把热度拿出来是为了卖会员，咱又不卖会员我觉着还是怪怪的。
（也许加个官方的会员广告会更加和谐？）
总之这个热度和小说画师并列是绝对的逻辑错误，要是不行就学官方把小说插画画师拆三个页面，有热度的单独再加顶部tab。
再或者直接默认热度排序也行。

**Comment by SodaWithoutSparkles** [comment]
有着官方没有的功能才是第三方应用的主要买点，不然谁用第三方啊

加会员广告我觉得没需要，因为买会员这个项目不会得益，显得很奇怪

默认热度排序会有个问题，就是有些tag搜热度搜不出来，但实际上是有的

小说；插画；画师，分三个tab来处理也是不错的，不过实际上怎么放到应用里面是个问题。搜寻栏隔壁选择？还是直接在底部多分几个tab？还是侧边导航栏分开？需要讨论一下。

**Comment by takuron** [comment]
热度搜索这个bug有例子吗，我在使用过程中是没有发现的，可否给几个关键词我测试一下。
我还是倾向排序方式是一个搜索选项这个方案的，但我觉得要是热度没有bug默认热度可能会解决热度排序不明显这个问题，回头做个统计看看用日期的多还是用热度的多。

**Comment by SodaWithoutSparkles** [comment]
搜一些冷门的tag就会有了，或者冷门tag的组合。我有空找几个作例子。

感觉热度排序的机制是把热度前n个在伺服器保存，接到request的时候就在那个list中找前30个，如果不到三十个就只return找到的。但是如果你搜索的东西比较冷门，连前n个也不到的话，那样就会搜不出来。

我也有试过搜正常的没出现结果，搜热度能搜出来。现在的界面(正式版)的话可以。更加方便的发现这个问题。

我个人用热度排序是比较多的，倾向保持现有的状态

**Comment by takuron** [comment]
这个倒不是，我用作测试的tag就是一个只有五个结果的，热度或者日期都是正确的。
主要还是热度不能并列的问题，要是热度比较多那就默认热度，日期需要在选项里面调出来。并且最新的修改小说也可以非会员前三十个热度了，也加上去？tab最后肯定会过于拥挤，所以我倾向直接并进来。

**Comment by sunbeams001** [comment]
@takuron 所以帮你改下排序默认值为热度吗，就不用另外PR了

**Comment by SodaWithoutSparkles** [comment]
不建议，有些时候会有bug令热度出不来。

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 可以用最新版试试，每次合并都有debug版的包，也许你的问题已经解决过了

**Comment by SodaWithoutSparkles** [comment]
不懂就问，那个debug版的包在哪里找？

**Comment by sunbeams001** [comment]
![image](https://user-images.githubusercontent.com/3478170/128601788-846f6e25-147c-49db-b5fe-44d13d47e4f4.png)
![image](https://user-images.githubusercontent.com/3478170/128601803-73c410d3-c18f-4bbc-877e-26f0a2f8e0e6.png)

**Comment by SodaWithoutSparkles** [comment]
暂时好像找不到了，不过我有个提议：

要不把热度和普通排序合并在同一个tab里面，先显示能显示出来的热度排序，加一个分割线，再显示普通排序，直接向下滑就可以了。

有重复也没必要处理，因为热度排序之后有明显的分割线。

如果有会员的话像现在这样再开启就行。这样即便有我刚说的那个bug也不会影响。

**Comment by takuron** [comment]
1.如你所说有些也有时间不显示热度正常显示的，但无论哪个我用了这软件快一年也没发现过，你也不能给我一个可以正确复现该问题的例子。个人认为这是一个你个人的网络问题或者极罕见问题的可能性更大，还是如果有反馈的话那就再做修改。
2. 你这个方案不还是等同于热度优先？30个说多不多说少不少，对真需要时间排序的人来说还是额外操作了，感觉也不如搜索选项的方案。
3. 帮我改成热度优先吧，另外再就是我觉得可以去掉搜索选项里面的保存按钮，有选项变更就自动刷新这样能节省些操作，我的网络下这样也不会造成过多等待，要是能一起做了我就不改等正式版反馈了。

**Comment by sunbeams001** [comment]
@takuron 切换马上应用倒是也可以，那需要同时关掉侧栏吗，直接关掉感觉有点太过激了

**Comment by takuron** [comment]
不用关掉比较好吧。

**Comment by SodaWithoutSparkles** [comment]
如果某些tab 没有东西的时候隐藏掉可行吗？

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 强行增加代码难度，用户开这个选项也是使用成本，我觉得不合适

**Comment by SodaWithoutSparkles** [comment]
那么能不能加个开关返回之前的tab layout？

**Comment by takuron** [comment]
我觉得这些都是徒增代码难度，要不就直接大改tab改成推特那种特别紧凑的，目前的样式只适合2-4个（还需要翻译合适），增加设置也是一种形式的徒增学习成本，空界面的问题既无其他反馈也没有可供复现的明确关键词恕不能定性成bug（我个人用了一年多，各种奇奇怪怪的关键词都搜过，真的从来没发生过）。私以为继续这样让插画处于特殊地位是不妥的（就算还需要热度也应该是官方那种拆成每种搜索单独的界面然后加tab比较合适），并且根据调查需要经常最新和最热切换的用户也属于少数，纯热度默认情况下能满足6成以上的用户合理。并且侧滑设置很容易重新打开其他功能并且专程制作了引导也不会存在用户不知道的情况。你这样修改是真的没什么意义，要是反对意见多也应该回归官方的样式，这是我的观点。
