### ISSUE TITLE
[Translation] 多个翻译问题

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#383]
![IMG_20210805_040423.jpg](https://user-images.githubusercontent.com/64138578/128247724-ff7bc8a4-610d-452e-b03d-7f302f0ae12e.jpg)

- "非公开"的英语翻译non-public感觉有点怪
> 改成private感觉比较好？
- "动态"的英语翻译挺肯定不是dynamic
> ~~不知道怎么改~~官网是翻译成Feed
- 对画师的关注翻译成"watch"可能不太好
> 改成follow或者subscribe？
- 繁体中文翻译点进右下角"R"的tab，在左上的"R"tab不知为何变成了"[R"
> 这个简单
- "最新"的英文翻译是"newest"?
> 没记错应该是"latest"
- "精华列" 英文好像翻译成了 "精油列"？
> 可能要复核一下
- "以图搜源" 英文翻译有点怪
> 翻译成"Reverse image search"可能比较好
- 我的关注 英文好像翻译成 "我关心的事"
> 官网是翻译成following的

先这样吧

**Comment by sunbeams001** [comment]
最好你自己改吧，能优化下是最好，开个长期issue，把修改的都记录下，改翻译也不用写啥代码，这东西当初都纯机翻的

**Comment by SodaWithoutSparkles** [comment]
问题是我不知道咋改，档案在那个位置

**Comment by takuron** [comment]
我觉得相比于机翻丢人，把主语言设置成英文之后带对应语言的翻译者补齐更好。不必非得机翻填满

**Comment by sunbeams001** [comment]
很少英文用户，有是有但是不懂安卓，只是在tg群里反馈过有地方看不懂
想精益求精就自己动手吧
https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/app/src/main/res/values-en/strings.xml

**Comment by SodaWithoutSparkles** [comment]
我改天做，之后PR。

话说的61行的🐴是咋回事

**Comment by SodaWithoutSparkles** [comment]
```
    <string name="how_about_trending">动态页面展示谁的作品？</string>
```
这个是什么情况的时候用的？

顺便帮我看看为啥build不了？
https://github.com/SodaWithoutSparkles/Pixiv-Shaft/commit/17860c9280050ff7ad5a781a922c9c559c37ffe3

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 
how_about_trending 这东西代码里没引用
open_direct_connection 开启直连啊，我也不知道咋翻译
see_pixiv_ez 详见另一个项目
66 67 68 是占位符，在界面里就被覆盖了，相当于没用上，不用管

build 失败看日志是说 繁中的文件的 string_193 有问题

**Comment by sunbeams001** [comment]
关注用户用 subscribe 吗，我觉得 watch 或 follow 就行啊？

**Comment by SodaWithoutSparkles** [comment]
因为文档其他地方有的用subscribe有些用follow有些用watch，我也不知道换那个。你看看想用那个？不过统一的话比较好。

这个你看看怎么改

**Comment by sunbeams001** [comment]
官方是follow就follow吧

**Comment by SodaWithoutSparkles** [comment]
```
  <string name="string_193">作品尺寸：%dpx * %dpx</string> 
```

**Comment by SodaWithoutSparkles** [comment]
> open_direct_connection 开启直连啊，我也不知道咋翻译

直连是P2P链接的意思吗？这样的话改成 `Use P2P connection to server` 行不行？

**Comment by sunbeams001** [comment]
> > open_direct_connection 开启直连啊，我也不知道咋翻译
> 
> 直连是P2P链接的意思吗？这样的话改成 `Use P2P connection to server` 行不行？

完全是两回事，感觉老外也用不到这个吧，可以意译成 Bypass GFW 什么的就行了

**Comment by SodaWithoutSparkles** [comment]
> Bypass GFW
现在的机制是怎样的？默认开启？可能改成每次开应用的时候ping google.com来看看需不需要开，需要就自动开，但是保留手动设置。默认开启自动设置，关闭自动设置之后就可以选择开启或关闭。

**Comment by sunbeams001** [comment]
外网环境无所谓，相当于全程代理，你开了也不会导致连不上

**Comment by SodaWithoutSparkles** [comment]
这样不会有overhead或者延迟吗？

感觉知道为啥build 不了了，我把报错日志抄出来：

```
/home/runner/work/Pixiv-Shaft/Pixiv-Shaft/app/src/main/res/values-en/strings.xml:153:2: Failed to flatten XML for resource 'never_show_again' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/Pixiv-Shaft/Pixiv-Shaft/app/src/main/res/values-en/strings.xml:153:2: string/never_show_again does not contain a valid string resource.
```

现已修复，看看能不能过check

**Comment by SodaWithoutSparkles** [comment]
说起来我看有好多翻译的内容是重复的啊，这个是咋回事？

**Comment by sunbeams001** [comment]
> 说起来我看有好多翻译的内容是重复的啊，这个是咋回事？

原作者知道，至少我开始PR时候就这样了

**Comment by SodaWithoutSparkles** [comment]
是所有都有用上的吗... 那么我就要全部再翻译一次了...

**Comment by sunbeams001** [comment]
还有个事啊，你要是提交PR最好把你改的新建一个单独分支再提交，别master到master，后期你自己代码就乱了

**Comment by SodaWithoutSparkles** [comment]
原来如此，学到了学到了。真正用github还是今年的事，感谢大佬指路。

那么我把全部Watch 和subscribe改成follow了

**Comment by SodaWithoutSparkles** [comment]
https://github.com/SodaWithoutSparkles/Pixiv-Shaft/pull/1

你看看这个PR行不行？

**Comment by sunbeams001** [comment]
@SodaWithoutSparkles 差不多是这个意思，左边换成这个项目的master就行了

**Comment by SodaWithoutSparkles** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/pull/390

PR 完成，你看看行不行？

**Comment by sunbeams001** [comment]
收藏，官方好像是叫 bookmark 来着？

**Comment by SodaWithoutSparkles** [comment]
> 收藏，官方好像是叫 bookmark 来着？

也是有很多说法，你觉得bookmark 比较好？
或者我把整个档案处理完成之后再PR吧

**Comment by sunbeams001** [comment]
也无所谓 至少现在都是favorite 比collection好多了

**Comment by SodaWithoutSparkles** [comment]
Emmm，那么现在合并掉，我过几天有空再翻译

**Comment by SodaWithoutSparkles** [comment]
```
  <string name="string_227">未安装手Q或安装的版本不支持</string>
```
这个是什么？

**Comment by sunbeams001** [comment]
加QQ群提示啊

**Comment by SodaWithoutSparkles** [comment]
> 加QQ群提示啊

我实在不知道怎么翻译，老外应该不会用qq所以扔着这样？

**Comment by SodaWithoutSparkles** [comment]
https://github.com/SodaWithoutSparkles/Pixiv-Shaft/commit/7b048ad459b6e7f9826afac4726131cee55331fa

你看看有没有问题？

**Comment by sunbeams001** [comment]
我直接在 pr 上标注了

**Comment by SodaWithoutSparkles** [comment]
难怪我在官网上面搜索不到精华列

**Comment by sunbeams001** [comment]
我觉得像是这种意思 Selected 啊 Chosen，Collected 什么的，本地标签属于意译了，你随意吧，都差不多

**Comment by SodaWithoutSparkles** [comment]
那么就`Personal selection`吧

**Comment by SodaWithoutSparkles** [comment]
这个issue等出下一个正式release的时候就关掉把
