### ISSUE TITLE
为何新版本没有发布在谷歌play商店？？

### ISSUE THREAD

**Issue by yohar2b** [CeuiLiSA/Pixiv-Shaft#386]

**Comment by yohar2b** [comment]
就是问一下，因为看到谷歌商店里边的版本一直没有更新

**Comment by SodaWithoutSparkles** [comment]
好像之前有说过，作者有了新工作有点忙，所以没时间更新了。

建议在那边更新最后一次，不过在那个更新里面说明现在主要发布渠道已经改变。

顺便加一个检查更新的功能，预设开启自动检查更新（开app检查一次），可以手动检查，有更新就direct 去 release。这堆东西可以塞进设定/关于本应用
