### ISSUE TITLE
下载GIF能否增加一个同时下载压缩包的选项

### ISSUE THREAD

**Issue by khvarenah** [CeuiLiSA/Pixiv-Shaft#403]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

注意到合成的GIF分辨率都比较小
这应该也是由于手机性能限制的？
同时发现下载GIF的过程中会把压缩包下载到一个缓存文件夹中，之后再进行合成
能否增加一个将压缩包下载到图片文件夹的选项？

### 

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

暂无

**Comment by sunbeams001** [comment]
哪个分辨率小了，给个id看看，印象中没有缩图的处理

**Comment by khvarenah** [comment]
> 哪个分辨率小了，给个id看看，印象中没有缩图的处理
91856516
图片本身应该是540x960
但是保存的GIF为338x600
图片信息见图[https://sm.ms/image/OkSq9T1wMCDygjP](url)

**Comment by sunbeams001** [comment]
确认了下，App的GIF元数据接口里就没返回原图地址，不像PC版接口，所以暂时没办法，就是给了你压缩包里面也不是原图大小

**Comment by khvarenah** [comment]
> 确认了下，App的GIF元数据接口里就没返回原图地址，不像PC版接口，所以暂时没办法，就是给了你压缩包里面也不是原图大小

好吧，了解了
