### ISSUE TITLE
特殊情况下看不到返回键

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#408]
二级详情返回键在特殊情况下没法看到，例如图片左上纯白一片就看不清。

建议：和分享鍵一样增加阴影效果

虽然分享键加了阴影也要特意去看才能看清，不过总比看不见瞎猜好

**Comment by sunbeams001** [comment]
你帮忙找找，我手里没有现成的

**Comment by SodaWithoutSparkles** [comment]
找找返回键图标？

**Comment by sunbeams001** [comment]
是的

**Comment by sunbeams001** [comment]
这个东西啊，官方pixiv应用是有带阴影图标的，但是是 <- 这个样子的，和现在这个矢量图标不一样，不过矢量图一般很少加阴影啊，要找一个 < 这样带阴影的

**Comment by SodaWithoutSparkles** [comment]
如果在同一个位置向下偏移一点之后设置同一个矢量图，更改为灰色？

**Comment by sunbeams001** [comment]
> 如果在同一个位置向下偏移一点之后设置同一个矢量图，更改为灰色？

没这么干的，要加阴影不是层叠，可以找个美工或者你自己PS试一下
