### ISSUE TITLE
建议加一个打开支持的链接

### ISSUE THREAD

**Issue by ding667** [CeuiLiSA/Pixiv-Shaft#41]
![S91125-012157](https://user-images.githubusercontent.com/48525679/69498349-0d9e3c00-0f22-11ea-8206-f90d1c4d5f2e.jpg)
![S91125-012044](https://user-images.githubusercontent.com/48525679/69498354-15f67700-0f22-11ea-9c6b-c0498953b210.jpg)
这样就可以直接以Sharft打开，而不用复制ID了…

**Comment by duzhaokun123** [comment]
![Screenshot_20191125-012629_](https://user-images.githubusercontent.com/39830683/69498424-e5630d00-0f22-11ea-8779-c925077adb43.png)
本身就有啊

**Comment by ding667** [comment]
蛤？

**Comment by ding667** [comment]
那为啥不能链接跳转

**Comment by duzhaokun123** [comment]
因为 Shaft 不被认为是浏览器应用吧

**Comment by ding667** [comment]
…
还得复制ID，好麻烦

**Comment by CeuiLiSA** [comment]
你俩头像看着差不多，我TM看半天以为一个人自言自语呢

**Comment by CeuiLiSA** [comment]
@ding667 你能不能给一个链接样式，我看下链接样式，就可以控制点这个链接的时候跳到这个APP

**Comment by ding667** [comment]
> @ding667 你能不能给一个链接样式，我看下链接样式，就可以控制点这个链接的时候跳到这个APP

#NSFW 德丽莎透明化事件 / fufumi #pixiv
https://www.pixiv.net/artworks/77959725

**Comment by ding667** [comment]
> @ding667 你能不能给一个链接样式，我看下链接样式，就可以控制点这个链接的时候跳到这个APP

样式和描述是一样的…就是没法用它打开

**Comment by duzhaokun123** [comment]
@ding667 看上去你的应用需要你选择一个***浏览器***以打开链接

而不是一个可以打开`www.pixiv.net`的应用以打开链接

因为可以打开`*`的 ADM Editor 没有出现在列表中，但 ADM Browser 出现了

**Comment by ding667** [comment]
> @ding667 看上去你的应用需要你选择一个_**浏览器**_以打开链接
> 
> 而不是一个可以打开`www.pixiv.net`的应用以打开链接
> 
> 因为可以打开`*`的 ADM Editor 没有出现在列表中，但 ADM Browser 出现了

…无论从tg点击这个链接还是在这里点击都是唤起浏览器

**Comment by duzhaokun123** [comment]
@ding667 这因该是 tg 和你的浏览器的问题

**Comment by ding667** [comment]
> @ding667 这因该是 tg 和你的浏览器或 GitHub 的问题

从标签里打开也一样…要不你试试
![S91126-001541](https://user-images.githubusercontent.com/48525679/69557672-f6268800-0fe1-11ea-8209-2dfc8944a5d6.jpg)

**Comment by duzhaokun123** [comment]
@ding667 额... 是什么应用

**Comment by ding667** [comment]
> @ding667 额... 是什么应用

便签

**Comment by CeuiLiSA** [comment]
我马上升级一个版本，应该是解决了，你们从外部点开https://www.pixiv.net/artworks/77959725，然后选择用其他应用打开， 应该是可以唤起这个app
