### ISSUE TITLE
首页无内容

### ISSUE THREAD

**Issue by tianyun1114** [CeuiLiSA/Pixiv-Shaft#416]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.10

### Android system version

10

### Device model

galaxy S9

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

从2.6.8（直连正常使用）覆盖安装至3.2.10
1.开代理登录后显示登录成功，然后一直显示“资源解析中“

2.关闭应用重新打开进入app，侧页账户已登录，首页推荐作品显示”这里什么都没有“，热门标签有内容，点进任意标签插画/漫画无内容，小说有搜索结果但点任意作品白屏，画师有搜索结果但画师详情页显示”这里什么都没有“。

3.首页点击放大镜搜索按钮直接闪退，个人主页无内容

4.代理/直连/pixivcat和wifi/数据（均为联通）都组合操作过，重开应用依旧无内容，开代理手机浏览器上P站能正常浏览内容

### Expected behavior / 期望行为

显示内容

### Actual behavior / 实际行为

无内容

**Comment by sunbeams001** [comment]
跨版本有点多，建议卸载重装，看起来是网络有问题
不知道你用的是什么代理，不过可以尝试以下步骤：
开启直连，关掉代理（确认完全关掉）
关闭直连，开启代理，测试官方App是否可以访问（网页机制不同参考意义有限），尝试更换代理或切换线路

**Comment by tianyun1114** [comment]
卸载重装，登陆后直连正常使用，后续步骤未测试
