### ISSUE TITLE
[bug] 分享并以图搜源会打开多个窗口

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#419]
## 预计行为
分享图片到shaft以图搜源时会利用上一个窗口

## 实际行为
会出现多个窗口

## 重现方法
1. 准备2个以上能成功以图搜源的图片，而且能找到pixiv ID的
2. 在相册/档案浏览器分享该图片到shaft并以图搜源
3. 在以图搜源的界面点击结果的pixiv ID
4. 在相册/档案浏览器重复步骤2-4，直到全部已经准备的图片都完成
5. 切换后台，发现多个窗口

## 可能的解决方法
在搜源的时候检查是否有上一个实例，如有就使用，并关闭现在的程序

**Comment by sunbeams001** [comment]
有没有想过这其实是个feature呢？

**Comment by SodaWithoutSparkles** [comment]
不会占用大量资源吗？

**Comment by sunbeams001** [comment]
不会
