### ISSUE TITLE
希望在作者页面将漫画作品从“其他”一栏中移出成为单独一栏

### ISSUE THREAD

**Issue by 1235789gzy1** [CeuiLiSA/Pixiv-Shaft#420]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

p站的插画和漫画作品是在同一个页面的两栏，希望shaft也能将漫画页面做为画师信息一栏，当然杂糅也行
（这玩意藏的也太深了，我就说怎么感觉关注的画师作品少了不少，找半天在找到混在信息页面里的插画作品）

### 

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by sunbeams001** [comment]
倒是不难，只要画过任何漫画就单独加一个tab？

**Comment by 1235789gzy1** [comment]
对
