### ISSUE TITLE
何不增加扩展插件的功能？(例如评论加上谷歌翻译的功能的扩展？)

### ISSUE THREAD

**Issue by chenskiro** [CeuiLiSA/Pixiv-Shaft#423]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

希望在评论下方可以加上类似于Twitter的那种谷歌翻译，点击就会在下方提供翻译后的文字

### 

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by DTpeel** [comment]
尽管这的确不是刚需，但可以实在的优化用户体验，不用在第三方之间切换，既然要lees is more 将核心做到极致，那不妨增加一下扩展插件的选项，由用户自行选择/上传/下载，既可以保持apk的轻量，也可以优化体验，这是最优解决方案
