### ISSUE TITLE
桌面控件的小建议

### ISSUE THREAD

**Issue by XiaoMouz** [CeuiLiSA/Pixiv-Shaft#425]
添加刷新小按钮，使其可以手动刷新
在设置中可以设定小控件显示推荐图还是显示已喜爱的图或已下载文件夹等

非常抱歉，在issue模板中没有找到可用模板，因此选择直接发送

**Comment by SodaWithoutSparkles** [comment]
如果是喜爱的图的话希望可以选择那些喜爱的图。例如我有1024个喜爱的图没理由全都加进去或者全都随机出现吧？可能可以用本地分类功能，就是长按收藏会出现的那个菜单。

如果用github app的话会找不到最新的ymal模板，剩下预设的 no template

**Comment by sunbeams001** [comment]
刷新可以加，其他你完全可以用别的单独的桌面美化应用实现

**Comment by XiaoMouz** [comment]
好耶，有刷新键啦

**Comment by magzeya** [comment]
可以双击点入画作的详情页，或者收藏吗
