### ISSUE TITLE
增加一个小说区看评论的功能

### ISSUE THREAD

**Issue by horryruo** [CeuiLiSA/Pixiv-Shaft#427]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

如题，增加一个小说区看评论的功能，虽然有tag功能，这个点赞，但是红心数阅读量等不是很直观，也看不见作者写的简介、发帖时间等等，建议可以仿照官方应用的布局，不过最想要的还是评论区，谢谢

### 

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

pixez也不支持

**Comment by sunbeams001** [comment]
不会设计布局怎么办，就随便搞搞
