### ISSUE TITLE
请问可以在下载图片 自定义文件名称里添加时间和标签吗？

### ISSUE THREAD

**Issue by WencongZuo** [CeuiLiSA/Pixiv-Shaft#428]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

请问有没有可能在下载图片，自定义文件名称时，添加作品创作时间及作品所含标签作为文件名称可选内容？

### 

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by sunbeams001** [comment]
创作时间感觉还行，不知道你想要什么格式的？可读的还是时间戳？给个示例
标签不是很推荐，一个是长度太长，然后标签可变，一旦有增减，会丧失判断文件是否已下载的功能

**Comment by WencongZuo** [comment]
我想就是普通的日期格式就好
我自己手动修改了两种 你看一下 哪种比较简单
![Screenshot_2021-10-13-16-47-27-138_com miui gallery](https://user-images.githubusercontent.com/92371141/137093992-ba4cb61f-3db2-4b21-bbca-c6087c6ce1f6.jpg)
![Screenshot_2021-10-13-16-47-10-675_com miui gallery](https://user-images.githubusercontent.com/92371141/137094029-9b49fcdc-3abf-4bf2-9afe-ca19ceef9cfb.jpg)
可能也要考虑文件名长度 20211013这种格式会比较好吧 感谢
