### ISSUE TITLE
关于应用文件夹的建议

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#43]
看到了这个 #42 就想到了这个问题

1. 图片下载路径应为`/stroage/emulated/0/Pictures/Shaft/SingleImages`

2. GIF压缩包存放路径应为`/stroage/emulated/0/Download/Shaft`

3. GIF压缩包解压路径应在***应用缓存文件夹***中

4. GIF生成路径应为`/stroage/emulated/0/Pictures/Shaft/Gif`

这样就不用为 Shaft 开启存储重定向了

**Comment by CeuiLiSA** [comment]
说改就改，下版本见
