### ISSUE TITLE
如果图片标题含有特殊字符则下载图片报错

### ISSUE THREAD

**Issue by ouy160** [CeuiLiSA/Pixiv-Shaft#437]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

newest version

### Android system version

7

### Device model

true

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.图片标题含有/ \ ? * < > " |
2.下载
3.图片下载报错

### Expected behavior / 期望行为

将/ \ ? * < > " |字符替换为其他字符，即可正常下载

### Actual behavior / 实际行为

1.图片标题含有/ \ ? * < > " |
2.下载
3.图片下载报错

**Comment by sunbeams001** [comment]
来个ID，这种应该是有处理过，可能覆盖不全

**Comment by ouy160** [comment]
https://www.pixiv.net/artworks/93845723

> 来个ID，这种应该是有处理过，可能覆盖不全

这个https://www.pixiv.net/artworks/93845723

**Comment by sunbeams001** [comment]
![Screenshot_2021-11-01-14-59-39-427_com.alensw.PicFolder.png](https://user-images.githubusercontent.com/3478170/139633797-9adedb17-7f37-4d1a-8710-b8f56d1bffc5.png)

下成功了啊，你有啥报错吗？

**Comment by ouy160** [comment]
> ![Screenshot_2021-11-01-14-59-39-427_com.alensw.PicFolder.png](https://user-images.githubusercontent.com/3478170/139633797-9adedb17-7f37-4d1a-8710-b8f56d1bffc5.png)
> 
> 下成功了啊，你有啥报错吗？

我在逍遥模拟器7.0,64位中用传统下载模式下载的,有报错信息.
在SAF模式下正常下载
![Screenshot_20211101-164309](https://user-images.githubusercontent.com/32807088/139645559-8dee1fc3-e21c-4984-a1e6-4d351c4d0326.png)

**Comment by sunbeams001** [comment]
官方模拟器Android 11/12 试了下没问题，你这个可能是厂商魔改导致的，换个兼容好点的模拟器试试吧

**Comment by soloopooo** [comment]
> 官方模拟器 Android 11/12 试了下没问题，你这个可能是厂商魔改导致的，换个兼容好点的模拟器试试吧

不。跟你说的无关。
这跟文件名禁止使用的字符有关。要复现这个问题，请保证保存的文件名带有作品名称。

**Comment by soloopooo** [comment]
> ![Screenshot_2021-11-01-14-59-39-427_com.alensw.PicFolder.png](https://user-images.githubusercontent.com/3478170/139633797-9adedb17-7f37-4d1a-8710-b8f56d1bffc5.png)
> 
> 下成功了啊，你有啥报错吗？

下划线不属于被文件名禁止使用的范畴，所以不会报错。

**Comment by sunbeams001** [comment]
@soloopooo 因为代码里改掉了啊，非法字符已经替换为下划线了

**Comment by ouy160** [comment]
> 官方模拟器Android 11/12 试了下没问题，你这个可能是厂商魔改导致的，换个兼容好点的模拟器试试吧

ok
