### ISSUE TITLE
功能请求 - 无痕模式

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#439]
现在浏览一定要登入，有办法不登入就浏览吗？例如普通的pixiv如果不是年龄限制也可不登入浏览。

无痕模式是相当于不登入，不保存任何东西。相当于开一个临时账号那样。但是无法收藏，也不会被现有账户里的推荐影响。

如果能实行的话，建议入口放在换账户哪里。

**Comment by sunbeams001** [comment]
没啥必要，注册账号也不费事，不想过多更改账号和API设计架构
