### ISSUE TITLE
希望增加一个修改预览图片显示质量的设置选项

### ISSUE THREAD

**Issue by 850710247liu** [CeuiLiSA/Pixiv-Shaft#445]
让图片预览中的图片质量更高一些，现在在平板上及win11安卓器上显示略微模糊，因为电脑和平板的屏幕比较大

![Screenshot_20211204_114358_ceui.lisa.pixiv_edit_39377772401383.jpg](https://user-images.githubusercontent.com/59795360/144695747-3fbc9921-ac56-4a23-a4d6-3d92c5ef37e2.jpg)

**Comment by sunbeams001** [comment]
可以哦，载入可能会慢一点了

**Comment by 850710247liu** [comment]
好 不是加载原图就行 比原来稍微慢一点质量高一点就行 QvQ
