### ISSUE TITLE
屏蔽功能在小说中失效

### ISSUE THREAD

**Issue by pandoleya** [CeuiLiSA/Pixiv-Shaft#446]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.20

### Android system version

miui 12.5

### Device model

Redmi K40

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1. 在小说tab下，即使屏蔽tag或作者，相关小说依然会显示
2. 小说浏览界面中，点击右上角选项（三个点），没有屏蔽设置的选项

### Expected behavior / 期望行为

1. 在小说tab下，屏蔽tag或作者后，相关小说会不予显示
2. 小说浏览界面中，点击右上角选项（三个点），有屏蔽设置的选项

### Actual behavior / 实际行为

1. 在小说tab下，即使屏蔽tag或作者，相关小说依然会显示
2. 小说浏览界面中，点击右上角选项（三个点），没有屏蔽设置的选项

**Comment by sunbeams001** [comment]
这个好像是当初设计时候就只考虑了插画，小说也没太多人用所以没加，可以做
