### ISSUE TITLE
保持屏幕常亮

### ISSUE THREAD

**Issue by Jacheers** [CeuiLiSA/Pixiv-Shaft#447]
希望可以添加一个保持屏幕常亮的选项，看漫画时会比较方便点。

**Comment by sunbeams001** [comment]
全局设置吗？还是只针对漫画作品？
另外在设置中切换也不太方便，是否放到插画二级详情中更容易操作？

**Comment by Jacheers** [comment]
全局就可以了，这种选项也不会有人频繁改。
