### ISSUE TITLE
设置中增加非wifi网络不自动下载的选项

### ISSUE THREAD

**Issue by 1235789gzy1** [CeuiLiSA/Pixiv-Shaft#448]
我希望设备在使用移动网络时可以设置不自动下载
即移动网络下载图片只增加到下载列表，但是不执行下载操作，在设备连接到wifi时开始下载

**Comment by AsakiRain** [comment]
希望可以同时增加wifi下手动开始下载的功能，我这里直连或者使用pixiv.cat的速度不太乐观，下载任务有时候会影响浏览

**Comment by sunbeams001** [comment]
大概是3个级别：
直接下载
移动网络不直接下载
任何网络都不直接下载

**Comment by 1235789gzy1** [comment]
我觉得可以
