### ISSUE TITLE
动图详情界面依旧为老界面

### ISSUE THREAD

**Issue by ghost** [CeuiLiSA/Pixiv-Shaft#449]
![Screenshot_20220101_015342_com.github.android.jpg](https://user-images.githubusercontent.com/59795360/147834722-afadbfa9-c39c-412f-8325-5bf44c3ba0dd.jpg)

**Comment by sunbeams001** [comment]
不会设计UI啊，现在的新界面布局也不是专门给GIF设计的
你要是有需求可以自己做好了提交PR
