### ISSUE TITLE
MIUI13设置白屏

### ISSUE THREAD

**Issue by ODtian** [CeuiLiSA/Pixiv-Shaft#455]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.20

### Android system version

12

### Device model

小米11

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

打开设置，直接白屏，其他界面无问题

### Expected behavior / 期望行为

无白屏

### Actual behavior / 实际行为

有白屏

**Comment by sunbeams001** [comment]
没用过13，建议备份设置卸载掉重新安装试试

**Comment by ODtian** [comment]
从3.1.5到3.2.20都试过了，都是没有设置，在原生a12上就没这个问题，也许是miui13的锅，我等过几天有更新了再试一下

**Comment by ODtian** [comment]
3.23 miui13开发版已经修复
