### ISSUE TITLE
B添加切换图床的功能（使用直连时无法加载出图片本身）

### ISSUE THREAD

**Issue by FlandiaYingman** [CeuiLiSA/Pixiv-Shaft#459]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.20 & 3.1.5 (186)

### Android system version

Android 11 / MIUI 12.5.15

### Device model

MI 11

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

打开设置中的“开启直连”。
选项“使用 PixivCat 代理“似乎对此问题没有任何影响。

### Expected behavior / 期望行为

打开”开启直连“后，应能加载出图片本身。

### Actual behavior / 实际行为

没有加载出图片本身。

### Other details / 其它细节

使用 Notsfsssf/pixez-flutter 时，这问题同样出现。可以推测是我所使用的网络（中国移动）不太支持域名前置等绕过 GFW 的方式。不过，Notsfsssf/pixez-flutter 有选项可以切换图床为 `i.pixiv.re`，之后就可以加载图片了。希望 Pixiv-Shaft 也添加此功能。

**Comment by sunbeams001** [comment]
已经是这个了
