### ISSUE TITLE
奇怪的表现

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#46]
![Screenshot_20200104-234809_](https://user-images.githubusercontent.com/39830683/71768108-31f02e00-2f4e-11ea-80b1-e4a0aeb65001.png)

**Comment by CeuiLiSA** [comment]
这是腾讯MTA统计库，用来查看在线用户信息和错误日志搜集。有一说一你你这监视工具还挺高级

**Comment by duzhaokun123** [comment]
查看在线用户信息什么的不需要经过用户同意吗？

工具是存储重定向 https://sr.rikka.app/zh-hans/

**Comment by CeuiLiSA** [comment]
这里的信息指的是，机型参数，在线人数，这些在google play都可以看到
然后闪退的错误日志，google play没法看，就用这个工具了。你想的敏感参数是需要READ_PHONE_STATE才能看到的，但是我根本没申请这项权限


 
---原始邮件---
发件人: "Du Zhaokun"<notifications@github.com&gt;
发送时间: 2020年1月6日 19:27:10
收件人: "CeuiLiSA/Pixiv-Shaft"<Pixiv-Shaft@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"CeuiLiSA"<fatemercis@qq.com&gt;;
主题: Re: [CeuiLiSA/Pixiv-Shaft] 奇怪的表现 (#46)



查看在线用户信息什么的不需要经过用户同意吗？
 
工具是存储重定向 https://sr.rikka.app/zh-hans/

**Comment by duzhaokun123** [comment]
行吧
