### ISSUE TITLE
直接分享图片

### ISSUE THREAD

**Issue by Hugo7650** [CeuiLiSA/Pixiv-Shaft#461]
希望在作品详情页增加个分享图片选项（不是分享链接） 选择后会把图片分享到对应地方

**Comment by sunbeams001** [comment]
1.清晰度有要求吗？详情页的图不是原图也就能看的地步，下原图时间就不好控制了
2.多图只分享第一张？

**Comment by Hugo7650** [comment]
> 1.清晰度有要求吗？详情页的图不是原图也就能看的地步，下原图时间就不好控制了 2.多图只分享第一张？

1. 没要求 因为分享出去经常也会被二次压缩
2. 是

**Comment by sunbeams001** [comment]
已更新
