### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by banyue9527** [CeuiLiSA/Pixiv-Shaft#463]
应用无法登陆，挂了梯子也不行

**Comment by sunbeams001** [comment]
请阅读FAQ，可以登录

**Comment by banyue9527** [comment]
![Screenshot_2022-03-05-10-52-17-202_ceui lisa pixiv](https://user-images.githubusercontent.com/94790779/156865061-e3a0da86-0213-4e97-836a-1f43006082a5.jpg)
我用的是外部代理啊，点击登录加载一会儿见显示出错

**Comment by banyue9527** [comment]
找到问题了，我的v2ray开启了分应用代理，但是应用没有自动勾选shaft导致无法登陆
![Uploading Screenshot_2022-03-05-10-59-40-171_com.v2ray.ang.jpg…]()
