### ISSUE TITLE
收藏数筛选20000档结果过少

### ISSUE THREAD

**Issue by Zheng-san** [CeuiLiSA/Pixiv-Shaft#465]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.21

### Android system version

安卓10 MIUI12.5.2稳定版

### Device model

小米8

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

例如
1.搜索genshin标签图片，右上角进行筛选
2.关键字匹配 标签 部分匹配；收藏数筛选 20000人收藏；排序方式 最新作品 或 由旧到新
3.结果只有一张图片，实际上在收藏数筛选10000人收藏的结果中，就能找到很多收藏数大于20000的图片

### Expected behavior / 期望行为

应该筛选出收藏大于20000的图片若干

### Actual behavior / 实际行为

只搜到一张收藏大于20000的图片

### Other details / 其它细节

用其他标签也能复现这个bug，只不过筛选结果数不一样，可能是三五张，也有十几张，还可能没有，但数量绝对不准确，因为从大于10000收藏的筛选结果中就能搜到数目远超这个数量的图片，甚至大于50000收藏的数量都比20000的多

**Comment by sunbeams001** [comment]
此处原理为按照标签筛选，按照真实收藏数筛选为官方收费功能
