### ISSUE TITLE
无法使用邮箱登陆

### ISSUE THREAD

**Issue by thouser8** [CeuiLiSA/Pixiv-Shaft#466]
![172908d53e9f2040.jpg](https://user-images.githubusercontent.com/83090571/157791038-300e2d8d-cf1b-46fa-8893-f772bf4481aa.jpg)![-3bbe1f11e1cb3533.jpg](https://user-images.githubusercontent.com/83090571/157791047-fa82ede0-d078-4782-bdcd-07c29b668433.jpg)![2c841564c60c58b.jpg](https://user-images.githubusercontent.com/83090571/157791053-a5fe3d76-9322-428a-b63c-08d45527c660.jpg)

**Comment by sunbeams001** [comment]
看FAQ
