### ISSUE TITLE
首页刷新有概率排版错误

### ISSUE THREAD

**Issue by char-46** [CeuiLiSA/Pixiv-Shaft#467]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.21

### Android system version

12

### Device model

Redmi Note 11 Pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

首页点击左下角按钮刷新

### Expected behavior / 期望行为

排版正常

### Actual behavior / 实际行为

排版错误，推荐与排行榜重叠。
![Screenshot_2022-03-28-18-26-03-970_ceui lisa pixiv](https://user-images.githubusercontent.com/53117560/160379737-b9a6ecea-4a59-4558-b4a4-89399c8bf50d.jpg)

**Comment by sunbeams001** [comment]
老bug了，原因很神秘，不妨碍用
