### ISSUE TITLE
直连模式下图片下载超时异常以及详情页加载不成功

### ISSUE THREAD

**Issue by jishiqi-lgtm** [CeuiLiSA/Pixiv-Shaft#468]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.21

### Android system version

8.0

### Device model

knt_ul10

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

app内随机选择图片下载

### Expected behavior / 期望行为

经过一段时间后，下载完毕。

### Actual behavior / 实际行为

几秒钟之后，抛出线程超时异常。

下载失败，原因： java.net.SocketTimeoutException: timeout

### Other details / 其它细节

重启或多次重复下载不同图片，处境一致。
下载中或0或几k每秒。  详情页或也需多次加载。

**Comment by sunbeams001** [comment]
个别地区的网络问题，无法保证全部环境下直连都可用，我这里可以，推荐使用代理
