### ISSUE TITLE
请教一下oauth token的刷新机制？

### ISSUE THREAD

**Issue by mashirozx** [CeuiLiSA/Pixiv-Shaft#47]
java代码看着有点迷糊，这边token是定时刷新，还是每次需要用token来发送请求的时候都刷新一次？

oauth接口有个字段 `"expires_in"： 3600` ，不过测试了一个小时后token也还有效，不知道合适的刷新时机是什么样的？

**Comment by CeuiLiSA** [comment]
先说结论，token怎么刷新的？
每次请求的时候如果收到的response.getCode() == 400，就去刷新

为什么会code = 400？因为这个token失效了，可能是token时间太长过期了，也可能是这个账号在另一个设备登录导致现在持有的token过期了

这样到底规不规范？
不规范，因为我是偷了个懒，不应该用code = 400来刷新token，实际上pixiv有好几个接口在错误的情况下都会返回400，如未绑定邮箱的账号去做评论动作，那时候就会返回400，实际上不需要刷新token但是我现在的写法就把他误伤了，希望你能想个好的办法出来

这种刷新模式成本高吗？
成本很低，只需要判断responsecode 是否等于400，比本地存刷新时间更快

看一下需要请求token的例子：
1.--> GET https://app-api.pixiv.net/v1/spotlight/articles?filter=for_android&offset=10&category=all
2.--> POST https://oauth.secure.pixiv.net/auth/token
3.<-- 200 OK https://oauth.secure.pixiv.net/auth/token
4.<-- 200 OK https://app-api.pixiv.net/v1/spotlight/articles?filter=for_android&offset=10&category=all

不需要刷新token的时候：
1.--> GET https://app-api.pixiv.net/v1/spotlight/articles?filter=for_android&offset=10&category=all
2.<-- 200 OK https://app-api.pixiv.net/v1/spotlight/articles?filter=for_android&offset=10&category=all

**Comment by mashirozx** [comment]
感谢解答，已经明白了。

关于未绑定邮箱那点，在oauth接口可以获取到一个`is_mail_authorized`字段，或许能有所帮助。

目前看我也得效仿“不规范”的方法了ヽ(￣ω￣(￣ω￣〃)ゝ

**Comment by mashirozx** [comment]
PS. expires_in 好像指的是 refresh_token

**Comment by CeuiLiSA** [comment]
好的谢谢，大佬你睡得有点晚啊


 
---原始邮件---
发件人: "Mashiro"<notifications@github.com&gt;
发送时间: 2020年1月10日 23:52:11
收件人: "CeuiLiSA/Pixiv-Shaft"<Pixiv-Shaft@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"CeuiLiSA"<fatemercis@qq.com&gt;;
主题: Re: [CeuiLiSA/Pixiv-Shaft] 请教一下oauth token的刷新机制？ (#47)



PS. expires_in 好像指的是 refresh_token

**Comment by mashirozx** [comment]
我哪是大佬，菜得一批😂

**Comment by CeuiLiSA** [comment]
{"error":{"user_message":"","message":"Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_grant","reason":"","user_message_details":{}}}

这个是token过期的response.body().string();

在response.code == 400的时候，如果body不包含上面的那些东西，应该就是普通的400，不用刷新token
如果包含上面的错误，就说明该刷新token了
（又是一个偷懒的方法，亲测有效，不会误伤）
