### ISSUE TITLE
使用实际收藏数进行筛选

### ISSUE THREAD

**Issue by Hakoyu** [CeuiLiSA/Pixiv-Shaft#472]
比如说像查看某个tag近期的高收藏作品 我们会使用**tag+1000users入り**之类的方式来进行搜索

但这样有些许弊端
1. 这只是一个tag 作者和读者都可以自行添加 有些技术力不高作者会手动添加此tag以期望获取更高的阅读量
2. 作品能添加的tag有限 比如有多个角色的图片中 达到了上限就无法使用这种方式来搜索

所以希望使用图片的真实收藏数来作为筛选条件

**Comment by sunbeams001** [comment]
你这个问题加钱开会员可以解决

**Comment by Hakoyu** [comment]
行 那就先这样吧
