### ISSUE TITLE
无法载图

### ISSUE THREAD

**Issue by Ausar-Darkmode** [CeuiLiSA/Pixiv-Shaft#481]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.21

### Android system version

11

### Device model

Shark KSR-A0

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.Start app
2.Fail to load images

### Expected behavior / 期望行为

恢复查看图片

### Actual behavior / 实际行为

2022.10.14开始 无法载图
有时能加载出一两张缩略图 但是也看不到详情
pixiv官网正常
PixEz也有无法载图现象 但是相对好点

### Other details / 其它细节

none

**Comment by sunbeams001** [comment]
特殊时期个别地区的网络问题，无法保证全部环境下直连都可用，推荐使用代理
