### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by kyoyacchi** [CeuiLiSA/Pixiv-Shaft#484]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

Hi. Is it possible to translate this app to other language?
I'd like to translate Turkish language, if possible.
Since i don't know Chinese, im talking as English, it's on my list to learn..

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

Yes. (PixEz, i translated it for PixEz) *and other non-pixiv apps.*

### Any other information can be help? / 其它信息

Sorry for speaking English, i know this project's native language is Chinese.

**Comment by sunbeams001** [comment]
Just do it, make a pull request and I will merge it.

**Comment by kyoyacchi** [comment]
> Just do it, make a pull request and I will merge it.

Which file do i need to edit?

**Comment by kyoyacchi** [comment]
> Just do it, make a pull request and I will merge it.

https://github.com/CeuiLiSA/Pixiv-Shaft/pull/485
