### ISSUE TITLE
点击首页右上角放大镜（搜索）闪退

### ISSUE THREAD

**Issue by futuer-szd** [CeuiLiSA/Pixiv-Shaft#490]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.23（223）

### Android system version

基于miui12.5

### Device model

设备型号吗？(黑鲨)SHARK KLE-A0

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.打开app
2.点击‘放大镜’
3.闪退

### Expected behavior / 期望行为

正常使用

### Actual behavior / 实际行为

闪退

### Other details / 其它细节

其实还有其他问题，比如图片加载不了，就是首页推荐作品那里，包括其他地方。但是热门标签可以加载，并且热门标签的代表图也可以，但是点进去还是转圈。

**Comment by futuer-szd** [comment]
补充一句，从热门标签进入搜索界面正常，但是因为‘其他细节’中我说的问题，加载不住来，一直转圈

**Comment by sunbeams001** [comment]
网络问题，建议使用代理/开启直连/PixivCat代理

**Comment by futuer-szd** [comment]
可能是之前版本过老，直接覆盖安装的原因。今天卸载重装软件之后功能正常，包括搜索按钮和图片加载
