### ISSUE TITLE
关于没法下载图片的问题，显示代码rxhttp与okhttp等

### ISSUE THREAD

**Issue by himetuki** [CeuiLiSA/Pixiv-Shaft#493]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.23

### Android system version

harmony 2.0

### Device model

p30pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.下载图片

2.没法下载

### Expected behavior / 期望行为

正常下载

### Actual behavior / 实际行为

报错，下载错误，显示：
**下载失败，原因：<------rxhttp/2.7.3 okhttp/4.4.1 request end ------>
rxhttp.wrapper.exception.HttpStatusCodeException: GET http://210.140.92.141.img-original**

### Other details / 其它细节

下载管理和《正在下载》页面没有预览图（？其他细节），用的校园网，但是之前下载都正常，本来是3.2.21，以为是版本原因，就更新一下，发现还是有问题。改用电信流量也是一样。看图正常，下载失败

**Comment by sunbeams001** [comment]
基本上这种问题都是代理质量较差或使用人数太多导致的，考虑更换尝试
仅在官方客户端相同网络环境下完全正常时考虑是本应用问题
