### ISSUE TITLE
瀑布流很好用，就是能不能加个页码跳转功能？

### ISSUE THREAD

**Issue by cmmdwl** [CeuiLiSA/Pixiv-Shaft#495]
每一次回看收藏时候，突然想看某些收藏的老图，才发现要下滑翻好久才能翻回去，网页本身有翻页功能，但是好像手机app都不喜欢做这个功能？

**Comment by sunbeams001** [comment]
手机API和网页不是一套

**Comment by CeuiLiSA** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/32817377/223901469-8952c9e7-04fd-406a-8b6c-db197bb8281f.png">
想翻到指定的那一页，需要知道那一页的第一个作品id，现在看来是做不了

**Comment by cmmdwl** [comment]
我有一个思路，不知道行不行，就是加个快捷键，例如下滑20秒，这样可以避免手工下滑太久
