### ISSUE TITLE
增加自定义图片源功能

### ISSUE THREAD

**Issue by amokiel** [CeuiLiSA/Pixiv-Shaft#497]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

发现默认开启的直连速度似乎不是很快，另外pixivcat国内好像已经无法连接。可以考虑提供个自定义图片源的选项，那样就可以用i.pixiv.re之类的进行直连，可能体验会更好一些。多谢开发者，辛苦啦！

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by sunbeams001** [comment]
目前最新版用的就是re，虽然写的是cat
