### ISSUE TITLE
首页（推荐页）推荐个性化 R18 内容（类似于网页 R-18 按钮，非设置中的R页面）

### ISSUE THREAD

**Issue by dwcjgh** [CeuiLiSA/Pixiv-Shaft#499]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

我的现状：
· R18 个性化推荐在 网页 登录账号后推荐页点击按钮「R-18」可正常显示
· R18 在 Shaft 中通过搜索可以搜到，动态标签页也可以看到，证明设置是没问题的
· 首页（推荐页）不推荐 R18（漏三点）内容
· Shaft 提供的功能「APP 主页显示 R 页面」和 网页中「R-18」按钮的效果不同，不是个性化的推荐作品
· 已确认检查过 F&Q 中的「R18 作品不显示时，检查流程」以及「Shaft设置-常规-默认过滤R18内容为关闭状态」

我的问题是希望在首页（推荐作品抽屉页）瀑布流中推荐个性化的 R-18 内容，类似于网站上的「R-18」按钮那样，而非软件中的「R-18 排行榜」
我认为软件应该是已经有这个功能的，奈何花时间探索了仍然没发现，首页推荐没有露三点的内容不清楚是我操作的问题，还是没有做这个功能，感谢阅读、回复以及给我指导！

————————
下载官方 app 验证是否有这个功能后，首页插画抽屉页也是无 R-18 内容推荐，也同样验证了搜索中和「最新」页可以搜索到 R-18

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by sunbeams001** [comment]
官方App接口没有这个功能，网页和App不是一套接口，很多功能无法实现的

**Comment by dwcjgh** [comment]
好的，多谢，感谢回复
