### ISSUE TITLE
关于"相关图片"功能

### ISSUE THREAD

**Issue by Lyndisn** [CeuiLiSA/Pixiv-Shaft#501]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

 相关图片可以让我查看与之相关的图片，否则我只能通过搜索从新到旧或者从旧到新挨个查看，恳请增加这一功能使大家能够更好地查看自己想看的内容。

### Official support / 官方支持情况

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

是,pixez支持

**Comment by sunbeams001** [comment]
不是很懂你说的是哪个功能，查看作品的相关作品是有的

**Comment by Lyndisn** [comment]
感谢解惑，我想是我搞错了，我已经明白该怎么做了。

**Comment by Lyndisn** [comment]
感谢解惑，我想是我搞错了，我已经明白该怎么做了。
