### ISSUE TITLE
关于最近更新的方式

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#510]
1. 自从两年多前的3.2.0版本都是用github release bot搞的，现在突然改了？
2. 如果是alpha版本或者beta版本，可以把tag改为pre-release，像是3.2.2-beta一样

**Comment by LoxiaLiSA** [comment]
1.没有改，是这两天不规范。后面改成原先规范的样子 （我真不知道我们之前用的这个这个github release bot哈哈哈）
2.加了新feature的（不稳定）版本会加上标签

**Comment by CeuiLiSA** [comment]
ok

**Comment by CeuiLiSA** [comment]
还请 @sunbeams001 大佬协助一下 @LoxiaLiSA , 不太清楚如何通过github release bot 发布一个版本

**Comment by sunbeams001** [comment]
推送发布commit（就是确定要发布的版本号之后）时附加一个版本tag，tag名称参考历史记录，会触发自动编译+生成apk

**Comment by CeuiLiSA** [comment]
好的谢谢啦，我试试&nbsp;


丘比特
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 上午10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [CeuiLiSA/Pixiv-Shaft] 关于最近更新的方式 (Issue #510)





 
推送发布commit（就是确定要发布的版本号之后）时附加一个版本tag，tag名称参考历史记录，会触发自动编译+生成apk

**Comment by sunbeams001** [comment]
推荐在master单独修改版本号并push，其他分支合并我忘了能不能触发了

**Comment by SodaWithoutSparkles** [comment]
我记得其他人做都是修改完所有要修改的东西之后，加一个占位commit，只修改一个版本号文件。就是最后的这个push附带了tag

**Comment by LoxiaLiSA** [comment]
> 我记得其他人做都是修改完所有要修改的东西之后，加一个占位commit，只修改一个版本号文件。就是最后的这个push附带了tag
> 
> P.S. CeuiLiSA 和 LoxiaLiSA 是不是同一个人？

好的，下次有更新我先自己试试这么push看行不行。
是一个人，是公司小号
