### ISSUE TITLE
ai榜单

### ISSUE THREAD

**Issue by ODtian** [CeuiLiSA/Pixiv-Shaft#515]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

在r界面添加ai榜单

### Official support / 官方支持情况

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by CeuiLiSA** [comment]
这功能在v3.3.4做好了，可以去release页面下到这个版本
