### ISSUE TITLE
作品大图页的双击放大

### ISSUE THREAD

**Issue by ATFmxyl** [CeuiLiSA/Pixiv-Shaft#518]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.2

### Android system version

13

### Device model

Redmi K40

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

点击作品大图详情页
双击屏幕

### Expected behavior / 期望行为

双击放大一点,再次双击再提高放大比列,第三次双击缩放回无放大状态

双击放大（长/宽适应）后可能还可以继续双指放大，前提是原图确实够大

### Actual behavior / 实际行为

图片直接被放大到最大

**Comment by CeuiLiSA** [comment]
修了。可以下载 3.3.4 pre-release 版本试一下

**Comment by ATFmxyl** [comment]
> 修了。可以下载 3.3.4 pre-release 版本试一下

好的,但是3.3.4不是两天前发布的吗?

**Comment by LoxiaLiSA** [comment]
这个release的信息和附件可以一直更新的，现在下的apk就是刚传的apk。

**Comment by ATFmxyl** [comment]
> 这个release的信息和附件可以一直更新的，现在下的apk就是刚传的apk。

好的,谢谢😀

**Comment by ATFmxyl** [comment]
> 这个版本的信息和附件可以直接更新的，现在下面的apk就是刚传的apk。

测试了一下,只双击放大了第一次,再次双击就缩放回正常大小了,没有进行二次放大,不过放大的倍数确实没有一下子放大很大了

**Comment by LoxiaLiSA** [comment]
> > 这个版本的信息和附件可以直接更新的，现在下面的apk就是刚传的apk。
> 
> 测试了一下,只双击放大了第一次,再次双击就缩放回正常大小了,没有进行二次放大,不过放大的倍数确实没有一下子放大很大了

哈喽，是这样的。双击图片被放大到2x，这个时候你可以继续用双指捏合伸缩继续放大到3x，也可以直接双击缩放回原样。

**Comment by ATFmxyl** [comment]
> > > 这个版本的信息和附件可以直接更新的，现在下面的apk就是刚传的apk。
> > 
> > 
> > 测试了一次，只双击放大了第一次，再双击就放回正常大小了，没有进行第二次放大，不过放大的倍数确实没有下一次放大了
> 
> 哈哈，是这样的。双击图片被放大到2x，这个时候你可以继续用双指抓合拉伸继续放大到3x，也可以直接双击放大恢复原状。

好的
