### ISSUE TITLE
提高首页缩略图质量

### ISSUE THREAD

**Issue by amokiel** [CeuiLiSA/Pixiv-Shaft#521]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

首页两列的情况下，开启缩略图显示大图之后，缩略图依旧明显感觉到不少壁纸显示质量不太高，有一些壁纸存在明显模糊的情况。
不过，其它部分二级页面详情页原图这些壁纸，显示质量没有什么问题。
可否酌情考虑提高一些首页缩略图的清晰度呢。
主要是想到，大部分时候都是浏览首页板块，感兴趣的壁纸才会进入二级页面查看原图。这样的情况下，提高首页缩略图质量的效果应该是很明显的。
开发者辛苦了，感谢您的辛苦工作！

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by CeuiLiSA** [comment]
下最新的pre-release，应该是修好了。记得在设置页面打开“缩略图显示大图”这个开关

**Comment by LoxiaLiSA** [comment]
多少要写点公司的代码了家人们，在上班呢
