### ISSUE TITLE
默认私人收藏没应用到小说

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#522]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.2.23

### Android system version

13

### Device model

Poco x4 gt

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1. 在设置>个人化里启用"添加收藏默认私人收藏"
2. 如有需要重启app
3. 收藏任意插画
4. 可见插画是进私人收藏的
5. 收藏任意小说
6. 可见小说是进 **公开收藏** 的

### Expected behavior / 期望行为

行为和插画保持一致

### Actual behavior / 实际行为

行为不一致，详情见复现步骤

**Comment by SodaWithoutSparkles** [comment]
更新到3.3.4也是一样

**Comment by SodaWithoutSparkles** [comment]
对于关注画师也是同样问题

**Comment by CeuiLiSA** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/releases/tag/v3.3.4  可以了

**Comment by SodaWithoutSparkles** [comment]
大哥，pre-release不是这样用的啊，至少改了release apk之后也要把release的changelog改掉。

或者可以用release candidates或者hotfix的形式出一个新release。release candidates的用法大概是有些新功能确定会到下一个版本了，而且距离下一个版本很近了，那就拿下一个版本号加上rc，例如`v3.3.5-rc1` `v3.3.5-rc2`

Hotfix 是有大bug要尽快patch掉，因为影响到很多人而且有重大使用上的问题。

Alpha 版和 beta 版都是测试版，alpha 更为不稳定。但也不是保持同一个版本号换源的。

<details>
  <summary>Wikipedia上关于版本号的说明</summary>
## Pre-alpha
有時候軟體會在Alpha或Beta版本前先釋出Pre-alpha版本。一般而言相對於Alpha或Beta版本，Pre-alpha版本是一個功能不完整的版本。

## Alpha
Alpha版本仍然需要測試，其功能亦未完善，因為它是整個軟體釋出周期中的第一個階段，所以它的名稱是「Alpha」，希臘字母中的第一個字母「α」。

Alpha版本通常會送到開發軟體的組織或某群體中的軟體測試者作內部測試。在市場上，越來越多公司會邀請外部客戶或合作夥伴參與其測試。這令軟體在此階段有更大的可用性測試。

在測試的第一個階段中，開發者通常會進行白盒測試。其他測試會在稍後時間由其他測試團體以黑盒或灰盒技術進行，不過有時會同時進行。

## Beta
Beta版本是軟件最早對外公開的軟體版本，由公司外的第三方開發者和業餘玩家等參與公眾測試。 因為是Alpha的下一個階段，所以為希臘字母的第二個字Beta (β)。 一般來說，Beta包含所有功能，但可能有一些已知問題和較輕微的程序錯誤（BUG），要進行除錯（debug）。Beta版本的測試者通常是開發軟體的組織的客戶，他們會以免費或優惠價錢得到軟體。Beta版本亦作為測試產品的支援和市場反應等。

其他情況不同企業有不同的稱法，例如微軟曾以Community Technology Preview（簡稱CTP，中文稱為「社群技術預覽」）為發佈軟體的測試版本之一，微軟將這個階段的軟體散佈給有需要先行試用的使用者或廠商，並收集這些人的使用經驗，以便作為進一步修正軟體的參考。

## Release Candidate
Release Candidate（簡稱RC）指可能成為最終產品的候選版本，如果未出現問題則可釋出成為正式版本。在此階段的產品通常包含所有功能、或接近完整，亦不會出現嚴重問題。

多數開源軟件會推出兩個RC版本，最後的RC2則成為正式版本。閉源軟件較少公開使用，微軟公司在Windows 7上應用此名稱。蘋果公司把在這階段的產品稱為「Golden Master Candidate」（簡稱GM Candidate），而最後的GM即成為正式版本。而 iOS 自 14.2 開始亦採用 RC 稱呼處於此階段的版本狀態。

## 穩定版（Stable）
穩定版本來自預覽版本釋出使用與改善而修正完成，通常是初始版本進行幾個小更新後的版本。為目前所使用的軟件在符合需求規格的硬件與操作系統中運行不會造成嚴重的不相容或是硬件衝突，其已受過某定量的測試無誤後所釋出者。

</details>
