### ISSUE TITLE
按钮画风不合...?

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [CeuiLiSA/Pixiv-Shaft#523]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

自从3.3.0以来，按钮的画风好像和整体界面不合。新按钮是类似霓虹灯还是cyberpunk那种，不切合整体UI平面化的设计。

如果有一个选项调回之前那样就好了

### Official support / 官方支持情况

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

Yes

**Comment by CeuiLiSA** [comment]
app整体设计正在向新的风格过渡

**Comment by SodaWithoutSparkles** [comment]
换画风可是大事啊，所以能加一个选项退回就设计风格吗？

**Comment by CeuiLiSA** [comment]
大概会长这样 - https://github.com/CeuiLiSA/Pixiv-Slinky/releases/tag/v0.0.4
不会加开关换新旧风格

**Comment by SodaWithoutSparkles** [comment]
那新风格怎么会在旧app出现的🤔

**Comment by LoxiaLiSA** [comment]
现在有点两难。旧项目功能太多，历史代码太难维护改起来很麻烦。

新项目功能只有乞丐版只能说能用，但是代码改起来很惬意，没任何包袱，就像是打好了地基，加什么都很简单

所以，现在是把Shaft的功能移植到新app里呢，还是把新app的代码和风格apply到Shaft里呢

暂时选了后者

**Comment by SodaWithoutSparkles** [comment]
还是用java写吗？

**Comment by LoxiaLiSA** [comment]
0 java了，只有一个activity，全按谷歌标准来的

**Comment by SodaWithoutSparkles** [comment]
Golang 还是dart?

**Comment by LoxiaLiSA** [comment]
kotlin呀
