### ISSUE TITLE
调整pixivision样式

### ISSUE THREAD

**Issue by amokiel** [CeuiLiSA/Pixiv-Shaft#527]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

pixivision目前似乎是网页形式，有时候会连接不稳定，体验不是太好。可以调整一下，和app样式保持一致，不再使用网页样式提供内容。
多谢，辛苦了！

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by LoxiaLiSA** [comment]
之前尝试做过，强行用jsoup 从网页里把插画列表扒拉出来了，但是做到最后发现，网页里的插画数据结构和app的插画结构居然不一致，还得一个个转一下，就放弃了。
如果有类似的api支持，当然是能做，现阶段确实是没有（现阶段只有pixivision的列表有api，点进去就是个网页，网页里的信息就没有api支持了）

**Comment by LoxiaLiSA** [comment]
嗯嗯，已经看到那个问题啦，还在想怎么解决才更有效一点
