### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by NEWCPT** [CeuiLiSA/Pixiv-Shaft#528]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.4

### Android system version

10

### Device model

redmi note7Pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

开启代理情况下
shaft内 登录
点击右上角打开网页
登录pixiv账号
获取api
跳转shaft
loading resources
卡在加载
退出加载页面
error

### Expected behavior / 期望行为

网页端可以打开pixiv
pix-ez可以正常登录

### Actual behavior / 实际行为

卡在loading resources

### Other details / 其它细节

![Screenshot_2023-03-26-10-38-25-834_ceui lisa pixiv](https://user-images.githubusercontent.com/52870721/227752238-9634af9b-4345-4bf7-b9b8-a039364adfff.jpg)
![Screenshot_2023-03-26-10-38-11-286_android](https://user-images.githubusercontent.com/52870721/227752243-70198c8d-0c52-4cb8-bb2f-c38115b878d3.jpg)
![Screenshot_2023-03-26-10-38-11-286_android](https://user-images.githubusercontent.com/52870721/227752392-bbe184e0-f297-4ed2-8647-ae1f7c18d4b7.jpg)
![Screenshot_2023-03-26-10-37-32-208_ceui lisa pixiv](https://user-images.githubusercontent.com/52870721/227752394-acfb4651-b508-41d4-9d6a-49a982250033.jpg)

**Comment by CeuiLiSA** [comment]
老实说我有时候也遇到这个问题，但是一般换个梯子的节点或者换移动数据来访问就解决了（。）

**Comment by SodaWithoutSparkles** [comment]
在墙外用官方app都登录不了，最近加载特别慢
