### ISSUE TITLE
dalao现在接口开源🐎？？？

### ISSUE THREAD

**Issue by zjiale** [CeuiLiSA/Pixiv-Shaft#53]

**Comment by CeuiLiSA** [comment]
这是官方的接口，自己抓包得到的，应该不算开源，只算能用

**Comment by zjiale** [comment]
> 这是官方的接口，自己抓包得到的，应该不算开源，只算能用

就是之前你抓包的那些接口还提供给其他人用吗？

**Comment by CeuiLiSA** [comment]
可以的哈，你随意发挥


 
---原始邮件---
发件人: "zjiale"<notifications@github.com&gt;
发送时间: 2020年1月14日 17:46:09
收件人: "CeuiLiSA/Pixiv-Shaft"<Pixiv-Shaft@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"CeuiLiSA"<fatemercis@qq.com&gt;;
主题: Re: [CeuiLiSA/Pixiv-Shaft] dalao现在接口开源？？？ (#53)


 
这是官方的接口，自己抓包得到的，应该不算开源，只算能用
  
就是之前你抓包的那些接口还提供给其他人用吗？

**Comment by zjiale** [comment]
大佬，我还想问个问题就是我看到您代码里面有个httpdns，是请求的时候再经过里面的地址再转发过去吗？我在postman把地址设置到代理上面好像也没效果
