### ISSUE TITLE
即使打开原图，大图界面的图片与下载后的仍有差别

### ISSUE THREAD

**Issue by Silicon7921** [CeuiLiSA/Pixiv-Shaft#538]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.5(260)

### Android system version

HarmonyOS 2.0.0

### Device model

Huawei VRD-W10

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.在设置打开所有原图选项
2.选择任意作品 打开大图
3.在图片背景区域（色彩相对单一的区域）观察到类似彩虹的条纹，类似图片压缩后产生的现象
4.下载该图片，用其他图片查看器查看 未观察到以上现象

### Expected behavior / 期望行为

在大图界面查看到的图片效果与下载后相同，没有如同压缩后的彩色条纹

### Actual behavior / 实际行为

大图界面即使打开了原图也有彩色的条纹，怀疑有质量损失
下载后的图片都没有类似现象，质量完好无损

### Other details / 其它细节

1. 这个issue是我代替别人提交的
2. 对比图发出来大概也会被压缩 就不发了
3. 图片在pixiv官网没有这个问题 所以应该是软件问题

**Comment by MHsugar** [comment]
这个是在软件二级详情页查看效果![软件截图](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/134122829/beb080d6-c9a9-48cc-b71e-f4d2bc5491e4)
这个是下载下来用其他软件查看的效果![其他看图软件截图](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/134122829/0cc39b38-1097-4b6c-933a-e072ff0b7a34)

**Comment by Discut** [comment]
下面的是开启了32位色彩支持？

**Comment by Silicon7921** [comment]
> 下面的是开启了32位色彩支持？

不是。只是单纯的APP内查看和下载后查看的区别，没有改动设置

**Comment by Silicon7921** [comment]
> > > 下面的是开启了32位色彩支持？
> > 
> > 
> > 不是。只是单纯的APP内查看和下载后查看的区别，没有改动设置
> 
> 我的意思是，它的这个预览组件是不是不支持32位色彩。Tachiyomi打开32位色彩支持后能够减少色带，做到上图的效果。

这就不知道了。甚至这张图片有没有32位色彩都不知道，因为是个ai图
我也不知道APP支不支持32位色彩

**Comment by CeuiLiSA** [comment]
fixed
