### ISSUE TITLE
Unable to view the FAQ translated into Japanese

### ISSUE THREAD

**Issue by aiueonicked** [CeuiLiSA/Pixiv-Shaft#541]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

latest version

### Android system version

13

### Device model

Xiaomi 11t pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.Open https://github.com/CeuiLiSA/Pixiv-Shaft/
2.Go to readme.md
3.Click on "日本語(日文)" or visit https://github.com/CeuiLiSA/Pixiv-Shaft/blob/README/README.ja.md

### Expected behavior / 期望行为

The link should be displayed

### Actual behavior / 实际行为

It says "Cannot find a valid ref in README/README.ja.md"

### Other details / 其它细节

The link is not https://github.com/CeuiLiSA/Pixiv-Shaft/blob/README/README.ja.md, 
it should be https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/README/README.ja.md.

**Comment by CeuiLiSA** [comment]
fixed

**Comment by aiueonicked** [comment]
Thanks
