### ISSUE TITLE
我上不去了，求助

### ISSUE THREAD

**Issue by NEWCPT** [CeuiLiSA/Pixiv-Shaft#544]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

latest version

### Android system version

Android 10.0

### Device model

redmi note7Pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

拉取登录权限后无反应。

### Expected behavior / 期望行为

正常拉取登录权限

### Actual behavior / 实际行为

无法登陆

### Other details / 其它细节

其它

**Comment by NEWCPT** [comment]
Anbody here?

**Comment by NEWCPT** [comment]
anybody here?

**Comment by Dome-World** [comment]
> anybody here?

我也出现了这个问题，无法登录，不知道原因是什么 @CeuiLiSA

**Comment by Dome-World** [comment]
> anybody here?

换了个代理就登上了
