### ISSUE TITLE
小说中按钮失效

### ISSUE THREAD

**Issue by ding667** [CeuiLiSA/Pixiv-Shaft#55]
![S00117-13253022](https://user-images.githubusercontent.com/48525679/72586487-edd93200-392c-11ea-9326-6e5c916ce8c3.jpg)
上一张下一张按钮无效，确定在网页版是有上一张下一张的

**Comment by CeuiLiSA** [comment]
功能还没做，暂时就留了俩按钮

**Comment by CeuiLiSA** [comment]
做好了，下版本更新
