### ISSUE TITLE
图片双击缩放

### ISSUE THREAD

**Issue by huajideshutiao** [CeuiLiSA/Pixiv-Shaft#550]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.6

### Android system version

安卓13

### Device model

k50

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

在长图二级详情页双击
![Screenshot_2023-07-03-22-02-06-356_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/38980554/1a733b6b-fccf-4581-b41d-60164449d183)

boom
![Screenshot_2023-07-03-22-02-13-036_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/38980554/d30270f8-2149-42f1-b36a-5376ae733308)

### Expected behavior / 期望行为

至少能适应宽度

### Actual behavior / 实际行为

6

### Other details / 其它细节

虽然确实有个关于长图的issue，但是没包括点击后适应宽度

**Comment by CeuiLiSA** [comment]
fixed
