### ISSUE TITLE
 无法加载图片

### ISSUE THREAD

**Issue by yohar2b** [CeuiLiSA/Pixiv-Shaft#559]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.6（262）

### Android system version

emui10

### Device model

huawei nova 5 pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.进入画师主页（关注列表/搜索进入）
2.进入作品详情页，详情页图片未能加载出来，也无法在详情页下载原图
![Screenshot_20230821_211656_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/88493352/844544d7-cfdc-40f0-ad03-54d6a0eaa450)

3.有些时候画师主页的部分作品也无法加载出来

### Expected behavior / 期望行为

能尽快解决就行

### Actual behavior / 实际行为

app不更新了吗？

**Comment by hankeigi** [comment]
同样的情况，最近开始有的，只是我用的是直连加pixivcat。

**Comment by 30000lightyears** [comment]
实测pixivcat关闭后加载正常，估计是pixivcat的服务出问题了
