### ISSUE TITLE
好像我的热度排序会自动屏蔽r18

### ISSUE THREAD

**Issue by a2435300833** [CeuiLiSA/Pixiv-Shaft#56]

**Comment by a2435300833** [comment]
比如，我输入ベルファスト(アズールレーン)标签会有R-18的内容显示，但是进行热度排序就后，显示的就是不含R-18的

**Comment by CeuiLiSA** [comment]
是的，因为热多排序实际上是把一个会员账号的排序结果给你看。我前段时间把自己会员账号的R18给关了，所以大家就看不到了。
为什么关R18，因为google play看到有些色情内容把我下架了。。。

**Comment by a2435300833** [comment]
原来如此，我还以为是程序bug了
