### ISSUE TITLE
小说阅读问题

### ISSUE THREAD

**Issue by sepicoderw** [CeuiLiSA/Pixiv-Shaft#579]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.4(258)

### Android system version

xiaomi hyperos

### Device model

redmi k50 ultra

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1、点击任意一本小说_
2、app弹出提示“您所指定的端点不存在”

### Expected behavior / 期望行为

显示出小说内容

### Actual behavior / 实际行为

app弹出提示“您所指定的端点不存在”

**Comment by SovietBall** [comment]
隔壁pixez也是如此……感觉可能换接口了（？）

**Comment by YinChenming** [comment]
一模一样的情况，并且我开全局梯子后就一直转圈圈，没有下载流量

**Comment by jainylord** [comment]
我也遇到了一样的问题

**Comment by SigmaHarmonizer** [comment]
关闭直连使用自己的代理，也是一样的问题（看图正常）

**Comment by Cairre520** [comment]
看小说显示你指定的端口不存在

**Comment by LoxiaLiSA** [comment]
在修了

**Comment by DiLiuNEUexpresscompany** [comment]
肉身在海外，关闭代理也有问题

**Comment by Cairre520** [comment]
> 在修了

没事，慢慢来

**Comment by DiLiuNEUexpresscompany** [comment]
> 在修了

感谢，慢慢来

**Comment by CeuiLiSA** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/pull/580

fixed

**Comment by CeuiLiSA** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/releases/tag/v3.3.6

**Comment by sepicoderw** [comment]
> #580
> 
> fixed

感谢大佬

**Comment by sepicoderw** [comment]
感谢大佬
