### ISSUE TITLE
部分小说打开空白无文字

### ISSUE THREAD

**Issue by horryruo** [CeuiLiSA/Pixiv-Shaft#586]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.3.8

### Android system version

14

### Device model

vivo

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

id=21692020；id=21685472；

### Expected behavior / 期望行为

fix

### Actual behavior / 实际行为

none

**Comment by LoxiaLiSA** [comment]
下载github 最新的 release，昨天修好了

**Comment by horryruo** [comment]
确实，谢谢
