### ISSUE TITLE
评论区图片无法显示

### ISSUE THREAD

**Issue by Dome-World** [CeuiLiSA/Pixiv-Shaft#599]
### Acknowledgements / 确认事项

- [x] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.4.0

### Android system version

14

### Device model

redmi note12turbo

### Steps to reproduce / 复现步骤

随便打开一个图片的评论区，如117646626，发现出现空白评论

### Expected behavior / 期望行为

空白评论在网页上看了一下是图片，希望能显示出来

### Actual behavior / 实际行为

显示为空

**Comment by CeuiLiSA** [comment]
修了，google play 送审了

**Comment by CeuiLiSA** [comment]
https://github.com/CeuiLiSA/Pixiv-Shaft/releases/tag/v4.0.1
