### ISSUE TITLE
切换系统深色模式时崩溃

### ISSUE THREAD

**Issue by demolg** [CeuiLiSA/Pixiv-Shaft#60]
如题

**Comment by CeuiLiSA** [comment]
麻烦提供下手机/系统型号

**Comment by demolg** [comment]
@CeuiLiSA Redmi K20 Pro，用的是第三方ROM Havoc OS(Android 10)

**Comment by demolg** [comment]
@CeuiLiSA 这是刚刚切换深色模式时崩溃的的报告 https://del.dog/webittyhus

**Comment by CeuiLiSA** [comment]
看来只可以在切换到夜间模式之后，再打开APP或者杀掉APP重进了

**Comment by liqngyuqi** [comment]
您好，我能将您这款应用分享给更多人吗？

**Comment by CeuiLiSA** [comment]
> 您好，我能将您这款应用分享给更多人吗？

当然可以

**Comment by CeuiLiSA** [comment]
现在不崩溃了，但是还是不适配深色模式，。。

**Comment by CeuiLiSA** [comment]
已适配深色模式
