### ISSUE TITLE
该软件无法通过代理软件连接互联网

### ISSUE THREAD

**Issue by NpTIme** [CeuiLiSA/Pixiv-Shaft#600]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

4.0.1

### Android system version

12(LineageOS 19.1)

### Device model

xiaomi mix2s

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [X] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

在使用[NekoBox](https://github.com/MatsuriDayo/NekoBoxForAndroid)和[ClashMetaForAndroid](https://github.com/MetaCubeX/ClashMetaForAndroid)代理网络时, Shaft 不能通过代理连接网络, 且该情况在上一个版本未出现,其它代理软件未测试

我测试了两种情况:

1. 保留用户数据卸载旧版并重新安装
2. 不保留用户数据并重新安装

两种情况都有这个问题

### Expected behavior / 期望行为

如同上一个版本以及其它App一样通过代理连接网络

### Actual behavior / 实际行为

APP未使用代理连接网络,导致 App 不能正常使用

**Comment by huajideshutiao** [comment]
是不是你梯子的问题，我这可以
![Screenshot_2024-04-11-10-46-48-298_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/38980554/5c3611ad-61ac-4f5c-a937-d9a35e73f1de)
![Screenshot_2024-04-11-10-46-51-215_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/38980554/22594444-c851-4dd8-9520-94f296794aa3)

**Comment by NpTIme** [comment]
> 是不是你梯子的问题，我这可以
> ![Screenshot_2024-04-11-10-46-48-298_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/38980554/5c3611ad-61ac-4f5c-a937-d9a35e73f1de)
> ![Screenshot_2024-04-11-10-46-51-215_ceui lisa pixiv](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/38980554/22594444-c851-4dd8-9520-94f296794aa3)
> 

我回到旧版了，又能用了，新版无法代理旁。
你用的什么代理软件，shaft是在github下载的吗？

**Comment by huajideshutiao** [comment]
> > 是不是你梯子的问题，我这可以
> > ![Screenshot_2024-04-11-10-46-48-298_ceui lisa pixiv](https://private-user-images.githubusercontent.com/38980554/321470268-5c3611ad-61ac-4f5c-a937-d9a35e73f1de.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM2MDgsIm5iZiI6MTcxMjg1MzMwOCwicGF0aCI6Ii8zODk4MDU1NC8zMjE0NzAyNjgtNWMzNjExYWQtNjFhYy00ZjVjLWE5MzctZDlhMzVlNzNmMWRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE2MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OGQ5MDBjMjUyZDU3YWZiMWEwODlmMTVmZjU4MWQ3NTY2MTRkNTVkZjk5MDNiZDI4NzAxNjhlMzMzMTYzNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.24ZFwYj_dVu0EDJ6rYbsgNCC1pf2COkvY9JbNx6YBHI)
> > ![Screenshot_2024-04-11-10-46-51-215_ceui lisa pixiv](https://private-user-images.githubusercontent.com/38980554/321470274-22594444-c851-4dd8-9520-94f296794aa3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM2MDgsIm5iZiI6MTcxMjg1MzMwOCwicGF0aCI6Ii8zODk4MDU1NC8zMjE0NzAyNzQtMjI1OTQ0NDQtYzg1MS00ZGQ4LTk1MjAtOTRmMjk2Nzk0YWEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE2MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMmYyNDczM2I1YTE3YzllMzEyYjc3ZjZlNzMwZTE3YzY4ZTNhMTJiNzk0MjQ2OWEyYTZmNDE5YzgzYzkyMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgKQ17aRjmu7ys30oE9_Mw1_4et53kHlojUwK_Q3gg4)
> 
> 我回到旧版了，又能用了，新版无法代理旁。 你用的什么代理软件，shaft是在github下载的吗？

我用的NekoBox 和openclash，配置文件有几个，都可以。shaft是最新的
