### ISSUE TITLE
希望能支持小说的追更列表功能

### ISSUE THREAD

**Issue by hzy132** [CeuiLiSA/Pixiv-Shaft#603]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

目前可以搜索阅读小说、添加书签、收藏小说，但还不能查看小说的追更列表，也不支持小说的单章内的阅读进度记录。

追更列表官方网页和app都支持，小说单章内阅读进度只有网页支持。

下面图片是官方网页和app的截图。
![IMG1](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/35918116/179f531e-988f-4e3c-9bde-549e4e3bc111)
![IMG2](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/35918116/5b7a1029-d78d-499b-ace4-fe34cb77893e)

### Official support / 官方支持情况

- [X] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

好像没有

**Comment by h4ckm310n** [comment]
我也有同样的需求，目前我正在尝试自己添加这部分功能

**Comment by whx9986** [comment]
追更功能并不完善，目前只能查看追更列表，并不能在软件中添加追更的小说，想要添加还是要去pixiv官方
![Screenshot_2025-01-03-14-00-31-899_ceui lisa pixiv](https://github.com/user-attachments/assets/9175ee8c-afb4-4df9-924a-7782fe204f88)
