### ISSUE TITLE
图片纵向展示列数超过2列时，首页图片高度未跟随宽度调整

### ISSUE THREAD

**Issue by ShadowPower** [CeuiLiSA/Pixiv-Shaft#606]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

3.4.1 (282)

### Android system version

14

### Device model

Xiaomi Pad 6 Max

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1. 拉出左侧抽屉，点击设置
2. 将“图片纵向展示列数”更改为4
3. 退出APP，重新打开，进入首页（或排行榜，我的收藏等界面）

### Expected behavior / 期望行为

在旧版本中（至少为1年前的版本），使用3、4列模式时，预览图的高度会跟随图片宽度缩放。
在当前版本中，使用3、4列模式时，预览图仍然使用2列时的高度展示。
因此，图片会显示为长条状，内容的左右两侧被裁切。

以下为期望行为截图：
![Screenshot](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/7625230/bf25a1aa-552c-440f-b86c-cdc1957a377d)

### Actual behavior / 实际行为

预览图的高度应随着列数改变而自动调整，以显示完整图片内容，和旧版本的行为一致。

以下为实际行为截图：
![Screenshot](https://github.com/CeuiLiSA/Pixiv-Shaft/assets/7625230/8da9f15e-03ad-4d7e-935c-196eeacec81c)

### Other details / 其它细节

期望行为的截图来自3.2.21(221)版本

**Comment by Dome-World** [comment]
在matepad11上复现此bug

**Comment by CeuiLiSA** [comment]
下最新的release 修好了
