### ISSUE TITLE
图片双击全屏，而不是简单的放大

### ISSUE THREAD

**Issue by ztchhhhh** [CeuiLiSA/Pixiv-Shaft#607]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

另一个第三方pixEZ图标打开双击不是放大而是全屏，就是图片如果是横着的，双击图片上下就会贴合屏幕的上下

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

### Is this feature supported by any other third-party pixiv app? / 第三方App是否支持

pixEZ支持

**Comment by CeuiLiSA** [comment]
确实是像你说的那样，是有优化空间的。

**Comment by CeuiLiSA** [comment]
我发了个新版本，可以用下面这个作品试试看二级详情页的放大功能

老婆们-年更 | 红白0v0 #Pixiv https://www.pixiv.net/artworks/97802718

**Comment by LoxiaLiSA** [comment]
还是要兼顾别的非极端比例图片的放大功能，就先这样了
