### ISSUE TITLE
关于热度搜索

### ISSUE THREAD

**Issue by Aisaka-t** [CeuiLiSA/Pixiv-Shaft#61]
热度搜索似乎又坏了，不知道为什么，开热度搜索后绝大部分图搜不到，而且排序似乎也不是按热度排的

**Comment by CeuiLiSA** [comment]
1.热度搜索的专用账户会员过期了
2.分发会员token的服务器过期了
3.我在武汉，翻墙工具都被封了，回上海之后处理

**Comment by Aisaka-t** [comment]
惨，注意安全，身体第一
