### ISSUE TITLE
看到空评论，点开他人主页小说漫画等按钮出现空白页

### ISSUE THREAD

**Issue by hongfengshu** [CeuiLiSA/Pixiv-Shaft#633]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

4.1.1

### Android system version

11

### Device model

LM -V500N

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [ ] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

如题

### Expected behavior / 期望行为

如题

### Actual behavior / 实际行为

如题

### Other details / 其它细节

如题

**Comment by LoxiaLiSA** [comment]
升级到最新版试试，应该是修了
