### ISSUE TITLE
商店被下架了吗

### ISSUE THREAD

**Issue by mashirozx** [CeuiLiSA/Pixiv-Shaft#65]
还有发布在其他地方吗？

**Comment by duzhaokun123** [comment]
又被下架了还行，为什么执意要在 Google play 上发布

**Comment by CeuiLiSA** [comment]
是被下架了，那就不发布了。。

**Comment by BCsl** [comment]
> 是被下架了，那就不发布了。。

好奇是为啥被下架了？

**Comment by duzhaokun123** [comment]
似乎又没有被下架了

**Comment by mashirozx** [comment]
@CeuiLiSA 大佬，要不release一下apk吧，每次自己打包好麻烦噢。。

**Comment by CeuiLiSA** [comment]
那我下次google play发版的时候顺便打个release吧，争取养成习惯，每次gplay发版，就发一个release
