### ISSUE TITLE
Google Play上无法获取到这款应用

### ISSUE THREAD

**Issue by Aqua-Chen** [CeuiLiSA/Pixiv-Shaft#652]
### Acknowledgements / 确认事项

- [x] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

Google Play上无法搜索到这款应用，通过描述页的链接进入提示：”抱歉，在此服务器上找不到所请求的网址“

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by CeuiLiSA** [comment]
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/5c7a7af0-8566-441b-95f7-fe13a9bcc45c">

**Comment by CeuiLiSA** [comment]
解决了，现在可以在 play store 里面看到了
