### ISSUE TITLE
shaft自带pixiv相关网站ip失效

### ISSUE THREAD

**Issue by BUnipendix** [CeuiLiSA/Pixiv-Shaft#664]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

4.1.5

### Android system version

12

### Device model

MATE60 PRO

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1. 启动直连
2. HTTP 421报错

### Expected behavior / 期望行为

开启直连能正常连接

### Actual behavior / 实际行为

开启直连后报错HTTP421

### Other details / 其它细节

我找到其它仓库的相关问题的修复：https://github.com/URenko/Accesser/pull/208

**Comment by OrigamiShido** [comment]
+1,同样情况

**Comment by CeuiLiSA** [comment]
下最新的release
