### ISSUE TITLE
关于小说标签

### ISSUE THREAD

**Issue by wiwgwgwi** [CeuiLiSA/Pixiv-Shaft#665]
能否麻烦作者大大加个切换，小说标签和插画一样的标签(跟老版一样)，新版小说有一些颜色看不清，只是想看清这篇文章的标签混着五颜六色的标签看着很累之前是用旧版挺着的，现在连不上更新成4.2.0没办法才来提意见的(இωஇ)，不知道怎么表达，如果冒犯了您请见谅

**Comment by CeuiLiSA** [comment]
我理解你的意思了，我会出一版折中的方案和设计。

**Comment by bai12123** [comment]
大佬，我已经更新到v4.2.1版本。标签看着没有多大变化，很多颜色容易视觉疲劳，并且还有些标签漏翻译，求给个按钮回到旧版样式。另外麻烦看下 #657  ，他的一些请求刚好我也很需要。求求了 @CeuiLiSA

**Comment by CeuiLiSA** [comment]
下载最新版的release试试
