### ISSUE TITLE
小说标签问题

### ISSUE THREAD

**Issue by conanaa** [CeuiLiSA/Pixiv-Shaft#668]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### What feature should be added? / 需要加上什么功能

小说标签功能需要优化并且能否进行旧版选择
目前1颜色混乱看不清 2翻译不通顺甚至误翻译 3部分标签对比原版显示缺失 4带有颜色数字编号不能去除

### Official support / 官方支持情况

- [ ] Is this feature supported by the official pixiv app? / 官方App是否支持

**Comment by bai12123** [comment]
作者在releases/v4.2.1中发布了2个安装包。其中PixShaft_4.2.1.apk确实出现了你所说的4个小说标签问题。另一个shaft_v4_2_1.apk
还是有“颜色混乱看不清”“好些个标签未翻译，漏翻译”的问题。旧版本的蓝底白字看起来更舒服，标签也没有出现漏翻译情况。

求大佬解决一下，谢谢谢谢了 @CeuiLiSA

**Comment by CeuiLiSA** [comment]
用最新的 v4.2.2 release 试试

**Comment by CeuiLiSA** [comment]
未翻译，漏翻译   能不能提供一个小说id 或者小说链接
