### ISSUE TITLE
目测热度排序失效

### ISSUE THREAD

**Issue by Weariz** [CeuiLiSA/Pixiv-Shaft#67]
之前用的还好好的，萌新今天试了一下发现热度排序已经失效???
![Screenshot_2020-02-24-15-34-52-611_ceui lisa pixiv](https://user-images.githubusercontent.com/41582915/75135048-3a2d4400-571b-11ea-932c-56066531234d.png)
p1是关键词“楊貴妃(Fate) 5000users入り”普通搜索的结果
![Screenshot_2020-02-24-15-36-42-376_ceui lisa pixiv](https://user-images.githubusercontent.com/41582915/75135123-7f517600-571b-11ea-9735-a9d2b97bc1dc.png)
p2是热度排序之后的结果
不难看出来两者是一样的，后来又试了几个还是这样，得出结论热度排序功能好像鸽了，求大佬修复一下，蠢新感激不尽。

**Comment by CeuiLiSA** [comment]
[https://github.com/CeuiLiSA/Pixiv-Shaft/issues/66](url)

**Comment by Weariz** [comment]
大佬今天好像那个一直在转圈，干脆就没有显示

**Comment by railannad** [comment]
> [https://github.com/CeuiLiSA/Pixiv-Shaft/issues/66](url)

这个地址不存在，搜索#66也没有结果，似乎是被删掉了

**Comment by duzhaokun123** [comment]
@railannad #66 是旧原因, 新原因是 #94
