### ISSUE TITLE
图片显示为固定的几张

### ISSUE THREAD

**Issue by m55tqe** [CeuiLiSA/Pixiv-Shaft#670]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

4.2.1

### Android system version

鸿蒙4.2.0

### Device model

华为p50pro

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [ ] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [X] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

1.打开软件

### Expected behavior / 期望行为

能正常浏览图片，包括首页和动态

### Actual behavior / 实际行为

几乎所有图片都是固定的几张，而且还不是我关注的作者的
![Screenshot_20241221_142141_ceui lisa pixiv](https://github.com/user-attachments/assets/db46922b-02c7-4dca-8d04-527ddc76cf32)
![Screenshot_20241221_142146_ceui lisa pixiv](https://github.com/user-attachments/assets/c8c5127d-24d4-488e-bf56-3891eddc22ae)
![Screenshot_20241221_142149_ceui lisa pixiv](https://github.com/user-attachments/assets/f5b92c84-5e7d-47a1-8200-c69d9dd081c9)
![Screenshot_20241221_142153_ceui lisa pixiv](https://github.com/user-attachments/assets/7d1e31c5-038d-4ad3-9385-929b791dfaee)

**Comment by zeroofGitHub** [comment]
同样的状况只有自行代理可以正常
![Screenshot_20241221_150711](https://github.com/user-attachments/assets/e742b879-3bae-44f3-8e02-e681dd74bff3)
![Uploading Screenshot_20241221_150717.jpg…]()

**Comment by ruliang212** [comment]
同样的情况，也是这几张图片

**Comment by ruliang212** [comment]
> 同样的情况，也是这几张图片

并且在4.2.0版本也出现了这个问题，只要打开直连并使用pixivCat代理就一定会出现这个问题

**Comment by CeuiLiSA** [comment]
用最新的release试下

**Comment by m55tqe** [comment]
> 用最新的release试下

抱歉，4.2.2的动态里还是有问题。。。

**Comment by CeuiLiSA** [comment]
我明天再看看动态那里是啥情况，补一个版本，今天下班了





------------------ 原始邮件 ------------------
发件人: m55tqe ***@***.***&gt;
发送时间: 2024年12月23日 19:41
收件人: CeuiLiSA/Pixiv-Shaft ***@***.***&gt;
抄送: CeuiLiSA ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [CeuiLiSA/Pixiv-Shaft] 图片显示为固定的几张 (Issue #670)





  
用最新的release试下
  
抱歉，4.2.2的动态里还是有问题。。。
