### ISSUE TITLE
可以加入屏蔽R18功能吗

### ISSUE THREAD

**Issue by NakataniIku** [CeuiLiSA/Pixiv-Shaft#68]
如题

**Comment by CeuiLiSA** [comment]
暂时不知道怎么屏蔽

**Comment by duzhaokun123** [comment]
不能按标签品屏蔽吗

**Comment by CeuiLiSA** [comment]
很多抓奶漏胸撅屁股的，标签里没有R18，就一个“少女”，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杜兆琨"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 晚上9:15
收件人: "CeuiLiSA/Pixiv-Shaft"<Pixiv-Shaft@noreply.github.com&gt;; 
抄送: "863043461"<fatemercis@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [CeuiLiSA/Pixiv-Shaft] 可以加入屏蔽R18功能吗 (#68)




不能按标签品屏蔽吗

**Comment by CeuiLiSA** [comment]
@duzhaokun123  你这边有没有什么可行的方案，可以筛选掉R18作品的？

**Comment by duzhaokun123** [comment]
@CeuiLiSA  未成年账户都解决不了问题

**Comment by duzhaokun123** [comment]
@CeuiLiSA 按标签至少能屏蔽一些

**Comment by duzhaokun123** [comment]
平时少看些奇怪的东西，首页推荐这些会少些

**Comment by NakataniIku** [comment]
@duzhaokun123 按条件查找还是会混进去不少

**Comment by duzhaokun123** [comment]
@NakataniIku 这有什么办法，没有任何明显的标记指明是R-18内容，难不成让应用根据图片判断

**Comment by CeuiLiSA** [comment]
今天上班没事干撸了一个按标签屏蔽的功能，自己手动加点标签可以实现屏蔽不需要的内容
