### ISSUE TITLE
推荐页可以加一个返回顶部刷新嘛

### ISSUE THREAD

**Issue by SmartEasonXia** [CeuiLiSA/Pixiv-Shaft#69]
比如我新收藏了一些图 那新推荐的图会在瀑布流里面更新吗 还是需要到顶部来新一轮的刷新？

**Comment by CeuiLiSA** [comment]
你在推荐页面点了红心，不刷新而只是一直往下滑加载更多的话，
说实话我不确定新出来的图是不是根据你刚刚点的红心做的推荐。
保险起见，我做了一个点击底部导航栏可以直达列表顶部刷新页面的效果。
这样子新刷出来的页面应该是基于你点的收藏做的推荐
