### ISSUE TITLE
bug 检查 License 时崩溃

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#71]
应用版本: 1.3.0

Android 版本: LineageOS 16(Android 9)

日志: https://pan.baidu.com/s/1LJ9DwiwnmrLbioSyjexkeg 提取码:791o

我感觉这是 AboutLibraries 的问题，因为我的应用用了也崩溃

但为什么之前的版本没有崩溃

**Comment by CeuiLiSA** [comment]
。。你是真的勤快，明天搞吧

**Comment by CeuiLiSA** [comment]
<style name="AppTheme" parent="QMUI.Compat.NoActionBar">

我前几天为了用腾讯的QMUI，就把Appttheme的parent换成QMUI的了。导致AboutLibraries崩溃
把apptheme的parent换回Theme.MaterialComponents.xxxxxxxxxx即可正常打开license页面
如Theme.MaterialComponents.Light.NoActionBar.Bridge
