### ISSUE TITLE
热度排序按钮变灰色了

### ISSUE THREAD

**Issue by xushet** [CeuiLiSA/Pixiv-Shaft#72]

**Comment by xushet** [comment]
![Screenshot_20200309-003009](https://user-images.githubusercontent.com/34502902/76166920-5d390880-619d-11ea-8b2e-f3e0fb488916.jpg)

**Comment by CeuiLiSA** [comment]
因为用作热度排序的服务器被GFW ban了，就先把这个功能下线了。
