### ISSUE TITLE
图片详情页(查看单图)横屏闪退

### ISSUE THREAD

**Issue by GHOSTagw** [CeuiLiSA/Pixiv-Shaft#73]
机型:Honor V9 Android 9

**Comment by CeuiLiSA** [comment]
新版本应该是解决了这个问题啊。。你用的app是什么版本呢

**Comment by GHOSTagw** [comment]
play store上下载的1.4.0，平常看图横竖屏是没啥问题，放大单个图片后横屏闪退，还有横屏进入app的时候大概率闪退。
报错{" restrict ":[" Restrict is required "," Restrict contains invalid value "]}

> 
> 
> 新版本应该是解决了这个问题啊。。你用的app是什么版本呢

play store上下载的1.4.0，平常看图横竖屏是没啥问题，放大单个图片后横屏闪退，还有横屏进入app的时候大概率闪退。
报错{" restrict ":[" Restrict is required "," Restrict contains invalid value "]}

**Comment by CeuiLiSA** [comment]
感谢配合，找到问题了，下版本修复
