### ISSUE TITLE
下载不了带表情，也看不了带表情的GIF

### ISSUE THREAD

**Issue by CHEN127** [CeuiLiSA/Pixiv-Shaft#75]

**Comment by CeuiLiSA** [comment]
麻烦提供一个出现这个问题的作品id

**Comment by CHEN127** [comment]
79069649

**Comment by CHEN127** [comment]
> 麻烦提供一个出现这个问题的作品id

79963317，79069649，GIF看不了下载不了，其他不是GIF的图可以下载，但是会出现两个黑图两个正常图，看文件大小也不正常。

**Comment by CeuiLiSA** [comment]
实测是可以的，请问你账号在官网开启r18了吗，没开R18的账号是不可以看的，反之可以看

**Comment by CHEN127** [comment]
> 实测是可以的，请问你账号在官网开启r18了吗，没开R18的账号是不可以看的，反之可以看

开R18了，就是看不了下载不了文件名带表情的GIF。PIX-EZ没这个问题。

**Comment by CHEN127** [comment]
看了一下PIXEZ下载会把原来的文件名改成图片ID，应该是我的手机对图片名带表情支持不好

**Comment by CeuiLiSA** [comment]
好的，我看了下确实有的手机文件系统支持不了带表情的文件名，我做一些适配吧
