### ISSUE TITLE
深色模式两个适配bug

### ISSUE THREAD

**Issue by xushet** [CeuiLiSA/Pixiv-Shaft#82]
[<a href="https://sm.ms/image/5kxiLKAXIbMFUhB" target="_blank"><img src="https://i.loli.net/2020/03/15/5kxiLKAXIbMFUhB.jpg" ></a>](url)

**Comment by xushet** [comment]
还有就是评论区编辑框的字在深色模式也是黑的看不清

**Comment by CeuiLiSA** [comment]
好的，我来处理下

**Comment by CeuiLiSA** [comment]
已处理

**Comment by xushet** [comment]
评论编辑框字体在深色模式下无法看清[<img src="https://s1.ax1x.com/2020/03/17/8Nqc0e.png" alt="8Nqc0e.png" border="0" />](url)

**Comment by CeuiLiSA** [comment]
好我继续搞
