### ISSUE TITLE
深色模式字体问题

### ISSUE THREAD

**Issue by xushet** [CeuiLiSA/Pixiv-Shaft#85]
![Screenshot_20200320-235451](https://user-images.githubusercontent.com/34502902/77181595-88f5b000-6b06-11ea-8240-8b53a62544a7.jpg)
看不清楚

**Comment by xushet** [comment]
还有编辑账号界面也是这种问题

**Comment by xushet** [comment]
以图搜源的提示改成增加一个不再提示的按钮会好点，特别是在需要搜多张图片的时候
![Screenshot_20200321-000205_PixShaft](https://user-images.githubusercontent.com/34502902/77182326-85165d80-6b07-11ea-90fa-5f345239098e.png)

**Comment by duzhaokun123** [comment]
好的

**Comment by duzhaokun123** [comment]
另外那个文件名格式你改成`<id>_<title>_<p>.jpg`不然所有保存的标题都会变成`123456789_title_p0.jpg`

下次提交加上自动转换

**Comment by CeuiLiSA** [comment]
已修复
