### ISSUE TITLE
动态页建议改成双列瀑布流

### ISSUE THREAD

**Issue by 610364023** [CeuiLiSA/Pixiv-Shaft#87]
现在只有一列而且显示不全

**Comment by duzhaokun123** [comment]
像这样?
![Screenshot_20200323-180038_PixShaft](https://user-images.githubusercontent.com/39830683/77305327-c76eb300-6d30-11ea-8201-6cf2ab38df25.png)

**Comment by CeuiLiSA** [comment]
现在支持双列了，自行去设置页面开启。下版本更新
