### ISSUE TITLE
无法浏览画师主页

### ISSUE THREAD

**Issue by efsg** [CeuiLiSA/Pixiv-Shaft#90]
环境：Pixel3 10.0
版本：1.5.8
[Log](https://paste.ubuntu.com/p/tVg7SkGt7j)

**Comment by duzhaokun123** [comment]
只在英文环境下出现的 BUG 因为
https://github.com/CeuiLiSA/Pixiv-Shaft/blob/1cd98c92123db2b28094c56e286f100e063c7a45/app/src/main/res/values-en/strings.xml#L95

**Comment by CeuiLiSA** [comment]
好，我知道什么问题，今天离开武汉回上海，晚点处理

**Comment by CeuiLiSA** [comment]
已处理
