### ISSUE TITLE
关于屏幕方向

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#91]
为什么要限制`UActivity`和`MainActivity`竖屏，不限制会有什么后果

**Comment by CeuiLiSA** [comment]
MainActivity 和UActivity里面都有很多个Fragment，数据处理不好容易闪退，参考B站和京东淘宝很多主流APP在主页都没法横屏，所以暂时强制竖屏了

**Comment by duzhaokun123** [comment]
避免重构就可以，不一定要强制竖屏

**Comment by CeuiLiSA** [comment]
相关的我不太了解，麻烦你有空了去调查一下啊，顺便提个PR

**Comment by duzhaokun123** [comment]
```xml
<Activity
    android:configChanges="screenSize|screenLayout|orientation"/>
```
至少在屏幕转向和分屏时不会重构
