### ISSUE TITLE
热度排序

### ISSUE THREAD

**Issue by NibaZShab** [CeuiLiSA/Pixiv-Shaft#94]
热度排序为啥会用不了了呢，真的很遗憾

**Comment by duzhaokun123** [comment]
see #66

**Comment by CeuiLiSA** [comment]
上次确实是因为服务器被ban，这次是因为用作热度排序的会员账号过度请求搜索接口，被pixiv官方警告了，要再这样直接删账号。。所以我怂了，怎么说呢，如果要继续热度排序，可能要维护10个会员账号随机使用，就不会被检测到过渡搜索了

**Comment by Aisaka-t** [comment]
啊这，这也太惨了
