### ISSUE TITLE
建议插画下载成功或失败后有提示

### ISSUE THREAD

**Issue by Saccharum** [CeuiLiSA/Pixiv-Shaft#96]
或者可以在设置里自选显示或者不显示提示

**Comment by CeuiLiSA** [comment]
网速快的话，下载30个作品，50张图，会被这个消息轰炸的。。所以一直没加提示

**Comment by duzhaokun123** [comment]
至少在下载失败时提示一下, 现在的下载器不管是否成功结果都会表现为下载成功

**Comment by CeuiLiSA** [comment]
好的 @duzhaokun123 五一节来写代码啊，在家里哪也不敢去，把剩下该做的功能都做了

**Comment by CeuiLiSA** [comment]
一张图怎么才算下载成功或者下载失败。不知道怎么判断啊

**Comment by duzhaokun123** [comment]
@CeuiLiSA `OkDownload`的任务监听器的`taskEnd()`的`EndCause cause`

详细看官方文档

**Comment by soloopooo** [comment]
要不加写一个下载页面，在里面显示每张图片的下载进度？这样有下载失败或者下载成功的话用红点提示下用户即可，就不需要弹消息框了

**Comment by CeuiLiSA** [comment]
已添加提示
