### ISSUE TITLE
切换账号时崩溃

### ISSUE THREAD

**Issue by ding667** [CeuiLiSA/Pixiv-Shaft#98]
如题…

**Comment by CeuiLiSA** [comment]
问下，是在设置页面点“账号管理”立马 闪退呢
还是进到账号管理页面点某个用户切换的时候才闪退

**Comment by ding667** [comment]
是点击切换到另一个用户的时候崩溃，添加账号的时候都是一切正常的

**Comment by CeuiLiSA** [comment]
麻烦说一下手机型号，确保自己装的是最新版app，去触发一下这个闪退，我后台可以看到错误日志

**Comment by ding667** [comment]
华为Nova青春版
