### ISSUE TITLE
功能 导出登陆的用户

### ISSUE THREAD

**Issue by duzhaokun123** [CeuiLiSA/Pixiv-Shaft#99]
- 方便在开发版和发行版之间切换
- 方便在多设备上登陆

**Comment by CeuiLiSA** [comment]
已处理，拉最新代码

**Comment by duzhaokun123** [comment]
??? 

导出用户名密码有什么用，又不是记不住密码，是不想收到提示邮件

难道不应该导出`UserModel`吗

还有就是谁会把登陆信息做成二维码啊

**Comment by CeuiLiSA** [comment]
熬这个意思啊。我明白了，后面再搞下
